# Generated by Django 3.2.9 on 2022-01-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADSAirport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icao_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADSCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.TextField()),
                ('continent', models.TextField()),
                ('currency_code', models.TextField()),
                ('in_eu', models.BooleanField()),
                ('in_schengen', models.BooleanField()),
                ('in_eea', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADSRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('utc_offset', models.FloatField()),
                ('dst_code', models.IntegerField()),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Code')),
                ('continent', models.CharField(max_length=2, verbose_name='Continent')),
                ('in_eu', models.BooleanField(default=False, verbose_name='In EU?')),
                ('in_schengen', models.BooleanField(default=False, verbose_name='In Schengen?')),
                ('in_eea', models.BooleanField(default=False, verbose_name='In EAA?')),
                ('in_cemac', models.BooleanField(default=False, verbose_name='In CEMAC?')),
                ('in_ecowas', models.BooleanField(default=False, verbose_name='In ECOWAS?')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_plural', models.CharField(max_length=50, verbose_name='Name (Plural)')),
                ('symbol', models.CharField(max_length=50, verbose_name='Symbol')),
                ('division_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Division Name')),
                ('division_factor', models.BigIntegerField(blank=True, null=True, verbose_name='Division Factor')),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('iata_code', models.CharField(max_length=6, verbose_name='IATA Code')),
            ],
            options={
                'db_table': 'fuel_types',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('code', models.CharField(max_length=5, verbose_name='Short Code')),
            ],
            options={
                'db_table': 'uom',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurementSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
            ],
            options={
                'db_table': 'uom_sources',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurementConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usg_conversion_factor', models.DecimalField(decimal_places=8, max_digits=9, verbose_name='To USG Rate')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unitofmeasurementsource', verbose_name='Source')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_factors', to='core.unitofmeasurement', verbose_name='Unit of Measurement')),
            ],
            options={
                'db_table': 'uom_conversion_factors',
            },
        ),
    ]
