# Generated by Django 3.2.9 on 2022-03-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'uom_temperature',
            },
        ),
    ]
