# Generated by Django 3.2.9 on 2022-03-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_temperatureunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'fuel_equipment_types',
            },
        ),
        migrations.AddField(
            model_name='fueltype',
            name='contains_fsii',
            field=models.BooleanField(default=False, verbose_name='Contains FSII'),
        ),
        migrations.AddField(
            model_name='fueltype',
            name='nato_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NATO Code'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='iata_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='IATA Code'),
        ),
    ]
