# Generated by Django 3.2.9 on 2022-03-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220326_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasurement',
            name='is_fluid_uom',
            field=models.BooleanField(default=False, verbose_name='Is Fluid UOM?'),
        ),
    ]
