# Generated by Django 4.0.3 on 2022-04-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmlApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.SlugField(max_length=10, unique=True, verbose_name='Code Name')),
            ],
            options={
                'db_table': 'aml_applications',
                'ordering': ['name'],
            },
        ),
    ]
