# Generated by Django 4.0.3 on 2022-04-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amlapplication',
            name='code',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Code Name'),
        ),
    ]
