# Generated by Django 4.0.3 on 2022-04-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0006_handlingserviceorganisationspecific_and_more'),
        ('core', '0011_alter_amlapplication_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='handling_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='handling.handlingservice'),
        ),
    ]
