# Generated by Django 4.0.3 on 2022-05-15 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comment_handling_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitofmeasurement',
            options={'ordering': ['description']},
        ),
    ]
