# Generated by Django 4.0.3 on 2022-05-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_unitofmeasurement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Is System Tag?'),
        ),
    ]
