# Generated by Django 4.0.3 on 2022-05-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tag_is_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=15, verbose_name='Unit Code')),
                ('currency_division_used', models.BooleanField(default=False, verbose_name='Currency Division Used')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency', verbose_name='Currency')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unitofmeasurement', verbose_name='Unit Of Measurement')),
            ],
            options={
                'db_table': 'pricing_units',
            },
        ),
    ]
