# Generated by Django 4.0.3 on 2022-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pricingunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasurement',
            name='description_plural',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Description Plural'),
            preserve_default=False,
        ),
    ]
