# Generated by Django 4.0.3 on 2022-07-05 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aircardprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircardprefix',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Valid From'),
        ),
    ]
