# Generated by Django 4.0.3 on 2022-07-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aircardprefix_valid_from'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
