# Generated by Django 4.0.3 on 2022-07-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightType',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'flight_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeographichFlightType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'flight_types_geographic',
                'ordering': ['name'],
            },
        ),
    ]
