# Generated by Django 4.0.3 on 2022-09-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0096_alter_dlacontractlocation_options_and_more'),
        ('core', '0020_flighttype_geographichflighttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfacApiException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofac_excepted', to='organisation.organisation', verbose_name='Excepted Organisation')),
            ],
            options={
                'db_table': 'organisations_ofac_api_exceptions',
            },
        ),
    ]
