# Generated by Django 4.0.3 on 2022-10-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ofacapiexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dod_cs_ts', models.TextField(blank=True, null=True, verbose_name='DoD Terms & Conditions')),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'db_table': 'settings',
            },
        ),
    ]
