# Generated by Django 4.0.3 on 2022-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltype',
            name='sg_kg_ltr',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='SG (kg/ltr)'),
        ),
        migrations.AddField(
            model_name='fueltype',
            name='sg_lb_usg',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='SG (lb/usg)'),
        ),
    ]
