# Generated by Django 4.0.3 on 2022-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_fueltype_sg_kg_ltr_fueltype_sg_lb_usg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltype',
            name='contains_prist',
            field=models.BooleanField(default=False, verbose_name='Contains PRIST'),
        ),
    ]
