# Generated by Django 4.0.3 on 2022-11-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fueltype_contains_prist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_fsii', models.BooleanField(default=False, verbose_name='Is FSII?')),
                ('is_lia', models.BooleanField(default=False, verbose_name='Is LIA?')),
            ],
            options={
                'db_table': 'fuel_additives',
            },
        ),
        migrations.CreateModel(
            name='FuelTypeBlend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blends', to='core.fueltype', verbose_name='Fuel')),
            ],
            options={
                'db_table': 'fuel_types_blends',
            },
        ),
        migrations.CreateModel(
            name='FuelTypeBlendComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.fueltypeblend', verbose_name='Blend')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blends_with_fuel', to='core.fueltype', verbose_name='Fuel')),
                ('fuel_additive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blends_with_additive', to='core.fueladditive', verbose_name='Additive')),
                ('component_blend_percentage', models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='Component Blend Percentage')),
            ],
            options={
                'db_table': 'fuel_types_blends_components',
            },
        ),
    ]
