# Generated by Django 4.0.3 on 2022-11-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_fueltype_contains_fsii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltype',
            name='nato_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NATO Code'),
        ),
    ]
