# Generated by Django 4.0.3 on 2022-11-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_last_token_sent_at'),
        ('core', '0028_fueltype_nato_code'),
        ('pricing', '0016_delete_unitofmeasurementconversionmethod')
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurementConversionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_ratio_div', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Conversion Ratio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('specific_fuel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions_specific_for_this_fuel', to='core.fueltype', verbose_name='Specific Fuel')),
                ('uom_converting_from', models.ForeignKey(db_column='uom_converting_from', on_delete=django.db.models.deletion.CASCADE, related_name='conversion_from_methods', to='core.unitofmeasurement', verbose_name='Unit of Measurement')),
                ('uom_converting_to', models.ForeignKey(db_column='uom_converting_to', on_delete=django.db.models.deletion.CASCADE, related_name='conversion_to_methods', to='core.unitofmeasurement', verbose_name='Unit of Measurement')),
                ('updated_by', models.ForeignKey(db_column='updated_by', on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'uom_conversion_methods',
            },
        ),
    ]
