# Generated by Django 4.0.3 on 2022-11-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_unitofmeasurementconversionmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasurementconversionmethod',
            old_name='specific_fuel_id',
            new_name='specific_fuel',
        ),
    ]
