# Generated by Django 4.0.3 on 2022-11-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pricingunit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingunit',
            name='description_short',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Description'),
        ),
    ]
