# Generated by Django 4.0.3 on 2023-03-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_traveldocument_number_and_more'),
        ('aircraft', '0017_aircrafttype_maximum_fuel_indicative_litres_and_more'),
        ('organisation', '0104_operatordetails_crew_weight_and_more'),
        ('core', '0033_pricingunit_description_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author_text', models.CharField(max_length=50, null=True, verbose_name='Author (raw)')),
                ('record_slug', models.SlugField(null=True, verbose_name='Record Slug')),
                ('value_name', models.CharField(max_length=50, null=True, verbose_name='Entity/Field Name')),
                ('value_prev', models.CharField(max_length=50, null=True, verbose_name='Previous Value')),
                ('value_new', models.CharField(max_length=50, null=True, verbose_name='New Value')),
                ('details', models.CharField(max_length=1000, null=True, verbose_name='Details')),
                ('data', models.JSONField()),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='aircraft.aircraft', verbose_name='Aircraft')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_activity_log_records', to='user.person', verbose_name='Author')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='organisation.organisation', verbose_name='Organisation')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='user.person', verbose_name='Person')),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
