# Generated by Django 4.0.3 on 2023-01-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pricingunit_description_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingunit',
            options={'ordering': ['description']},
        ),
    ]
