# Generated by Django 4.0.3 on 2023-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
