# Generated by Django 4.0.3 on 2023-06-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_missionlegservicing_handling_request'),
        ('core', '0035_alter_activitylog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='mission.mission', verbose_name='Mission'),
        ),
    ]
