# Generated by Django 4.0.3 on 2023-07-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_activitylog_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_in_nato',
            field=models.BooleanField(default=False, verbose_name='In NATO?'),
        ),
    ]
