# Generated by Django 4.0.3 on 2023-03-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_activitylog'),
        ('core', '0036_alter_unitofmeasurementconversionfactor_conversion_factor_to_litre'),
    ]

    operations = [
    ]
