# Generated by Django 4.0.3 on 2023-07-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0010_alter_mission_aircraft'),
        ('core', '0037_country_is_in_nato'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='mission_leg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='mission.missionleg', verbose_name='Mission Leg'),
        ),
    ]
