# Generated by Django 4.0.3 on 2023-05-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_activitylog_data'),
        ('core', '0037_merge_20230309_0005'),
    ]

    operations = [
    ]
