# Generated by Django 4.0.3 on 2023-03-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20230309_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasurementconversionfactor',
            name='conversion_factor_to_litre',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Conversion Factor to Litre'),
        ),
    ]
