# Generated by Django 4.0.3 on 2023-04-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_activitylog_data'),
        ('core', '0038_alter_unitofmeasurementconversionfactor_conversion_factor_to_litre'),
    ]

    operations = [
    ]
