# Generated by Django 4.0.3 on 2023-06-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20230505_1344'),
        ('core', '0039_merge_20230421_1154'),
    ]

    operations = [
    ]
