# Generated by Django 4.0.3 on 2023-05-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20230421_1154'),
        ('core', '0040_merge_20230505_1538'),
    ]

    operations = [
    ]
