# Generated by Django 4.0.3 on 2023-06-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('core', '0037_merge_20230613_1714'),
        ('core', '0040_merge_20230608_1617'),
    ]

    operations = [
    ]
