# Generated by Django 4.0.3 on 2023-08-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_permissions_options'),
        ('core', '0041_merge_20230630_0925'),
    ]

    operations = [
    ]
