# Generated by Django 4.0.3 on 2023-08-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='value_new',
            field=models.CharField(max_length=500, null=True, verbose_name='New Value'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='value_prev',
            field=models.CharField(max_length=500, null=True, verbose_name='Previous Value'),
        ),
    ]
