# Generated by Django 4.0.3 on 2023-06-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_activitylog_mission'),
        ('core', '0041_merge_20230519_1557'),
    ]

    operations = [
    ]
