# Generated by Django 4.0.3 on 2023-08-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_permissions_options'),
        ('core', '0042_merge_20230804_1013'),
    ]

    operations = [
    ]
