# Generated by Django 4.0.3 on 2023-06-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('core', '0037_merge_20230613_1714'),
        ('core', '0042_merge_20230602_1250'),
    ]

    operations = [
    ]
