# Generated by Django 4.0.3 on 2023-08-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0086_alter_permissions_options'),
        ('core', '0042_alter_activitylog_value_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='handling_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='handling.handlingrequest', verbose_name='S&F Request'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='handling_request_movement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='handling.handlingrequestmovement', verbose_name='Movement'),
        ),
    ]
