# Generated by Django 4.0.3 on 2023-06-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('core', '0038_merge_20230614_1508'),
        ('core', '0043_merge_20230613_1702'),
    ]

    operations = [
    ]
