# Generated by Django 4.0.3 on 2023-08-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20230807_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApronType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Comment')),
            ],
            options={
                'db_table': 'apron_types',
            },
        ),
    ]
