# Generated by Django 4.0.3 on 2023-08-11 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_activitylog_handling_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
