# Generated by Django 4.0.3 on 2023-06-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20230608_1617'),
        ('core', '0044_merge_20230616_0951'),
    ]

    operations = [
    ]
