# Generated by Django 4.0.3 on 2023-08-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_activitylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='record_slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Record Slug'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='value_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Entity/Field Name'),
        ),
    ]
