# Generated by Django 4.0.3 on 2023-06-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('core', '0037_merge_20230613_1714'),
        ('core', '0045_merge_20230619_1142'),
    ]

    operations = [
    ]
