# Generated by Django 4.0.3 on 2023-08-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0027_alter_mission_aircraft'),
        ('core', '0045_alter_activitylog_record_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='mission_turnaround',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='mission.missionturnaround', verbose_name='Mission Turnaround'),
        ),
    ]
