# Generated by Django 4.0.3 on 2023-06-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20230630_0925'),
        ('core', '0046_merge_20230629_1839'),
    ]

    operations = [
    ]
