# Generated by Django 4.0.3 on 2023-09-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20230807_1403'),
        ('core', '0046_activitylog_mission_turnaround'),
    ]

    operations = [
    ]
