# Generated by Django 4.0.3 on 2023-09-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_aprontype'),
        ('core', '0047_merge_20230901_1450'),
    ]

    operations = [
    ]
