# Generated by Django 4.0.3 on 2023-07-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_activitylog_mission_leg'),
        ('core', '0047_merge_20230630_1131'),
    ]

    operations = [
    ]
