# Generated by Django 4.0.3 on 2023-09-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0029_alter_missionturnaroundservice_updated_by'),
        ('handling', '0089_handlingrequest_is_aog'),
        ('core', '0048_merge_0044_aprontype_0047_merge_20230901_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='handling_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='handling.handlingrequest', verbose_name='Handling Request'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mission.mission', verbose_name='Mission'),
        ),
    ]
