# Generated by Django 4.0.3 on 2023-08-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_permissions_options'),
        ('core', '0048_merge_20230706_1832'),
    ]

    operations = [
    ]
