# Generated by Django 4.0.3 on 2023-09-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_0044_aprontype_0047_merge_20230901_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 'fuel_categories',
            },
        ),
        migrations.AddField(
            model_name='fueltype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_types', to='core.fuelcategory', verbose_name='Category'),
        ),
    ]
