# Generated by Django 4.0.3 on 2023-09-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_comment_handling_request_comment_mission'),
        ('core', '0049_fuelcategory_fueltype_category'),
    ]

    operations = [
    ]
