# Generated by Django 4.0.3 on 2023-08-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_merge_20230804_1013'),
        ('core', '0049_merge_20230803_2314'),
    ]

    operations = [
    ]
