# Generated by Django 4.0.3 on 2023-08-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_permissions_options'),
        ('core', '0050_merge_20230804_1044'),
    ]

    operations = [
    ]
