# Generated by Django 4.0.3 on 2023-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_20230921_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasurement',
            name='is_mass_uom',
            field=models.BooleanField(default=False, verbose_name='Is Mass UOM?'),
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='is_volume_uom',
            field=models.BooleanField(default=False, verbose_name='Is Volume UOM?'),
        ),
    ]
