# Generated by Django 4.0.3 on 2023-08-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20230807_1403'),
        ('core', '0051_merge_20230804_1641'),
    ]

    operations = [
    ]
