# Generated by Django 4.0.3 on 2023-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_unitofmeasurement_is_mass_uom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HookupMethod',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'fuel_hookup_methods',
                'ordering': ['name'],
            },
        ),
    ]
