# Generated by Django 4.0.3 on 2023-10-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelequipmenttype',
            options={'ordering': ['name']},
        ),
    ]
