# Generated by Django 4.0.3 on 2023-08-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_activitylog_created_at'),
        ('core', '0052_merge_20230807_1415'),
    ]

    operations = [
    ]
