# Generated by Django 4.0.3 on 2023-08-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_activitylog_record_slug_and_more'),
        ('core', '0053_merge_20230811_1930'),
    ]

    operations = [
    ]
