# Generated by Django 4.0.3 on 2023-08-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_activitylog_mission_turnaround'),
        ('core', '0054_merge_20230816_2358'),
    ]

    operations = [
    ]
