# Generated by Django 4.2.6 on 2023-11-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
    ]
