# Generated by Django 4.2.6 on 2023-11-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_customnotification_options_and_more'),
        ('core', '0055_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read?')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.comment', verbose_name='Comment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_read_statuses', to='user.person', verbose_name='Person')),
            ],
            options={
                'db_table': 'comments_read_tracking',
            },
        ),
    ]
