# Generated by Django 4.0.3 on 2023-08-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_aprontype'),
        ('core', '0055_merge_20230825_1736'),
    ]

    operations = [
    ]
