# Generated by Django 4.0.3 on 2023-09-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20230901_1450'),
        ('core', '0056_merge_0044_aprontype_0055_merge_20230825_1736'),
    ]

    operations = [
    ]
