# Generated by Django 4.2.6 on 2023-12-19 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_commentreadstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ADSAirport",
        ),
        migrations.DeleteModel(
            name="ADSCountry",
        ),
        migrations.DeleteModel(
            name="ADSRegion",
        ),
    ]
