# Generated by Django 4.0.3 on 2023-09-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_0044_aprontype_0047_merge_20230901_1450'),
        ('core', '0057_merge_20230901_1515'),
    ]

    operations = [
    ]
