# Generated by Django 4.0.3 on 2023-09-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_fuelcategory_fueltype_category'),
        ('core', '0058_merge_20230911_1440'),
    ]

    operations = [
    ]
