# Generated by Django 4.0.3 on 2023-09-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_comment_handling_request_comment_mission'),
        ('core', '0059_merge_20230918_1314'),
    ]

    operations = [
    ]
