# Generated by Django 4.0.3 on 2023-09-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_20230921_0143'),
        ('core', '0060_merge_20230918_2239'),
    ]

    operations = [
    ]
