# Generated by Django 4.0.3 on 2023-09-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_unitofmeasurement_is_mass_uom_and_more'),
        ('core', '0061_merge_20230922_1518'),
    ]

    operations = [
    ]
