# Generated by Django 4.0.3 on 2023-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
        ('core', '0062_merge_20230925_1321'),
    ]

    operations = [
    ]
