# Generated by Django 4.0.3 on 2023-10-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_fuelequipmenttype_options'),
        ('core', '0063_merge_0052_hookupmethod_0062_merge_20230925_1321'),
    ]

    operations = [
    ]
