# Generated by Django 4.0.3 on 2023-10-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_permissions_options'),
        ('core', '0064_merge_20231018_1434'),
    ]

    operations = [
    ]
