# Generated by Django 4.2.6 on 2023-11-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_commentreadstatus'),
        ('core', '0065_merge_20231023_1323'),
    ]

    operations = [
    ]
