# Generated by Django 4.2.6 on 2023-12-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_delete_adsairport_delete_adscountry_delete_adsregion'),
        ('core', '0066_merge_0056_commentreadstatus_0065_merge_20231023_1323'),
    ]

    operations = [
    ]
