# Generated by Django 3.2.9 on 2022-01-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_operator_id', models.BigIntegerField(blank=True, null=True, verbose_name='ADS Operator ID')),
            ],
            options={
                'db_table': 'organisations_operator_details',
            },
        ),
        migrations.CreateModel(
            name='OperatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('operates_private_flights', models.BooleanField(default=False, verbose_name='Private Flights')),
                ('operates_public_transport_flights', models.BooleanField(default=False, verbose_name='Public Transport Flights')),
                ('operates_government_flights', models.BooleanField(default=False, verbose_name='Government Flights')),
                ('operates_military_flights', models.BooleanField(default=False, verbose_name='Military Flights')),
                ('operates_training_flights', models.BooleanField(default=False, verbose_name='Training Flights')),
                ('operates_air_work_flights', models.BooleanField(default=False, verbose_name='Air Work Flights')),
                ('operates_air_ambulance_flights', models.BooleanField(default=False, verbose_name='Air Ambulance Flights')),
                ('operates_special_mission_flights', models.BooleanField(default=False, verbose_name='Special Mission Flights')),
                ('operates_scheduled_passenger_flights', models.BooleanField(default=False, verbose_name='Scheduled Passenger Flights')),
                ('operates_scheduled_cargo_flights', models.BooleanField(default=False, verbose_name='Scheduled Cargo Flights')),
                ('operates_non_scheduled_passenger_flights', models.BooleanField(default=False, verbose_name='Non-Scheduled Passenger Flights')),
                ('operates_non_scheduled_cargo_flights', models.BooleanField(default=False, verbose_name='Non-Scheduled Cargo Flights')),
            ],
            options={
                'db_table': 'organisations_operator_types',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Number')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Is Customer?')),
                ('is_fuel_supplier', models.BooleanField(default=False, verbose_name='Is Fuel Supplier?')),
                ('is_service_provider', models.BooleanField(default=False, verbose_name='Is Service Provider?')),
                ('is_competitor', models.BooleanField(default=False, verbose_name='Is Competitor?')),
                ('is_invoiceable', models.BooleanField(default=False, verbose_name='Is Invoiceable?')),
                ('is_trading', models.BooleanField(default=True, verbose_name='Is Trading?')),
                ('trading_ceased_date', models.DateField(blank=True, null=True, verbose_name='Trading Ceased Date')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='OrganisationPeopleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'organisations_people_roles',
            },
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_end_user', models.BooleanField(verbose_name='Is End User?')),
            ],
            options={
                'db_table': 'organisations_types',
            },
        ),
        migrations.CreateModel(
            name='OrganisationPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Organisation')),
            ],
            options={
                'db_table': 'organisations_people',
            },
        ),
    ]
