# Generated by Django 3.2.9 on 2022-01-25 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('organisation', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpeople',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='organisationpeople',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationpeoplerole', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='department_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Department Of'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='people',
            field=models.ManyToManyField(related_name='organisations', through='organisation.OrganisationPeople', to='user.Person'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organisation.organisationtype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_details', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.operatortype', verbose_name='Operator Type'),
        ),
    ]
