# Generated by Django 3.2.9 on 2022-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpeople',
            name='is_decision_maker',
            field=models.BooleanField(default=False, verbose_name='Is Decision Maker?'),
        ),
        migrations.AddField(
            model_name='organisationpeople',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
