# Generated by Django 3.2.9 on 2022-01-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20220128_1921'),
    ]

    database_operations = [
        # You have to use Django's database table naming defaults to get the
        # name 'tires_tires'. It is basically <app_name>_<model_name>.
        migrations.AlterModelTable('OrganisationPeopleRole', 'people_roles'),
    ]

    # Don't modify the Django 'state' yet
    state_operations = [

    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
