# Generated by Django 3.2.9 on 2022-01-29 16:33

from django.db import models, migrations
from django.db import migrations
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_alter_organisationpeople_role'),
        ('user', '0004_merge_0002_customnotification_0003_personrole'),
    ]

    operations = [
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_alter_organisationpeople_role'),
        ('user', '0003_personrole'),
    ]


    operations = [
        migrations.AlterField(
            model_name='organisationpeople',
            name='role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='user.personrole', verbose_name='Role'),
        ),
    ]
