# Generated by Django 3.2.9 on 2022-01-29 16:37

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20220129_1633'),
    ]
    
    state_operations = [
        migrations.DeleteModel(
            name='OrganisationPeopleRole',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
