# Generated by Django 3.2.9 on 2022-01-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20220129_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
