# Generated by Django 3.2.9 on 2022-01-31 23:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_alter_organisation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'organisations_handler_types',
            },
        ),
        migrations.CreateModel(
            name='HandlerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handles_ba_ga', models.BooleanField(default=False, verbose_name='Handles BA/GA?')),
                ('handles_airlines', models.BooleanField(default=False, verbose_name='Handles Airlines?')),
                ('handles_cargo', models.BooleanField(default=False, verbose_name='Handles Cargo?')),
                ('handles_military', models.BooleanField(default=False, verbose_name='Handles Military?')),
                ('contact_phone', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('ops_phone', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Ops Phone')),
                ('ops_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ops Email')),
                ('ops_frequency', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Ops Frequency')),
                ('is_ipa', models.BooleanField(blank=True, null=True, verbose_name='Is IPA?')),
                ('is_in_gat', models.BooleanField(blank=True, null=True, verbose_name='Is in GAT?')),
                ('is_in_airport_terminal', models.BooleanField(blank=True, null=True, verbose_name='Is in Airprot Terminal?')),
                ('has_pax_lounge', models.BooleanField(blank=True, null=True, verbose_name='Has pax lounge?')),
                ('has_crew_room', models.BooleanField(blank=True, null=True, verbose_name='Has crew room?')),
                ('has_vip_lounge', models.BooleanField(blank=True, null=True, verbose_name='Has VIP lounge?')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='airport.airport', verbose_name='Airport')),
                ('handler_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organisation.handlertype', verbose_name='Handler Type')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handler_details', to='organisation.organisation')),
            ],
            options={
                'db_table': 'organisations_handler_details',
            },
        ),
    ]
