# Generated by Django 3.2.9 on 2022-01-31 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_handlerdetails_handlertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlerdetails',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Contact Phone'),
        ),
    ]
