# Generated by Django 3.2.9 on 2022-02-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_auto_20220131_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlerdetails',
            name='handles_cargo',
            field=models.BooleanField(null=True, verbose_name='Handles Cargo?'),
        ),
    ]
