# Generated by Django 3.2.9 on 2022-02-18 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_code'),
        ('organisation', '0011_auto_20220218_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2')),
                ('line_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 3')),
                ('town_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('post_zip_code', models.CharField(max_length=50, verbose_name='Post Zip Code')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Fax')),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airport.airport', verbose_name='Airport')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Country')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Organisation')),
            ],
            options={
                'db_table': 'organisations_addresses',
            },
        ),
    ]
