# Generated by Django 3.2.9 on 2022-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_organisationaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationaddress',
            name='is_billing_address',
            field=models.BooleanField(default=False, verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='is_physical_address',
            field=models.BooleanField(default=False, verbose_name='Physical Address'),
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='is_postal_address',
            field=models.BooleanField(default=False, verbose_name='Postal Address'),
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='is_primary_address',
            field=models.BooleanField(default=False, verbose_name='Primary Address'),
        ),
    ]
