# Generated by Django 3.2.9 on 2022-02-22 17:45

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_auto_20220218_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='motto',
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=app.storage_backends.OrganisationsLogosStorage(), upload_to='', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='motto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motto'),
        ),
    ]
