# Generated by Django 3.2.9 on 2022-02-22 20:21

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0014_auto_20220222_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatordetails',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='operatordetails',
            name='motto',
        ),
        migrations.CreateModel(
            name='OrganisationLogoMotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, storage=app.storage_backends.OrganisationsLogosStorage(), upload_to='', verbose_name='Logo')),
                ('motto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motto')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Organisation')),
            ],
            options={
                'db_table': 'organisations_logos_mottos',
            },
        ),
    ]
