# Generated by Django 3.2.9 on 2022-03-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_auto_20220222_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationlogomotto',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo_motto', to='organisation.organisation', verbose_name='Organisation'),
        ),
    ]
