# Generated by Django 3.2.9 on 2022-03-24 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_code'),
        ('organisation', '0016_alter_organisationlogomotto_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='department_of',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_competitor',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_fuel_supplier',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_invoiceable',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_service_provider',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_trading',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='tax_number',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='trading_ceased_date',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='organisationtype',
            name='is_end_user',
        ),
        migrations.AddField(
            model_name='organisation',
            name='ofac_api_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OFAC API ID'),
        ),
        migrations.AddField(
            model_name='organisationlogomotto',
            name='cascade_to_departments',
            field=models.BooleanField(default=False, verbose_name='Cascade to Departments?'),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='is_fuel_end_user',
            field=models.BooleanField(default=False, verbose_name='Is Fuel End User?'),
        ),
        migrations.CreateModel(
            name='OrganisationRestricted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Is Customer?')),
                ('is_fuel_seller', models.BooleanField(default=False, verbose_name='Is Fuel Seller?')),
                ('is_service_supplier', models.BooleanField(default=False, verbose_name='Is Service Supplier?')),
                ('is_competitor', models.BooleanField(default=False, verbose_name='Is Competitor?')),
                ('is_invoiceable', models.BooleanField(default=False, verbose_name='Is Invoiceable?')),
                ('invoiceable_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiceables', to='organisation.organisation')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
            options={
                'db_table': 'organisations_restricted',
            },
        ),
        migrations.CreateModel(
            name='OrganisationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=100, verbose_name='Registered Name')),
                ('trading_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trading Name')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Number')),
                ('is_trading', models.BooleanField(default=True, verbose_name='Is Trading?')),
                ('trading_ceased_date', models.DateField(blank=True, null=True, verbose_name='Trading Ceased Date')),
                ('change_effective_date', models.DateField(auto_now_add=True, verbose_name='Change Effective Date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.country', verbose_name='Country')),
                ('department_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Department Of')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='organisation.organisation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organisation.organisationtype', verbose_name='Type')),
            ],
            options={
                'db_table': 'organisations_history',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_current', to='organisation.organisationdetails'),
        ),
    ]
