# Generated by Django 3.2.9 on 2022-03-25 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0017_auto_20220324_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_current', to='organisation.organisationdetails'),
        ),
        migrations.AlterField(
            model_name='organisationdetails',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='organisation.organisation'),
        ),
    ]
