# Generated by Django 3.2.9 on 2022-03-25 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220325_0148'),
        ('organisation', '0018_auto_20220325_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationpeople',
            name='title',
        ),
        migrations.AddField(
            model_name='organisationpeople',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title'),
        ),
        migrations.CreateModel(
            name='OrganisationPeopleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_decision_maker', models.BooleanField(default=False, verbose_name='Is Decision Maker?')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title')),
                ('change_effective_date', models.DateField(auto_now_add=True, verbose_name='Change Effective Date')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Organisation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person', verbose_name='Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personrole', verbose_name='Role')),
            ],
            options={
                'db_table': 'organisations_people_history',
            },
        ),
    ]
