# Generated by Django 3.2.9 on 2022-03-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_auto_20220325_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ofac_api_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OFAC API ID'),
        ),
    ]
