# Generated by Django 3.2.9 on 2022-03-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0023_airportdetails_airportweightunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportdetails',
            name='icao_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ICAO Code'),
        ),
    ]
