# Generated by Django 3.2.9 on 2022-03-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0024_alter_airportdetails_icao_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlerdetails',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='organisationaddress',
            name='airport',
        ),
    ]
