# Generated by Django 3.2.9 on 2022-03-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0025_auto_20220327_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationaddress',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_organisations_addresses', to='organisation.organisation', verbose_name='Airport'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organisation.organisation', verbose_name='Organisation'),
        ),
    ]
