# Generated by Django 3.2.9 on 2022-03-27 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0026_auto_20220327_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlerdetails',
            name='airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='airport_handlers', to='organisation.organisation', verbose_name='Airport'),
            preserve_default=False,
        ),
    ]
