# Generated by Django 3.2.9 on 2022-03-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220326_0101'),
        ('organisation', '0027_handlerdetails_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ipa_locations',
            field=models.ManyToManyField(related_name='ipa_locations_reverse', through='organisation.IpaLocation', to='organisation.Organisation'),
        ),
        migrations.CreateModel(
            name='DaoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 1')),
                ('contact_email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2')),
                ('contact_phone_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Phone 1')),
                ('contact_phone_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Phone 2')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dao_details', to='organisation.organisation')),
            ],
            options={
                'db_table': 'organisations_dao_details',
            },
        ),
        migrations.CreateModel(
            name='DaoCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('responsible_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_dao', to='core.country', verbose_name='Contry')),
            ],
            options={
                'db_table': 'organisations_dao_countries',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='dao_countries',
            field=models.ManyToManyField(related_name='dao_countries_reverse', through='organisation.DaoCountry', to='organisation.Organisation'),
        ),
    ]
