# Generated by Django 3.2.9 on 2022-03-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220326_0101'),
        ('organisation', '0028_auto_20220327_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='dao_countries',
            field=models.ManyToManyField(through='organisation.DaoCountry', to='core.Country'),
        ),
    ]
