# Generated by Django 3.2.9 on 2022-03-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0030_alter_daocountry_responsible_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlertype',
            name='is_fbo',
            field=models.BooleanField(default=False, verbose_name='Is FBO?'),
        ),
    ]
