# Generated by Django 3.2.9 on 2022-03-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0031_handlertype_is_fbo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlerdetails',
            name='is_ipa',
        ),
    ]
