# Generated by Django 3.2.9 on 2022-03-27 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0032_remove_handlerdetails_is_ipa'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatordetails',
            name='commercial_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='commercial_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='ops_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='operatordetails',
            name='ops_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Phone'),
        ),
    ]
