# Generated by Django 3.2.9 on 2022-03-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0033_auto_20220327_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasdlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'db_table': 'organisations_nasdl_types',
            },
        ),
        migrations.CreateModel(
            name='NasdlDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('what3words_code', models.CharField(max_length=255, verbose_name='3 Words Code')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nasdl_details', to='organisation.organisation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organisation.hasdltype', verbose_name='Type')),
            ],
            options={
                'db_table': 'organisations_nasdl_details',
            },
        ),
    ]
