# Generated by Django 4.0.3 on 2022-04-03 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0035_remove_nasdldetails_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'permissions': [('add_aircraft_operator', 'Add Aircraft Operator')]},
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='commercial_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Commercial Email Address'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='commercial_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Commercial Phone Number'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email Address'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='ops_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Operations Email Number'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='ops_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Operations Phone Number'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='is_billing_address',
            field=models.BooleanField(default=False, verbose_name='Billing Address?'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='is_physical_address',
            field=models.BooleanField(default=False, verbose_name='Physical Address?'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='is_postal_address',
            field=models.BooleanField(default=False, verbose_name='Postal Address?'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='is_primary_address',
            field=models.BooleanField(default=False, verbose_name='Primary Address?'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State / County'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='town_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town / City'),
        ),
        migrations.AlterField(
            model_name='organisationrestricted',
            name='is_competitor',
            field=models.BooleanField(default=False, verbose_name='Competitor?'),
        ),
        migrations.AlterField(
            model_name='organisationrestricted',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Customer?'),
        ),
        migrations.AlterField(
            model_name='organisationrestricted',
            name='is_fuel_seller',
            field=models.BooleanField(default=False, verbose_name='Fuel Seller?'),
        ),
        migrations.AlterField(
            model_name='organisationrestricted',
            name='is_invoiceable',
            field=models.BooleanField(default=False, verbose_name='Invoiceable?'),
        ),
        migrations.AlterField(
            model_name='organisationrestricted',
            name='is_service_supplier',
            field=models.BooleanField(default=False, verbose_name='Service Supplier?'),
        ),
        migrations.AlterField(
            model_name='organisationrestricted',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_restricted', to='organisation.organisation'),
        ),
    ]
