# Generated by Django 4.0.3 on 2022-04-04 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0036_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatordetails',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Contact Email Address'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='contact_phone',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_organisations_addresses', to='organisation.organisation', verbose_name='Airport'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='is_billing_address',
            field=models.BooleanField(default=True, verbose_name='Billing Address?'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='town_city',
            field=models.CharField(max_length=100, null=True, verbose_name='Town / City'),
        ),
        migrations.AlterField(
            model_name='organisationrestricted',
            name='is_invoiceable',
            field=models.BooleanField(default=True, verbose_name='Invoiceable?'),
        ),
    ]
