# Generated by Django 4.0.3 on 2022-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag'),
        ('organisation', '0038_organisationtag_organisation_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='organisations', through='organisation.OrganisationTag', to='core.tag'),
        ),
    ]
