# Generated by Django 4.0.3 on 2022-04-07 22:31

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0039_alter_organisation_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('organisation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationtype', verbose_name='Organisation Type')),
            ],
            options={
                'db_table': 'organisations_documents_types',
            },
        ),
        migrations.CreateModel(
            name='OrganisationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('file', models.FileField(storage=app.storage_backends.OrganisationDocumentStorage(), upload_to='', verbose_name='Document File')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organisation.organisation', verbose_name='Organisation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationdocumenttype', verbose_name='Document Type')),
            ],
            options={
                'db_table': 'organisations_documents',
            },
        ),
    ]
