# Generated by Django 4.0.3 on 2022-04-07 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag'),
        ('organisation', '0040_organisationdocumenttype_organisationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpaLocationFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipa_locations', to='core.fueltype', verbose_name='Fuel Type')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_fuel', to='organisation.ipalocation')),
            ],
            options={
                'db_table': 'organisations_ipa_locations_fuel',
            },
        ),
    ]
