# Generated by Django 4.0.3 on 2022-04-07 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0041_ipalocationfuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSupportCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'organisations_trip_support_customers',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='trip_support_customers',
            field=models.ManyToManyField(related_name='trip_support_customers_reverse', through='organisation.TripSupportCustomer', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='tripsupportcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_support', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='tripsupportcustomer',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
        ),
    ]
