# Generated by Django 4.0.3 on 2022-04-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0042_tripsupportcustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasdldetails',
            name='comment_guidance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment Guidance'),
        ),
        migrations.AddField(
            model_name='nasdldetails',
            name='use_address',
            field=models.BooleanField(default=False, verbose_name='Use Address?'),
        ),
    ]
