# Generated by Django 4.0.3 on 2022-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0043_nasdldetails_comment_guidance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlerdetails',
            name='is_in_cargo_centre',
            field=models.BooleanField(default=False, verbose_name='In Cargo Centre?'),
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='is_in_airport_terminal',
            field=models.BooleanField(blank=True, null=True, verbose_name='In Airprot Terminal?'),
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='is_in_gat',
            field=models.BooleanField(blank=True, null=True, verbose_name='In GAT?'),
        ),
    ]
