# Generated by Django 4.0.3 on 2022-04-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0044_handlerdetails_is_in_cargo_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportdetails',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Website URL'),
        ),
    ]
