# Generated by Django 4.0.3 on 2022-04-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0045_airportdetails_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipalocationequipment',
            name='registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration'),
        ),
    ]
