# Generated by Django 4.0.3 on 2022-04-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_person_aircraft_types'),
        ('organisation', '0046_ipalocationequipment_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdldetails',
            name='comment_guidance',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment Guidance'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_people', to='organisation.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_people', to='user.person', verbose_name='Person'),
        ),
    ]
