# Generated by Django 4.0.3 on 2022-04-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0048_groundservice_groundservicedeicingtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation')]},
        ),
        migrations.AlterField(
            model_name='ipalocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipa_locations_here', to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='ipalocation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipa_locations_rev', to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ipa_locations',
            field=models.ManyToManyField(related_name='ipas_here', through='organisation.IpaLocation', to='organisation.organisation'),
        ),
    ]
