# Generated by Django 4.0.3 on 2022-04-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0049_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundservicedeicingtype',
            name='colour',
            field=models.CharField(max_length=50, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='groundservicedeicingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
