# Generated by Django 4.0.3 on 2022-04-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0050_alter_groundservicedeicingtype_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationserviceproviderlocation',
            name='delivery_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_locations_here', to='organisation.organisation', verbose_name='Delivery Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisationserviceproviderlocation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_locations', to='organisation.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='organisationserviceproviderlocationservice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organisation.organisationserviceproviderlocation', verbose_name='Location'),
        ),
    ]
