# Generated by Django 4.0.3 on 2022-04-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0051_organisationserviceproviderlocation_delivery_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_agent', 'View Fuel Agent'), ('change_fuel_agent', 'Edit (change) Fuel Agent')]},
        ),
    ]
