# Generated by Django 4.0.3 on 2022-04-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0052_alter_organisation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_agent', 'View Fuel Agent'), ('change_fuel_agent', 'Edit (change) Fuel Agent'), ('view_fuel_reseller', 'View Fuel Reseller'), ('change_fuel_reseller', 'Edit (change) Fuel Reseller')]},
        ),
        migrations.AlterField(
            model_name='organisationdetails',
            name='department_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organisation.organisation', verbose_name='Department Of'),
        ),
    ]
