# Generated by Django 4.0.3 on 2022-04-13 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0053_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airportweightunit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='handlertype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='operatortype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['details__registered_name'], 'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_agent', 'View Fuel Agent'), ('change_fuel_agent', 'Edit (change) Fuel Agent'), ('view_fuel_reseller', 'View Fuel Reseller'), ('change_fuel_reseller', 'Edit (change) Fuel Reseller')]},
        ),
        migrations.AlterModelOptions(
            name='organisationdocumenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='airport',
            field=models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_organisations_addresses', to='organisation.organisation', verbose_name='Airport'),
        ),
    ]
