# Generated by Django 4.0.3 on 2022-04-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_persondetails_abbreviated_name'),
        ('organisation', '0054_alter_airportweightunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpeoplehistory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_people_history', to='user.person', verbose_name='Person'),
        ),
    ]
