# Generated by Django 4.0.3 on 2022-04-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0055_alter_organisationpeoplehistory_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpeople',
            name='job_title',
            field=models.CharField(default='Job Title', max_length=50, verbose_name='Job Title'),
            preserve_default=False,
        ),
    ]
