# Generated by Django 4.0.3 on 2022-04-15 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0057_alter_organisationpeoplehistory_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationpeoplehistory',
            old_name='change_effective_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='organisationpeople',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Starting Date'),
            preserve_default=False,
        ),
    ]
