# Generated by Django 4.0.3 on 2022-04-15 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0058_rename_change_effective_date_organisationpeoplehistory_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpeoplehistory',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Starting Date'),
            preserve_default=False,
        ),
    ]
