# Generated by Django 4.0.3 on 2022-04-15 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_personrole_options_and_more'),
        ('organisation', '0059_organisationpeoplehistory_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpeople',
            name='contact_email',
            field=models.EmailField(default='None', max_length=254, verbose_name='Personal Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationpeople',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Personal Phone'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_people', to='organisation.organisation', verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personrole', verbose_name='Job Role'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Starting Date'),
        ),
    ]
