# Generated by Django 4.0.3 on 2022-04-16 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_amlapplication'),
        ('organisation', '0060_organisationpeople_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPersonPositionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.amlapplication', verbose_name='Application')),
            ],
            options={
                'db_table': 'organisations_people_applications',
            },
        ),
        migrations.AddField(
            model_name='organisationpeople',
            name='applications_access',
            field=models.ManyToManyField(blank=True, related_name='organisation_people', through='organisation.OrganisationPersonPositionApplication', to='core.amlapplication'),
        ),
        migrations.AddField(
            model_name='organisationpersonpositionapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_applications', to='organisation.organisationpeople', verbose_name='Position'),
        ),
    ]
