# Generated by Django 4.0.3 on 2022-04-16 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0061_organisationpersonpositionapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlerdetails',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)(\\s?)+\\d(\\s?\\d){6,20}$')], verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='ops_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)(\\s?)+\\d(\\s?\\d){6,20}$')], verbose_name='Ops Phone'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='commercial_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)(\\s?)+\\d(\\s?\\d){6,20}$')], verbose_name='Commercial Phone Number'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='contact_phone',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)(\\s?)+\\d(\\s?\\d){6,20}$')], verbose_name='Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='ops_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)(\\s?)+\\d(\\s?\\d){6,20}$')], verbose_name='Operations Phone Number'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='fax',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)(\\s?)+\\d(\\s?\\d){6,20}$')], verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)(\\s?)+\\d(\\s?\\d){6,20}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)(\\s?)+\\d(\\s?\\d){6,20}$')], verbose_name='Personal Phone'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Starting Date'),
        ),
        migrations.AlterField(
            model_name='organisationpeoplehistory',
            name='end_date',
            field=models.DateField(auto_now_add=True, verbose_name='End Date'),
        ),
    ]
