# Generated by Django 4.0.3 on 2022-04-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0010_alter_aircrafthistory_homebase'),
        ('organisation', '0062_alter_handlerdetails_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPersonPositionAircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircrafttype', verbose_name='Application')),
            ],
            options={
                'db_table': 'organisations_people_aircraft_types',
            },
        ),
        migrations.AddField(
            model_name='organisationpeople',
            name='aircraft_types',
            field=models.ManyToManyField(blank=True, related_name='organisation_people', through='organisation.OrganisationPersonPositionAircraftType', to='aircraft.aircrafttype'),
        ),
        migrations.AddField(
            model_name='organisationpersonpositionaircrafttype',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_aircraft_types', to='organisation.organisationpeople', verbose_name='Position'),
        ),
    ]
