# Generated by Django 4.0.3 on 2022-04-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0010_alter_aircrafthistory_homebase'),
        ('organisation', '0063_organisationpersonpositionaircrafttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationAircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircrafttype', verbose_name='Aircraft Type')),
            ],
            options={
                'db_table': 'organisations_aircraft_types',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='aircraft_types',
            field=models.ManyToManyField(blank=True, related_name='organisations', through='organisation.OrganisationAircraftType', to='aircraft.aircrafttype'),
        ),
        migrations.AlterField(
            model_name='organisationpersonpositionaircrafttype',
            name='aircraft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircrafttype', verbose_name='Aircraft Type'),
        ),
        migrations.AddField(
            model_name='organisationaircrafttype',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_aircrafts', to='organisation.organisation', verbose_name='Organisation'),
        ),
    ]
