# Generated by Django 4.0.3 on 2022-04-19 00:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment'),
        ('aircraft', '0011_alter_aircrafthistory_homebase'),
        ('organisation', '0064_organisationaircrafttype_organisation_aircraft_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlerdetails',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='ops_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Ops Phone'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='commercial_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Commercial Phone Number'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='contact_phone',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='operatordetails',
            name='ops_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Operations Phone Number'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='airport',
            field=models.ForeignKey(blank=True, limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_organisations_addresses', to='organisation.organisation', verbose_name='Airport'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='fax',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='aircraft_types',
            field=models.ManyToManyField(blank=True, related_name='organisation_people', through='organisation.OrganisationPersonPositionAircraftType', to='aircraft.aircrafttype', verbose_name='Aircraft Types'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='applications_access',
            field=models.ManyToManyField(blank=True, related_name='organisation_people', through='organisation.OrganisationPersonPositionApplication', to='core.amlapplication', verbose_name='Applications Access'),
        ),
        migrations.AlterField(
            model_name='organisationpeople',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Personal Phone'),
        ),
    ]
