# Generated by Django 4.0.3 on 2022-04-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0066_alter_organisation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipalocationfuel',
            old_name='location',
            new_name='ipa_location',
        ),
    ]
