# Generated by Django 4.0.3 on 2022-04-20 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0068_rename_location_ipalocationequipment_ipa_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipalocation',
            name='location',
            field=models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='ipa_locations_here', to='organisation.organisation'),
        ),
    ]
