# Generated by Django 4.0.3 on 2022-04-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0069_alter_ipalocation_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['details__registered_name'], 'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_agent', 'View Fuel Agent'), ('change_fuel_agent', 'Edit (change) Fuel Agent'), ('view_fuel_reseller', 'View Fuel Reseller'), ('change_fuel_reseller', 'Edit (change) Fuel Reseller'), ('change_ipa', 'Edit (change) Into-Plane Agent (IPA)'), ('change_handler', 'Edit (change) Ground Handler')]},
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='airport',
            field=models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, on_delete=django.db.models.deletion.RESTRICT, related_name='airport_handlers', to='organisation.organisation', verbose_name='Airport'),
        ),
    ]
