# Generated by Django 4.0.3 on 2022-04-22 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment'),
        ('organisation', '0070_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilcoFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilco_fuel_types', to='core.fueltype', verbose_name='Fuel Type')),
            ],
            options={
                'db_table': 'organisations_oilco_fuel_types',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='oilco_fuel_types',
            field=models.ManyToManyField(blank=True, related_name='oilco_organisations', through='organisation.OilcoFuelType', to='core.fueltype'),
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='has_crew_room',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has Crew Room?'),
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='has_pax_lounge',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has Pax Lounge?'),
        ),
        migrations.AlterField(
            model_name='handlerdetails',
            name='is_in_airport_terminal',
            field=models.BooleanField(blank=True, null=True, verbose_name='In Airport Terminal?'),
        ),
        migrations.AddField(
            model_name='oilcofueltype',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilco_fuel', to='organisation.organisation'),
        ),
        migrations.CreateModel(
            name='OilcoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=10, null=True, verbose_name='IATA Code')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oilco_details', to='organisation.organisation')),
            ],
            options={
                'db_table': 'organisations_oilco_details',
            },
        ),
    ]
