# Generated by Django 4.0.3 on 2022-04-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment'),
        ('organisation', '0071_oilcofueltype_organisation_oilco_fuel_types_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['details__registered_name'], 'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_agent', 'View Fuel Agent'), ('change_fuel_agent', 'Edit (change) Fuel Agent'), ('view_fuel_reseller', 'View Fuel Reseller'), ('change_fuel_reseller', 'Edit (change) Fuel Reseller'), ('change_ipa', 'Edit (change) Into-Plane Agent (IPA)'), ('change_handler', 'Edit (change) Ground Handler'), ('change_oilco', 'Edit (change) Oil Company (OilCo)')]},
        ),
        migrations.AlterField(
            model_name='organisation',
            name='oilco_fuel_types',
            field=models.ManyToManyField(blank=True, related_name='oilco_organisations', through='organisation.OilcoFuelType', to='core.fueltype', verbose_name='Fuel Types Produced'),
        ),
    ]
