# Generated by Django 4.0.3 on 2022-04-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0072_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdldetails',
            name='comment_guidance',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location Comments / Guidance'),
        ),
        migrations.AlterField(
            model_name='nasdldetails',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='nasdldetails',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='nasdldetails',
            name='use_address',
            field=models.BooleanField(default=False, verbose_name='Use Address for Location?'),
        ),
        migrations.AlterField(
            model_name='nasdldetails',
            name='what3words_code',
            field=models.CharField(max_length=255, null=True, verbose_name='What3Words Code'),
        ),
    ]
