# Generated by Django 4.0.3 on 2022-04-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0073_alter_nasdldetails_comment_guidance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HasdlType',
            new_name='NasdlType',
        ),
    ]
