# Generated by Django 4.0.3 on 2022-04-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0074_rename_hasdltype_nasdltype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['details__registered_name'], 'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_agent', 'View Fuel Agent'), ('change_fuel_agent', 'Edit (change) Fuel Agent'), ('view_fuel_reseller', 'View Fuel Reseller'), ('change_fuel_reseller', 'Edit (change) Fuel Reseller'), ('change_ipa', 'Edit (change) Into-Plane Agent (IPA)'), ('change_handler', 'Edit (change) Ground Handler'), ('change_oilco', 'Edit (change) Oil Company (OilCo)'), ('change_nasdl', 'Edit (change) Non-Airport Location (NASDL)')]},
        ),
        migrations.AlterField(
            model_name='nasdldetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='nasdldetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='nasdldetails',
            name='what3words_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='What3Words Code'),
        ),
    ]
