# Generated by Django 4.0.3 on 2022-04-26 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0075_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['details__registered_name'], 'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_agent', 'View Fuel Agent'), ('change_fuel_agent', 'Edit (change) Fuel Agent'), ('view_fuel_reseller', 'View Fuel Reseller'), ('change_fuel_reseller', 'Edit (change) Fuel Reseller'), ('change_ipa', 'Edit (change) Into-Plane Agent (IPA)'), ('change_handler', 'Edit (change) Ground Handler'), ('change_oilco', 'Edit (change) Oil Company (OilCo)'), ('change_nasdl', 'Edit (change) Non-Airport Location (NASDL)'), ('change_service_provider', 'Edit (change) Service Provider')]},
        ),
        migrations.AlterField(
            model_name='organisationserviceproviderlocation',
            name='delivery_location',
            field=models.ForeignKey(limit_choices_to={'details__type_id__in': [8, 1002]}, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_locations_here', to='organisation.organisation', verbose_name='Delivery Location'),
        ),
    ]
