# Generated by Django 4.0.3 on 2022-04-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0076_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripSupportCustomer',
            new_name='TripSupportClient',
        ),
    ]
