# Generated by Django 4.0.3 on 2022-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0077_rename_tripsupportcustomer_tripsupportclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripsupportclient',
            old_name='customer',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='trip_support_customers',
        ),
        migrations.AddField(
            model_name='organisation',
            name='trip_support_clients',
            field=models.ManyToManyField(related_name='trip_support_clients_reverse', through='organisation.TripSupportClient', to='organisation.organisation'),
        ),
    ]
