# Generated by Django 4.0.3 on 2022-04-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0078_rename_customer_tripsupportclient_client_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tripsupportclient',
            table='organisations_trip_support_clients',
        ),
    ]
