# Generated by Django 4.0.3 on 2022-04-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0079_alter_tripsupportclient_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['details__registered_name'], 'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_agent', 'View Fuel Agent'), ('change_fuel_agent', 'Edit (change) Fuel Agent'), ('view_fuel_reseller', 'View Fuel Reseller'), ('change_fuel_reseller', 'Edit (change) Fuel Reseller'), ('change_ipa', 'Edit (change) Into-Plane Agent (IPA)'), ('change_handler', 'Edit (change) Ground Handler'), ('change_oilco', 'Edit (change) Oil Company (OilCo)'), ('change_nasdl', 'Edit (change) Non-Airport Location (NASDL)'), ('change_service_provider', 'Edit (change) Service Provider'), ('change_trip_support_company', 'Edit (change) Trip Support Company')]},
        ),
        migrations.AlterField(
            model_name='tripsupportclient',
            name='client',
            field=models.ForeignKey(limit_choices_to={'details__type_id': 1, 'operator_details__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='trip_support_companies', to='organisation.organisation'),
        ),
    ]
