# Generated by Django 4.0.3 on 2022-04-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0082_alter_organisation_ofac_latest_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['details__registered_name'], 'permissions': [('add_aircraft_operator', 'Add Aircraft Operator'), ('view_aircraft_operator', 'View Aircraft Operator Organisation'), ('view_airport', 'View Airport Organisation'), ('view_dao', 'View DAO (Defense Attache Offices)'), ('view_fuel_reseller', 'View Fuel Reseller'), ('change_fuel_reseller', 'Edit (change) Fuel Reseller'), ('change_ipa', 'Edit (change) Into-Plane Agent (IPA)'), ('change_handler', 'Edit (change) Ground Handler'), ('change_oilco', 'Edit (change) Oil Company (OilCo)'), ('change_nasdl', 'Edit (change) Non-Airport Location (NASDL)'), ('change_service_provider', 'Edit (change) Service Provider'), ('change_trip_support_company', 'Edit (change) Trip Support Company')]},
        ),
    ]
