# Generated by Django 4.0.3 on 2022-05-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0083_alter_organisation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilcodetails',
            name='iata_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IATA Code'),
        ),
    ]
