# Generated by Django 4.0.3 on 2022-05-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tag_is_system'),
        ('organisation', '0085_alter_organisation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='organisations', through='organisation.OrganisationTag', to='core.tag'),
        ),
    ]
