# Generated by Django 4.0.3 on 2022-05-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0013_alter_aircrafttype_options'),
        ('organisation', '0086_alter_organisation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='aircraft_types',
            field=models.ManyToManyField(blank=True, related_name='organisations', through='organisation.OrganisationAircraftType', to='aircraft.aircrafttype', verbose_name='Types Operated'),
        ),
    ]
