# Generated by Django 4.0.3 on 2022-05-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0088_alter_organisationpeople_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ['name']},
        ),
    ]
