# Generated by Django 4.0.3 on 2022-07-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0089_alter_organisationtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationlogomotto',
            name='cascade_to_departments',
            field=models.BooleanField(default=False, verbose_name='Cascade Logo/Motto to Departments?'),
        ),
    ]
