# Generated by Django 4.0.3 on 2022-08-29 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0090_alter_organisationlogomotto_cascade_to_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLAContractLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_reference', models.CharField(max_length=50, verbose_name='Contract Reference')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('early_termination_date', models.DateField(default=True, null=True, verbose_name='Early Termination Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'organisations_dla_contracts',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='dla_contracted_locations',
            field=models.ManyToManyField(related_name='dla_contracted_suppliers', through='organisation.DLAContractLocation', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='dlacontractlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dla_contracted_locations_here', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='dlacontractlocation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dla_contracted_locations_rev', to='organisation.organisation'),
        ),
    ]
