# Generated by Django 4.0.3 on 2022-09-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0091_dlacontractlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlacontractlocation',
            name='ipa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dla_contracted_locations_ipa_rev', to='organisation.organisation', verbose_name='IPA'),
        ),
    ]
