# Generated by Django 4.0.3 on 2022-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0092_dlacontractlocation_ipa'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationaircrafttype',
            name='mtow_override_kg',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='MTOW Override KG'),
        ),
        migrations.AddField(
            model_name='organisationaircrafttype',
            name='mtow_override_lbs',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='MTOW Override LBS'),
        ),
    ]
