# Generated by Django 4.0.3 on 2022-09-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0009_dlalocationalternativeicaocode'),
        ('organisation', '0094_alter_dlacontractlocation_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlacontractlocation',
            name='cis_supplier_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dla_contracts_using_this_name', to='dla_scraper.dlasuppliername', verbose_name='CIS Supplier Name'),
        ),
    ]
