# Generated by Django 4.0.3 on 2022-09-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0011_alter_dlacontract_options_alter_dlacontract_table'),
        ('organisation', '0095_dlacontractlocation_cis_supplier_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlacontractlocation',
            options={'permissions': [('view_dla_scraper', 'Can view DLA scraper logs'), ('run_dla_scraper', 'Can run DLA scraper')]},
        ),
        migrations.AddField(
            model_name='dlacontractlocation',
            name='cis_ipa_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dla_contracts_using_ipa_name', to='dla_scraper.dlasuppliername', verbose_name='CIS IPA Name'),
        ),
        migrations.AlterField(
            model_name='dlacontractlocation',
            name='cis_supplier_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dla_contracts_using_supplier_name', to='dla_scraper.dlasuppliername', verbose_name='CIS Supplier Name'),
        ),
        migrations.AlterField(
            model_name='dlacontractlocation',
            name='early_termination_date',
            field=models.DateField(null=True, verbose_name='Early Termination Date'),
        ),
    ]
