# Generated by Django 4.0.3 on 2022-10-10 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0097_dlacontractlocation_expiring_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipalocation',
            name='location_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='ipalocation',
            name='location_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Phone'),
        ),
    ]
