# Generated by Django 4.0.3 on 2022-11-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0098_ipalocation_location_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airportdetails',
            name='currency_override',
        ),
        migrations.RemoveField(
            model_name='airportdetails',
            name='has_pricing',
        ),
        migrations.RemoveField(
            model_name='airportdetails',
            name='is_active',
        ),
    ]
