# Generated by Django 4.0.3 on 2022-11-16 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0099_remove_airportdetails_currency_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportdetails',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='airportdetails',
            name='updated_by_ads_person_id',
            field=models.BigIntegerField(null=True, verbose_name='Updated By ADS Person'),
        ),
        migrations.AlterField(
            model_name='organisationdetails',
            name='change_effective_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Change Effective Date'),
        ),
    ]
