# Generated by Django 4.0.3 on 2023-01-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0100_airportdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPreferredGroundHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_handler', models.ForeignKey(limit_choices_to={'details__type_id': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_handler_operators', to='organisation.organisation', verbose_name='Ground Handler')),
                ('location', models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='location_preferred_handlers', to='organisation.organisation', verbose_name='Location')),
                ('organisation', models.ForeignKey(limit_choices_to={'details__type_id': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='operator_preferred_handlers', to='organisation.organisation', verbose_name='Organisation')),
            ],
            options={
                'db_table': 'organisations_operators_preferred_handlers',
            },
        ),
    ]
