# Generated by Django 4.0.3 on 2023-01-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0101_operatorpreferredgroundhandler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorpreferredgroundhandler',
            name='ground_handler',
            field=models.ForeignKey(limit_choices_to={'details__type_id': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_handler_operators', to='organisation.organisation', verbose_name='Preferred Ground Handler'),
        ),
    ]
