# Generated by Django 4.0.3 on 2023-01-19 12:38

from django.db import migrations, models
import django.db.models.deletion


def update_organisations(apps, schema):
    organisation_cls = apps.get_model('organisation', 'Organisation')
    ops_details_cls = apps.get_model('organisation', 'OrganisationOpsDetails')

    ground_handlers = organisation_cls.objects.filter(details__type_id=3).all()

    for organisation in ground_handlers:
        ops_details_cls.objects.update_or_create(
            organisation_id=organisation.pk,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0102_alter_operatorpreferredgroundhandler_ground_handler'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationOpsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receives_parking_chase_email', models.BooleanField(default=True, verbose_name='Receives Automated Parking Chase Emails?')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ops_details', to='organisation.organisation', verbose_name='Organisation')),
            ],
            options={
                'db_table': 'organisations_ops_details',
            },
        ),
        migrations.RunPython(update_organisations),
    ]
