# Generated by Django 4.0.3 on 2023-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0104_operatordetails_crew_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationopsdetails',
            name='spf_use_aml_logo',
            field=models.BooleanField(default=True, verbose_name='Use AML Logo in SPF?'),
        ),
    ]
