# Generated by Django 4.0.3 on 2023-03-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_activitylog'),
        ('organisation', '0104_operatordetails_crew_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_credit', models.BooleanField(verbose_name='Credit?')),
                ('is_on_account', models.BooleanField(verbose_name='Account?')),
                ('is_cash', models.BooleanField(verbose_name='Cash?')),
                ('is_card', models.BooleanField(verbose_name='Card?')),
            ],
            options={
                'db_table': 'organisations_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='OrganisationAcceptedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='Currency')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organisation.organisation', verbose_name='Organisation')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationpaymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'db_table': 'organisations_accepted_payment_methods',
            },
        ),
    ]
