# Generated by Django 4.0.3 on 2023-03-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0105_organisationpaymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationacceptedpaymentmethod',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_payment_method', to='organisation.organisationpaymentmethod', verbose_name='Payment Method'),
        ),
    ]
