# Generated by Django 4.0.3 on 2023-04-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0105_organisationopsdetails_spf_use_aml_logo'),
        ('organisation', '0106_alter_organisationacceptedpaymentmethod_payment_method'),
    ]

    operations = [
    ]
