# Generated by Django 4.0.3 on 2023-06-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0106_organisationpeople_is_authorising_person_and_more'),
        ('organisation', '0107_merge_20230505_1344'),
    ]

    operations = [
    ]
