# Generated by Django 4.0.3 on 2023-05-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0107_merge_20230505_1344'),
        ('organisation', '0108_merge_20230503_1555'),
    ]

    operations = [
    ]
