# Generated by Django 4.0.3 on 2023-06-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('organisation', '0109_merge_20230505_1538'),
    ]

    operations = [
    ]
