# Generated by Django 4.0.3 on 2023-10-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0110_organisationcontactdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcontactdetails',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_contact_details', to='organisation.organisation', verbose_name='Organisation'),
        ),
    ]
