# Generated by Django 4.0.3 on 2023-09-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0109_alter_operatorpreferredgroundhandler_ground_handler_and_more'),
        ('organisation', '0110_merge_20230619_1142'),
    ]

    operations = [
    ]
