# Generated by Django 4.0.3 on 2023-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0111_alter_organisationcontactdetails_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcontactdetails',
            name='locations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, related_name='contact_details_for_location', through='organisation.OrganisationContactDetailsLocation', to='organisation.organisation', verbose_name='Applicable Location(s)'),
        ),
    ]
