# Generated by Django 4.0.3 on 2023-10-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0112_alter_organisationcontactdetails_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcontactdetails',
            name='address_bcc',
            field=models.BooleanField(default=False, verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='organisationcontactdetails',
            name='address_cc',
            field=models.BooleanField(default=False, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='organisationcontactdetails',
            name='address_to',
            field=models.BooleanField(default=False, verbose_name='TO'),
        ),
        migrations.AlterField(
            model_name='organisationcontactdetailslocation',
            name='organisations_contact_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationcontactdetails', verbose_name='Contact Details'),
        ),
    ]
