# Generated by Django 4.0.3 on 2023-10-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0111_merge_20230929_1355'),
        ('organisation', '0113_alter_organisationcontactdetails_address_bcc_and_more'),
    ]

    operations = [
    ]
