# Generated by Django 4.2.6 on 2023-11-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0113_alter_organisationcontactdetails_address_bcc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcontactdetails',
            name='email_address',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email Address'),
        ),
    ]
