# Generated by Django 4.2.6 on 2023-11-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0114_alter_organisationcontactdetails_email_address'),
        ('organisation', '0114_merge_20231023_1323'),
    ]

    operations = [
    ]
