# Generated by Django 4.2.6 on 2023-11-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisation",
            "0114_dlaservice_handlerspfservice_dlaservicemapping_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dlaservice",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="dlaservice",
            name="khi_product_code",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="KHI Product Code"
            ),
        ),
    ]
