# Generated by Django 4.2.6 on 2023-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0115_alter_dlaservice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlerspfservice",
            name="applies_after_minutes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Applies After Minutes"
            ),
        ),
    ]
