# Generated by Django 4.2.6 on 2023-11-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0115_alter_dlaservice_options_and_more'),
        ('organisation', '0115_merge_20231106_1501'),
    ]

    operations = [
    ]
