# Generated by Django 4.2.6 on 2023-11-15 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0114_alter_organisationcontactdetails_email_address"),
        ("organisation", "0116_alter_handlerspfservice_applies_after_minutes"),
    ]

    operations = []
