# Generated by Django 4.2.6 on 2023-11-09 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0116_alter_handlerspfservice_applies_after_minutes"),
        ("organisation", "0116_merge_20231107_1722"),
    ]

    operations = []
