# Generated by Django 4.2.6 on 2023-11-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0117_merge_20231115_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="dlaservice",
            name="spf_represented_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="represents",
                to="organisation.dlaservice",
                verbose_name="Represented in SPF As",
            ),
        ),
    ]
