# Generated by Django 4.2.6 on 2023-11-15 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0117_merge_20231109_1922"),
        ("organisation", "0118_dlaservice_spf_represented_by"),
    ]

    operations = []
