# Generated by Django 4.2.6 on 2023-11-15 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0118_dlaservice_spf_represented_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dlaservice",
            old_name="is_spf_visible",
            new_name="is_spf_included",
        ),
    ]
