# Generated by Django 4.2.6 on 2023-11-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0119_rename_is_spf_visible_dlaservice_is_spf_included"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dlaservice",
            name="is_spf_included",
            field=models.BooleanField(
                default=False, verbose_name="Is Included in SPF?"
            ),
        ),
    ]
