# Generated by Django 4.2.6 on 2023-11-15 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0119_merge_20231115_1640"),
        ("organisation", "0120_alter_dlaservice_is_spf_included"),
    ]

    operations = []
