# Generated by Django 4.2.6 on 2023-11-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0120_alter_dlaservice_is_spf_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="dlaservice",
            name="codename",
            field=models.SlugField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                verbose_name="Code Name",
            ),
        ),
        migrations.AddField(
            model_name="dlaservice",
            name="is_dla_visible_arrival",
            field=models.BooleanField(
                default=False, verbose_name="Visible for Arrival"
            ),
        ),
        migrations.AddField(
            model_name="dlaservice",
            name="is_dla_visible_departure",
            field=models.BooleanField(
                default=False, verbose_name="Visible for Departure"
            ),
        ),
    ]
