# Generated by Django 4.2.6 on 2023-11-17 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0121_dlaservice_codename_and_more"),
        ("organisation", "0121_merge_20231115_2013"),
    ]

    operations = []
