# Generated by Django 4.2.6 on 2023-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0121_dlaservice_codename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlacontractlocation',
            name='enforce_fuel_order',
            field=models.BooleanField(default=False, verbose_name='Enforce Fuel Order?'),
        ),
    ]
