# Generated by Django 4.2.6 on 2023-11-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0122_dlacontractlocation_enforce_fuel_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationdetails",
            name="supplier_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_organisations",
                to="organisation.organisation",
                verbose_name="Billing Supplier",
            ),
        ),
    ]
