# Generated by Django 4.2.6 on 2023-11-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0122_dlacontractlocation_enforce_fuel_order'),
        ('organisation', '0122_merge_20231117_1735'),
    ]

    operations = [
    ]
