# Generated by Django 4.2.6 on 2023-11-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_commentreadstatus'),
        ('user', '0033_usersettings'),
        ('organisation', '0122_dlacontractlocation_enforce_fuel_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationAMLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organisations_aml_teams',
            },
        ),
        migrations.AddField(
            model_name='organisationpeople',
            name='primary_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_people', to='core.region', verbose_name='Primary Region'),
        ),
        migrations.CreateModel(
            name='OrganisationPersonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_assignment', models.BooleanField(default=False)),
                ('aml_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_in_team', to='organisation.organisationamlteam', verbose_name='AML Team')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='user.person', verbose_name='Person')),
            ],
            options={
                'db_table': 'organisations_people_teams',
            },
        ),
    ]
