# Generated by Django 4.2.6 on 2023-11-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0123_merge_20231121_1659'),
        ('organisation', '0123_organisationdetails_supplier_organisation'),
    ]

    operations = [
    ]
