# Generated by Django 4.2.6 on 2023-11-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_usersettings'),
        ('organisation', '0123_organisationamlteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpersonteam',
            name='schedule_managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manages_schedule_for', to='user.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='organisationpersonteam',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='user.person', verbose_name='Person'),
        ),
    ]
