# Generated by Django 4.2.6 on 2023-12-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0112_merge_20231130_1803"),
        ("core", "0056_commentreadstatus"),
        ("organisation", "0123_organisationdetails_supplier_organisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandlerCancellationBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_band_start_hours",
                    models.PositiveSmallIntegerField(
                        verbose_name="Notification Band Start Hours"
                    ),
                ),
                (
                    "notification_band_end_hours",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Notification Band End Hours",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handler_cancellation_bands",
                        to="organisation.organisation",
                        verbose_name="Handler",
                    ),
                ),
            ],
            options={
                "db_table": "organisations_handler_cancellation_bands",
            },
        ),
        migrations.CreateModel(
            name="HandlerCancellationBandTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "penalty_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Penalty Percentage",
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "cancellation_band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_terms",
                        to="organisation.handlercancellationband",
                        verbose_name="Cancellation Band",
                    ),
                ),
                (
                    "penalty_amount_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="handler_cancellation_bands_terms",
                        to="core.currency",
                        verbose_name="Currency",
                    ),
                ),
                (
                    "penalty_specific_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handler_cancellation_bands_terms",
                        to="handling.handlingservice",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "db_table": "organisations_handler_cancellation_bands_terms",
            },
        ),
    ]
