# Generated by Django 4.2.6 on 2023-12-05 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0124_handlercancellationband_handlercancellationbandterm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlercancellationband",
            name="notification_band_end_hours",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Notice Period End"
            ),
        ),
        migrations.AlterField(
            model_name="handlercancellationband",
            name="notification_band_start_hours",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="Notice Period Start",
            ),
        ),
        migrations.AlterField(
            model_name="handlercancellationbandterm",
            name="penalty_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Penalty Amount",
            ),
        ),
    ]
