# Generated by Django 4.2.6 on 2023-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0125_alter_organisationpersonteam_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationpersonteam',
            name='schedule_managed_by',
        ),
        migrations.AddField(
            model_name='organisationpersonteam',
            name='manages_own_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisationpersonteam',
            name='manages_team_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisationpersonteam',
            name='visible_on_calendar',
            field=models.BooleanField(default=True),
        ),
    ]
