# Generated by Django 4.2.6 on 2023-12-08 20:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0033_usersettings"),
        (
            "organisation",
            "0125_alter_handlercancellationband_notification_band_end_hours_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationdetails",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AddField(
            model_name="organisationdetails",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_organisation_details",
                to="user.person",
                verbose_name="Updated By",
            ),
        ),
        migrations.AlterField(
            model_name="handlercancellationband",
            name="notification_band_end_hours",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Notice Period End (Hours)"
            ),
        ),
        migrations.AlterField(
            model_name="handlercancellationband",
            name="notification_band_start_hours",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="Notice Period Start (Hours)",
            ),
        ),
    ]
