# Generated by Django 4.2.6 on 2023-11-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0126_remove_organisationpersonteam_schedule_managed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationpersonteam',
            name='manages_team_schedule',
        ),
        migrations.RemoveField(
            model_name='organisationpersonteam',
            name='visible_on_calendar',
        ),
    ]
