# Generated by Django 4.2.7 on 2023-12-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_teamrole'),
        ('organisation', '0127_remove_organisationpersonteam_manages_team_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpersonteam',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.teamrole', verbose_name='Role'),
        ),
    ]
