# Generated by Django 4.2.6 on 2023-12-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0127_emailfunction_organisationemailcontroladdress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailfunction",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Name"),
        ),
    ]
