# Generated by Django 4.2.7 on 2023-12-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0124_merge_20231122_1543'),
        ('organisation', '0127_remove_organisationpersonteam_manages_team_schedule_and_more'),
    ]

    operations = [
    ]
