# Generated by Django 4.2.6 on 2023-12-05 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisation",
            "0125_alter_handlercancellationband_notification_band_end_hours_and_more",
        ),
        ("organisation", "0128_merge_20231201_1152"),
    ]

    operations = []
