# Generated by Django 4.2.6 on 2023-12-08 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0126_organisationdetails_updated_at_and_more"),
        ("organisation", "0129_merge_20231205_1913"),
    ]

    operations = []
