# Generated by Django 4.2.6 on 2023-12-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0128_organisationpersonteam_role'),
        ('organisation', '0130_merge_20231208_2117'),
    ]

    operations = [
    ]
