# Generated by Django 4.2.6 on 2023-12-16 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0127_emailfunction_organisationemailcontroladdress_and_more"),
        ("organisation", "0131_merge_20231211_0918"),
    ]

    operations = []
