# Generated by Django 4.2.6 on 2023-12-19 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0128_alter_emailfunction_name"),
        ("organisation", "0132_merge_20231216_1846"),
    ]

    operations = []
