# Generated by Django 4.0.3 on 2022-07-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxrule',
            old_name='airport',
            new_name='specific_airport',
        ),
        migrations.RenameField(
            model_name='taxrule',
            old_name='country',
            new_name='specific_country',
        ),
        migrations.RenameField(
            model_name='taxruleexception',
            old_name='airport',
            new_name='exception_airport',
        ),
        migrations.RenameField(
            model_name='taxruleexception',
            old_name='country',
            new_name='exception_country',
        ),
        migrations.RenameField(
            model_name='taxruleexception',
            old_name='organisation',
            new_name='exception_organisation',
        ),
    ]
