# Generated by Django 4.0.3 on 2022-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_taxcategory_rename_name_tax_local_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code')),
            ],
            options={
                'db_table': 'taxes_rates',
            },
        ),
    ]
