# Generated by Django 4.0.3 on 2022-08-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_taxrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxFixedCostApplicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_override', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('charge_structures_properties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.chargestructureproperties', verbose_name='Charge Structures Properties')),
            ],
            options={
                'db_table': 'taxes_fixed_cost_application_methods',
            },
        ),
    ]
