# Generated by Django 4.0.3 on 2022-08-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_taxfixedcostapplicationmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxapplicationmethod',
            name='charge_structures_properties',
        ),
        migrations.AddField(
            model_name='taxapplicationmethod',
            name='fixed_cost_application_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.taxfixedcostapplicationmethod', verbose_name='Fixed Cost Application Method'),
        ),
    ]
