# Generated by Django 4.0.3 on 2022-08-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_remove_taxapplicationmethod_charge_structures_properties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrule',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='taxrule',
            name='specific_country',
        ),
        migrations.RemoveField(
            model_name='taxrule',
            name='tax_unit_price',
        ),
        migrations.RemoveField(
            model_name='taxruleexception',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='taxruleexception',
            name='tax_unit_price',
        ),
        migrations.AddField(
            model_name='taxrule',
            name='tax_rate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pricing.taxrate', verbose_name='Tax Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxrule',
            name='tax_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='pricing.taxsource', verbose_name='Tax Source'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='tax_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tax Unit Rate'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='tax_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules_exceptions', to='pricing.taxsource', verbose_name='Tax Source'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='tax_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tax Unit Rate'),
        ),
    ]
