# Generated by Django 4.0.3 on 2022-10-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_remove_taxrule_source_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('pricing_unit', models.ForeignKey(db_column='pricing_unit', on_delete=django.db.models.deletion.CASCADE, to='core.pricingunit', verbose_name='Pricing Unit')),
            ],
            options={
                'db_table': 'fuel_indices',
            },
        ),
        migrations.CreateModel(
            name='FuelIndexPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Price')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('valid_ufn', models.BooleanField(default=False, verbose_name='Valid UFN?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('fuel_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.fuelindex', verbose_name='Fuel Index')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'fuel_indices_pricing',
            },
        ),
    ]
