# Generated by Django 4.0.3 on 2022-11-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_unitofmeasurementconversionmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelindex',
            name='period_is_daily',
            field=models.BooleanField(default=False, verbose_name='Is Daily?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='period_is_weekly',
            field=models.BooleanField(default=False, verbose_name='Is Weekly?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='period_is_monthly',
            field=models.BooleanField(default=False, verbose_name='Is Monthly?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='period_is_lagged',
            field=models.BooleanField(default=False, verbose_name='Is Lagged?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='price_is_average',
            field=models.BooleanField(default=False, verbose_name='Is Average?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='price_is_low',
            field=models.BooleanField(default=False, verbose_name='Is Low?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='price_is_high',
            field=models.BooleanField(default=False, verbose_name='Is High?'),
        ),
    ]
