# Generated by Django 4.0.3 on 2022-11-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_fuelindex_period_is_daily_fuelindex_period_is_lagged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelindex',
            name='period_is_daily',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='period_is_lagged',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='period_is_monthly',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='period_is_weekly',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='price_is_average',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='price_is_high',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='price_is_low',
        ),
    ]
