# Generated by Django 4.0.3 on 2022-11-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fueltype_nato_code'),
        ('user', '0024_user_last_token_sent_at'),
        ('pricing', '0011_remove_fuelindex_period_is_daily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelindex',
            name='pricing_unit',
            field=models.ForeignKey(db_column='pricing_unit', on_delete=django.db.models.deletion.RESTRICT, to='core.pricingunit', verbose_name='Pricing Unit'),
        ),
        migrations.AlterField(
            model_name='fuelindexpricing',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='unitofmeasurementconversionmethod',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By'),
        ),
    ]
