# Generated by Django 4.0.3 on 2022-11-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fueltype_nato_code'),
        ('organisation', '0098_ipalocation_location_email_and_more'),
        ('aircraft', '0016_aircraftweightunit'),
        ('user', '0024_user_last_token_sent_at'),
        ('pricing', '0012_alter_fuelindex_pricing_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('applies_ooh', models.BooleanField(default=False, verbose_name='Applies OOH?')),
            ],
            options={
                'db_table': 'fees_fuel_categories',
            },
        ),
        migrations.CreateModel(
            name='SupplierFuelFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local Name')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_fees_where_is_supplier', to='organisation.organisation', verbose_name='Supplier')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_fees_where_is_location', to='organisation.organisation', verbose_name='Location')),
                ('ipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_fees_where_is_ipa', to='organisation.organisation', verbose_name='IPA')),
                ('fuel_fee_category', models.ForeignKey(db_column='fuel_fee_category', on_delete=django.db.models.deletion.RESTRICT, related_name='fees_in_category', to='pricing.fuelfeecategory', verbose_name='Fuel Fee Category')),
                ('pricing_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fees_using_unit', to='core.pricingunit', verbose_name='Pricing Unit')),
            ],
            options={
                'db_table': 'suppliers_fuel_fees',
            },
        ),
        migrations.CreateModel(
            name='SupplierFuelFeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_fuel_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pricing.supplierfuelfee', verbose_name='Supplier Fuel Fee')),
                ('delivery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method')),
                ('specific_fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fueltype', verbose_name='Specific Fuel')),
                ('flight_type', models.ForeignKey(db_column='flight_type', on_delete=django.db.models.deletion.RESTRICT, to='core.flighttype', verbose_name='Flight Type')),
                ('destination_type', models.ForeignKey(db_column='destination_type', on_delete=django.db.models.deletion.RESTRICT, to='core.geographichflighttype', verbose_name='Destination Type')),
                ('quantity_band_uom', models.ForeignKey(db_column='quantity_band_uom', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Quantity Band Unit')),
                ('quantity_band_start', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Quantity Band Start')),
                ('quantity_band_end', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Quantity Band End')),
                ('weight_band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='aircraft.aircraftweightunit', verbose_name='Weight Band Unit')),
                ('weight_band_start', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Weight Band Start')),
                ('weight_band_end', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Weight Band End')),
                ('source_document_url', models.ForeignKey(db_column='source_document_url', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisationdocument', verbose_name='Source Document')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'suppliers_fuel_fees_rates',
            },
        ),
        migrations.CreateModel(
            name='SupplierFuelFeeInclusiveTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_fuel_fee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.supplierfuelfeerate', verbose_name='Supplier Fuel Fee Rate')),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.taxcategory', verbose_name='Tax Category')),
            ],
            options={
                'db_table': 'suppliers_fees_fuel_inclusive_taxes',
            },
        ),
    ]
