# Generated by Django 4.0.3 on 2022-11-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0098_ipalocation_location_email_and_more'),
        ('core', '0028_fueltype_nato_code'),
        ('user', '0024_user_last_token_sent_at'),
        ('pricing', '0013_fuelfeecategory_supplierfuelfee_supplierfuelfeerate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAdditivePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_additive_prices', to='organisation.organisation', verbose_name='Supplier')),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.fueladditive', verbose_name='Additive')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Unit Price')),
                ('pricing_unit', models.ForeignKey(db_column='pricing_unit', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.pricingunit', verbose_name='Pricing Unit')),
                ('price_on_request', models.BooleanField(default=False, verbose_name='Price on Request?')),
                ('moq_amount', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='MOQ Amount')),
                ('moq_uom', models.ForeignKey(db_column='moq_uom', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='MOQ Unit')),
                ('manufactured_on_demand', models.BooleanField(default=False, verbose_name='Manufactured on Demand?')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('valid_ufn', models.BooleanField(default=False, verbose_name='Valid UFN?')),
                ('physical_location', models.ForeignKey(db_column='physical_location', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.country', verbose_name='Physical Location')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'suppliers_additives_pricing',
            },
        ),
    ]
