# Generated by Django 4.0.3 on 2022-11-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_supplieradditivepricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitOfMeasurementConversionMethod',
        ),
    ]
