# Generated by Django 4.0.3 on 2022-11-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0098_ipalocation_location_email_and_more'),
        ('supplier', '0002_rename_supplierfuelagreement_fuelagreement'),
        ('user', '0024_user_last_token_sent_at'),
        ('core', '0030_rename_specific_fuel_id_unitofmeasurementconversionmethod_specific_fuel'),
        ('pricing', '0015_supplierfuelfeerate_source_agreement'),
        ('pricing', '0016_delete_unitofmeasurementconversionmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelAgreementPricingManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_manual', to='supplier.fuelagreement', verbose_name='Agreement')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_location_manual', to='organisation.organisation', verbose_name='Location')),
                ('ipa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_ipa_manual', to='organisation.organisation', verbose_name='IPA')),
                ('delivery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_fuel_manual', to='core.fueltype', verbose_name='Fuel')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_client_manual', to='organisation.organisation', verbose_name='Client')),
                ('price_active', models.BooleanField(default=True, verbose_name='Price Is Active?')),
                ('pricing_discount_unit', models.ForeignKey(db_column='pricing_discount_unit', on_delete=django.db.models.deletion.RESTRICT, to='core.pricingunit', verbose_name='Pricing Discount Unit')),
                ('pricing_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Pricing Discount Percentage')),
                ('pricing_discount_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pricing Discount Amount')),
                ('flight_type', models.ForeignKey(db_column='flight_type', on_delete=django.db.models.deletion.RESTRICT, to='core.flighttype', verbose_name='Flight Type')),
                ('destination_type', models.ForeignKey(db_column='destination_type', on_delete=django.db.models.deletion.RESTRICT, to='core.geographichflighttype', verbose_name='Destination Type')),
                ('band_uom', models.ForeignKey(db_column='band_uom', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Band Unit')),
                ('band_start', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Band Start')),
                ('band_end', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Band End')),
                ('source_document_url', models.ForeignKey(db_column='source_document_url', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisationdocument', verbose_name='Source Document')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'suppliers_fuel_agreements_pricing_manual',
            },
        ),
        migrations.CreateModel(
            name='FuelAgreementPricingFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_formulae', to='supplier.fuelagreement', verbose_name='Agreement')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_location_formulae', to='organisation.organisation', verbose_name='Location')),
                ('ipa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_ipa_formulae', to='organisation.organisation', verbose_name='IPA')),
                ('delivery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_fuel_formulae', to='core.fueltype', verbose_name='Fuel')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_client_formulae', to='organisation.organisation', verbose_name='Client')),
                ('price_active', models.BooleanField(default=True, verbose_name='Price Is Active?')),
                ('pricing_index', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.fuelindex', verbose_name='Pricing Index')),
                ('index_period_is_daily', models.BooleanField(default=False, verbose_name='Period Is Daily?')),
                ('index_period_is_weekly', models.BooleanField(default=False, verbose_name='Period Is Weekly?')),
                ('index_period_is_monthly', models.BooleanField(default=False, verbose_name='Period Is Monthly?')),
                ('index_period_is_lagged', models.BooleanField(default=False, verbose_name='Period Is Lagged?')),
                ('index_period_is_grace', models.BooleanField(default=False, verbose_name='Period Is Grace?')),
                ('index_price_is_mean', models.BooleanField(default=False, verbose_name='Price Is Mean?')),
                ('index_price_is_low', models.BooleanField(default=False, verbose_name='Price Is Low?')),
                ('index_price_is_high', models.BooleanField(default=False, verbose_name='Price Is High?')),
                ('differential_value', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Differential Value')),
                ('differential_pricing_unit', models.ForeignKey(db_column='differential_pricing_unit', on_delete=django.db.models.deletion.RESTRICT, to='core.pricingunit', verbose_name='Differential Pricing Unit')),
                ('volume_conversion_method', models.ForeignKey(db_column='volume_conversion_method', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurementconversionmethod', verbose_name='Volume Conversion Method')),
                ('volume_conversion_ratio_override', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='Volume Conversion Ration Override')),
                ('flight_type', models.ForeignKey(db_column='flight_type', on_delete=django.db.models.deletion.RESTRICT, to='core.flighttype', verbose_name='Flight Type')),
                ('destination_type', models.ForeignKey(db_column='destination_type', on_delete=django.db.models.deletion.RESTRICT, to='core.geographichflighttype', verbose_name='Destination Type')),
                ('band_uom', models.ForeignKey(db_column='band_uom', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Band Unit')),
                ('band_start', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Band Start')),
                ('band_end', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Band End')),
                ('source_document_url', models.ForeignKey(db_column='source_document_url', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisationdocument', verbose_name='Source Document')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'suppliers_fuel_agreements_pricing_formulae',
            },
        ),
    ]
