# Generated by Django 4.0.3 on 2022-11-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pricingunit_description'),
        ('organisation', '0100_airportdetails_updated_at_and_more'),
        ('pricing', '0018_fuelindex_active_fuelindex_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxsource',
            name='tax',
        ),
        migrations.AddField(
            model_name='tax',
            name='verified_by_ads',
            field=models.BooleanField(default=False, verbose_name='Verified by ADS?'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='pax_must_stay_aboard',
            field=models.BooleanField(default=False, verbose_name='Pax Must Stay Aboard'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='taxable_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.taxrule', verbose_name='Taxable Tax'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='waived_for_tech_stop',
            field=models.BooleanField(default=False, verbose_name='Waived For Tech Stop'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='exception_only_for_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_specific_tax_exceptions', to='organisation.organisation', verbose_name='Exception only for Organisations'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='pax_must_stay_aboard',
            field=models.BooleanField(default=False, verbose_name='Pax Must Stay Aboard'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='taxable_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.taxruleexception', verbose_name='Taxable Exception'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='taxable_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.taxrule', verbose_name='Taxable Tax'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='waived_for_tech_stop',
            field=models.BooleanField(default=False, verbose_name='Waived For Tech Stop'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='tax_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Tax Unit Rate'),
        ),
        migrations.AlterField(
            model_name='taxruleexception',
            name='exception_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='taxruleexception',
            name='tax_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Tax Unit Rate'),
        ),
        migrations.AlterField(
            model_name='taxsource',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
    ]
