# Generated by Django 4.0.3 on 2022-11-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_remove_taxsource_tax_tax_verified_by_ads_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chargestructurecode',
            table='charge_structure_qualifiers_old',
        ),
        migrations.AlterModelTable(
            name='chargestructurequalifier',
            table='charge_structure_codes_old',
        ),
    ]
