# Generated by Django 4.0.3 on 2022-11-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pricingunit_description'),
        ('pricing', '0021_alter_chargestructurecode_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='price_active',
            field=models.BooleanField(default=True, verbose_name='Price Active'),
        ),
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='pricing_converted_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Pricing Converted Amount'),
        ),
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='pricing_converted_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_fuel_fee_rate_pricing_converted', to='core.pricingunit', verbose_name='Pricing Converted Unit'),
        ),
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='pricing_native_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Pricing Native Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='pricing_native_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_fuel_fee_rate_pricing_native', to='core.pricingunit', verbose_name='Pricing Native Unit'),
        ),
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='supplier_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Supplier Exchange Rate'),
        ),
    ]
