# Generated by Django 4.0.3 on 2022-11-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0022_supplierfuelfeerate_price_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrule',
            name='tax_percentage',
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.tax', verbose_name='Tax'),
        ),
        migrations.CreateModel(
            name='TaxRatePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax Percentage')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pricing.tax', verbose_name='Tax')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.taxrate', verbose_name='Rate')),
            ],
            options={
                'db_table': 'taxes_rates_percentages',
            },
        ),
        migrations.AddField(
            model_name='taxrule',
            name='tax_rate_percentage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.taxratepercentage', verbose_name='Tax Rate Percentage'),
        ),
    ]
