# Generated by Django 4.0.3 on 2023-01-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pricingunit_description_short'),
        ('pricing', '0025_tax_applicable_region_alter_tax_applicable_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='pricing_native_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_fuel_fee_rate_pricing_native', to='core.pricingunit', verbose_name='Pricing Native Unit'),
        ),
    ]
