# Generated by Django 4.0.3 on 2023-01-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_last_token_sent_at'),
        ('organisation', '0103_organisationopsdetails'),
        ('core', '0033_pricingunit_description_short'),
        ('pricing', '0026_alter_supplierfuelfeerate_pricing_native_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPricingMarketPld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market_plds_where_is_supplier', to='organisation.organisation', verbose_name='Supplier')),
                ('pld_name', models.CharField(max_length=255, verbose_name='PLD Name')),
                ('is_current', models.BooleanField(default=True, verbose_name='Is Current?')),
                ('source_document_url', models.ForeignKey(db_column='source_document_url', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisationdocument', verbose_name='Source Document')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market_pld',
            },
        ),
        migrations.CreateModel(
            name='FuelPricingMarketPldLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='pricing.fuelpricingmarketpld', verbose_name='PLD')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_pricing_market_plds_at_location', to='organisation.organisation', verbose_name='Location')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market_pld_locations',
            },
        ),
        migrations.CreateModel(
            name='FuelPricingMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_pld_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market', to='pricing.fuelpricingmarketpldlocation', verbose_name='PLD Location')),
                ('ipa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_pricing_markets_where_is_ipa', to='organisation.organisation', verbose_name='IPA')),
                ('delivery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_pricing_for_fuel', to='core.fueltype', verbose_name='Fuel')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_pricing_markets_where_is_client', to='organisation.organisation', verbose_name='Client')),
                ('price_active', models.BooleanField(default=True, verbose_name='Price Is Active?')),
                ('pricing_native_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_pricing_market_where_native', to='core.pricingunit', verbose_name='Pricing Native Unit')),
                ('pricing_native_amount', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Pricing Native Amount')),
                ('supplier_exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Supplier Exchange Rate')),
                ('pricing_converted_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_pricing_market_where_converted', to='core.pricingunit', verbose_name='Pricing Converted Unit')),
                ('pricing_converted_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Pricing Converted Amount')),
                ('flight_type', models.ForeignKey(db_column='flight_type', on_delete=django.db.models.deletion.RESTRICT, to='core.flighttype', verbose_name='Flight Type')),
                ('destination_type', models.ForeignKey(db_column='destination_type', on_delete=django.db.models.deletion.RESTRICT, to='core.geographichflighttype', verbose_name='Destination Type')),
                ('band_uom', models.ForeignKey(db_column='band_uom', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Band Unit')),
                ('band_start', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Band Start')),
                ('band_end', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Band End')),
                ('valid_from_date', models.DateField(verbose_name='Valid From')),
                ('valid_to_date', models.DateField(verbose_name='Valid To')),
                ('is_latest', models.BooleanField(default=True, verbose_name='Is Latest?')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Is Reviewed?')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published?')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market',
            },
        ),
        migrations.CreateModel(
            name='FuelPricingMarketReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_fuel_pricing_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pricing.fuelpricingmarket', verbose_name='Fuel Pricing Market')),
                ('assigned_at', models.DateTimeField(verbose_name='Assigned At')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_fuel_pricing_market_reviews', to='user.person', verbose_name='Assigned To')),
                ('reviewed_at', models.DateTimeField(null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviewed_fuel_pricing_market_reviews', to='user.person', verbose_name='Reviewed By')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market_reviews',
            },
        ),
        migrations.AddField(
            model_name='fuelpricingmarket',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pricing.fuelpricingmarketreview', verbose_name='Review')
        ),
    ]
