# Generated by Django 4.0.3 on 2023-01-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0103_organisationopsdetails'),
        ('user', '0024_user_last_token_sent_at'),
        ('pricing', '0027_fuelpricingmarket_fuelpricingmarketpld_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelindex',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='fuelindexpricing',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='fuelindexpricing',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published?'),
        ),
        migrations.AddField(
            model_name='fuelindexpricing',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Is Reviewed?'),
        ),
        migrations.AddField(
            model_name='fuelindexpricing',
            name='source_document',
            field=models.ForeignKey(db_column='source_document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisationdocument', verbose_name='Source Document'),
        ),
        migrations.CreateModel(
            name='FuelIndexPricingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_indices_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pricing.fuelindexpricing', verbose_name='Fuel Index Pricing')),
                ('assigned_at', models.DateTimeField(verbose_name='Assigned At')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_fuel_index_pricing_reviews', to='user.person', verbose_name='Assigned To')),
                ('reviewed_at', models.DateTimeField(null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviewed_fuel_index_pricing_reviews', to='user.person', verbose_name='Reviewed By')),
            ],
            options={
                'db_table': 'fuel_indices_pricing_reviews',
            },
        ),
        migrations.AddField(
            model_name='fuelindexpricing',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pricing.fuelindexpricingreview', verbose_name='Review'),
        ),
    ]
