# Generated by Django 4.0.3 on 2023-02-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0028_rename_active_fuelindex_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelindexpricing',
            name='fuel_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.fuelindex', verbose_name='Fuel Index'),
        ),
    ]
