# Generated by Django 4.0.3 on 2023-02-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_last_token_sent_at'),
        ('pricing', '0029_alter_fuelindexpricing_fuel_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCalculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.JSONField(verbose_name='Pricing Scenario')),
                ('results', models.JSONField(verbose_name='Pricing Results')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pricing_calculation_record', to='user.person', verbose_name='Created By')),
            ],
            options={
                'db_table': 'fuel_pricing_calculations_history',
            },
        ),
    ]
