# Generated by Django 4.0.3 on 2023-03-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0103_organisationopsdetails'),
        ('pricing', '0030_alter_fuelpricingmarketpld_source_document_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelpricingmarketpldlocation',
            name='location',
        ),
        migrations.AddField(
            model_name='fuelpricingmarketpldlocation',
            name='location',
            field=models.ForeignKey(default=800000, limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_pricing_market_plds_at_location', to='organisation.organisation', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
