# Generated by Django 4.0.3 on 2023-03-06 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0103_organisationopsdetails'),
        ('pricing', '0031_remove_fuelpricingmarketpldlocation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpricingmarketpld',
            name='locations',
            field=models.ManyToManyField(blank=True, through='pricing.FuelPricingMarketPldLocation', to='organisation.organisation', verbose_name='Locations(s)'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarketpldlocation',
            name='pld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pld_at_location', to='pricing.fuelpricingmarketpld', verbose_name='PLD'),
        ),
    ]
