# Generated by Django 4.0.3 on 2023-03-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0103_organisationopsdetails'),
        ('core', '0034_alter_pricingunit_options'),
        ('pricing', '0032_fuelpricingmarketpld_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='band_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Band End'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='band_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Band Start'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='band_uom',
            field=models.ForeignKey(blank=True, db_column='band_uom', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Band Unit'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='ipa',
            field=models.ForeignKey(limit_choices_to={'details__type_id': 4}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_pricing_markets_where_is_ipa', to='organisation.organisation', verbose_name='IPA'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='supplier_pld_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market', to='pricing.fuelpricingmarketpldlocation', verbose_name='PLD Location'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarketpld',
            name='locations',
            field=models.ManyToManyField(through='pricing.FuelPricingMarketPldLocation', to='organisation.organisation', verbose_name='Locations(s)'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarketpld',
            name='source_document_url',
            field=models.ForeignKey(blank=True, db_column='source_document_url', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pld_source_document', to='organisation.organisationdocument', verbose_name='Source Document'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarketpld',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'details__type_id': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market_plds_where_is_supplier', to='organisation.organisation', verbose_name='Supplier'),
        ),
    ]
