# Generated by Django 4.0.3 on 2023-05-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0032_add_applies_to_commercial_applies_to_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='applies_to_commercial',
            field=models.BooleanField(default=True, verbose_name='Applies To Commercial'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='applies_to_commercial',
            field=models.BooleanField(default=True, verbose_name='Applies To Commercial'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='applies_to_commercial',
            field=models.BooleanField(default=True, verbose_name='Applies To Commercial'),
        ),
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='applies_to_commercial',
            field=models.BooleanField(default=True, verbose_name='Applies To Commercial'),
        ),
    ]
