# Generated by Django 4.0.3 on 2023-06-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0033_alter_fuelagreementpricingformula_applies_to_commercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelagreementpricingformula',
            name='parent_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entries', to='pricing.fuelagreementpricingformula'),
        ),
        migrations.AddField(
            model_name='fuelagreementpricingmanual',
            name='parent_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entries', to='pricing.fuelagreementpricingmanual'),
        ),
    ]
