# Generated by Django 4.0.3 on 2023-03-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0033_alter_fuelpricingmarket_band_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='supplier_pld_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market', to='pricing.fuelpricingmarketpldlocation', verbose_name='PLD Location'),
        ),
    ]
