# Generated by Django 4.0.3 on 2023-03-08 16:22

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0034_alter_fuelpricingmarket_supplier_pld_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelpricingmarketpld',
            name='source_document_url',
        ),
        migrations.CreateModel(
            name='FuelPricingMarketPldDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('file', models.FileField(storage=app.storage_backends.FuelPricingMarketPldDocumentFilesStorage(), upload_to='', verbose_name='Document File')),
                ('pld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pld_document', to='pricing.fuelpricingmarketpld', verbose_name='PLD')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market_pld_documents',
            },
        ),
    ]
