# Generated by Django 4.0.3 on 2023-03-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0030_pricingcalculationrecord'),
        ('pricing', '0035_remove_fuelpricingmarketpld_source_document_url_and_more'),
    ]

    operations = [
    ]
