# Generated by Django 4.0.3 on 2023-03-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0104_operatordetails_crew_weight_and_more'),
        ('pricing', '0036_merge_20230311_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelpricingmarketplddocument',
            options={'permissions': [('can_supersede_pld', "Can supersede the Price List Document to change the 'current' status"), ('can_alter_pricing_publication_status', 'Can alter PLD attached pricing publication status')]},
        ),
        migrations.AlterField(
            model_name='fuelpricingmarketpld',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'details__type_id__in': [2, 3, 5, 8, 13, 14]}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market_plds_where_is_supplier', to='organisation.organisation', verbose_name='Supplier'),
        ),
    ]
