# Generated by Django 4.0.3 on 2023-03-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0031_taxrule_applies_to_fees_and_more'),
        ('pricing', '0037_alter_fuelpricingmarketplddocument_options_and_more'),
    ]

    operations = [
    ]
