# Generated by Django 4.0.3 on 2023-04-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20230309_0005'),
        ('pricing', '0038_alter_supplierfuelfeeinclusivetaxes_supplier_fuel_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='applicable_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='core.country', verbose_name='Applicable Country'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='geographic_flight_type',
            field=models.ForeignKey(db_column='geographic_flight_type_code', on_delete=django.db.models.deletion.CASCADE, to='core.geographichflighttype', verbose_name='Geographic Flight Type'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rule_set', to='pricing.tax', verbose_name='Tax'),
        ),
    ]
