# Generated by Django 4.0.3 on 2023-04-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0038_alter_supplierfuelfeeinclusivetaxes_supplier_fuel_fee'),
        ('pricing', '0038_merge_20230314_1608'),
    ]

    operations = [
    ]
