# Generated by Django 4.0.3 on 2023-04-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0039_alter_tax_applicable_country_and_more'),
        ('pricing', '0039_merge_20230407_1429'),
    ]

    operations = [
    ]
