# Generated by Django 4.0.3 on 2023-04-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0039_alter_tax_applicable_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpricingmarket',
            name='parent_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entries', to='pricing.fuelpricingmarket'),
        ),
    ]
