# Generated by Django 4.0.3 on 2023-05-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0040_fuelpricingmarket_parent_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='parent_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entries', to='pricing.taxrule'),
        ),
    ]
