# Generated by Django 4.0.3 on 2023-05-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0040_fuelpricingmarket_parent_entry'),
        ('pricing', '0040_merge_20230417_2150'),
    ]

    operations = [
    ]
