# Generated by Django 4.0.3 on 2023-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0041_taxrule_parent_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='valid_from_date',
            field=models.DateField(default='2023-05-01', verbose_name='Valid From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='valid_to_date',
            field=models.DateField(null=True, verbose_name='Valid To'),
        ),
    ]
