# Generated by Django 4.0.3 on 2023-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0041_merge_20230505_1538'),
        ('pricing', '0042_supplierfuelfeerate_valid_from_date_and_more'),
    ]

    operations = [
    ]
