# Generated by Django 4.0.3 on 2023-05-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0032_add_applies_to_commercial_applies_to_private'),
        ('pricing', '0042_supplierfuelfeerate_valid_from_date_and_more'),
    ]

    operations = [
    ]
