# Generated by Django 4.0.3 on 2023-06-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0044_alter_fuelpricingmarketpld_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxruleexception',
            name='parent_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entries', to='pricing.taxruleexception'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='tax_application_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_to_rules', to='pricing.taxapplicationmethod', verbose_name='Tax Application Method'),
        ),
    ]
