# Generated by Django 4.0.3 on 2023-06-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0034_add_parent_entry_to_agreement_pricing'),
        ('pricing', '0044_alter_fuelpricingmarketpld_options_and_more'),
    ]

    operations = [
    ]
