# Generated by Django 4.0.3 on 2023-05-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0044_alter_fuelpricingmarketpld_options_and_more'),
        ('pricing', '0044_merge_20230523_1310'),
    ]

    operations = [
    ]
