# Generated by Django 4.0.3 on 2023-05-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0033_alter_fuelagreementpricingformula_applies_to_commercial_and_more'),
        ('pricing', '0045_merge_20230530_1415'),
    ]

    operations = [
    ]
