# Generated by Django 4.0.3 on 2023-06-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_alter_fuelagreement_document'),
        ('pricing', '0045_merge_20230608_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='source_agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='associated_fees', to='supplier.fuelagreement', verbose_name='Source Agreement'),
        ),
    ]
