# Generated by Django 4.0.3 on 2023-06-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0034_add_parent_entry_to_agreement_pricing'),
        ('pricing', '0046_merge_20230531_1557'),
    ]

    operations = [
    ]
