# Generated by Django 4.0.3 on 2023-06-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20230608_1617'),
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0046_alter_supplierfuelfeerate_source_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='band_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Band End'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='band_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Band Start'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='band_uom',
            field=models.ForeignKey(blank=True, db_column='band_uom', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Band Unit'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='location',
            field=models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_location_formulae', to='organisation.organisation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='volume_conversion_method',
            field=models.ForeignKey(blank=True, db_column='volume_conversion_method', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurementconversionmethod', verbose_name='Volume Conversion Method'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='volume_conversion_ratio_override',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Volume Conversion Ratio Override'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='band_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Band End'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='band_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Band Start'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='band_uom',
            field=models.ForeignKey(blank=True, db_column='band_uom', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Band Unit'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='location',
            field=models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_location_manual', to='organisation.organisation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='tax_application_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_to_rules', to='pricing.taxapplicationmethod', verbose_name='Tax Application Method'),
        ),
    ]
