# Generated by Django 4.0.3 on 2023-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0046_taxruleexception_related_pld'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted At'),
        ),
    ]
