# Generated by Django 4.0.3 on 2023-06-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0047_alter_fuelagreementpricingformula_band_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelindex',
            options={'ordering': ['name']},
        ),
    ]
