# Generated by Django 4.0.3 on 2023-06-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0045_merge_20230608_1617'),
        ('pricing', '0047_merge_20230608_1348'),
    ]

    operations = [
    ]
