# Generated by Django 4.0.3 on 2023-06-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0048_alter_fuelindex_options'),
        ('pricing', '0048_merge_20230619_1142'),
    ]

    operations = [
    ]
