# Generated by Django 4.0.3 on 2023-07-06 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0048_alter_taxruleexception_taxable_exception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpricingmarket',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='supplierfuelfee',
            name='related_pld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.fuelpricingmarketpld'),
        ),
    ]
