# Generated by Django 4.0.3 on 2023-07-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20230630_0925'),
        ('pricing', '0048_alter_fuelindex_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='pricing_discount_unit',
            field=models.ForeignKey(blank=True, db_column='pricing_discount_unit', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.pricingunit', verbose_name='Pricing Discount Unit'),
        ),
    ]
