# Generated by Django 4.0.3 on 2023-07-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0049_alter_fuelagreementpricingmanual_pricing_discount_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelagreementpricingformula',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='fuelagreementpricingmanual',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
    ]
