# Generated by Django 4.0.3 on 2023-07-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0049_fuelpricingmarket_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted At'),
        ),
    ]
