# Generated by Django 4.0.3 on 2023-07-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0049_alter_fuelagreementpricingmanual_pricing_discount_unit'),
        ('pricing', '0049_merge_20230629_1706'),
    ]

    operations = [
    ]
