# Generated by Django 4.0.3 on 2023-07-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20230505_1344'),
        ('pricing', '0050_supplierfuelfeerate_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpricingmarket',
            name='is_pap',
            field=models.BooleanField(default=False, verbose_name='Posted Airport Pricing?'),
        ),
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='taxruleexception',
            name='exception_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.country', verbose_name='Country'),
        ),
    ]
