# Generated by Django 4.0.3 on 2023-07-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0048_alter_taxruleexception_taxable_exception_and_more'),
        ('pricing', '0050_merge_20230704_1655'),
    ]

    operations = [
    ]
