# Generated by Django 4.0.3 on 2023-07-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0048_alter_taxruleexception_taxable_exception_and_more'),
        ('pricing', '0050_fuelagreementpricingformula_deleted_at_and_more'),
    ]

    operations = [
    ]
