# Generated by Django 4.0.3 on 2023-07-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0051_merge_20230705_1352'),
        ('pricing', '0051_merge_20230705_1742'),
    ]

    operations = [
    ]
