# Generated by Django 4.0.3 on 2023-07-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20230505_1344'),
        ('pricing', '0051_fuelpricingmarket_is_pap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='specific_fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fueltype', verbose_name='Specific Fuel'),
        ),
    ]
