# Generated by Django 4.0.3 on 2023-07-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0050_supplierfuelfeerate_deleted_at'),
        ('pricing', '0052_merge_20230705_1801'),
    ]

    operations = [
    ]
