# Generated by Django 4.0.3 on 2023-07-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0053_taxruleexception_source_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelAgreementPricingFormulaIncludingTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.ForeignKey(db_column='pricing_formulae_id', on_delete=django.db.models.deletion.RESTRICT, related_name='included_taxes', to='pricing.fuelagreementpricingformula', verbose_name='Fuel Agreement Pricing Formula')),
                ('tax_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pricing.taxcategory', verbose_name='Tax Category')),
                ('applies_to_fees', models.BooleanField(default=False, verbose_name='Cascade to Fees?')),
            ],
            options={
                'db_table': 'suppliers_fuel_agreements_pricing_formulae_inclusive_taxes',
            },
        ),
        migrations.CreateModel(
            name='FuelAgreementPricingManualIncludingTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.ForeignKey(db_column='pricing_manual_id', on_delete=django.db.models.deletion.RESTRICT, related_name='included_taxes', to='pricing.fuelagreementpricingmanual', verbose_name='Fuel Agreement Pricing Manual')),
                ('tax_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pricing.taxcategory', verbose_name='Tax Category')),
                ('applies_to_fees', models.BooleanField(default=False, verbose_name='Cascade to Fees?')),
            ],
            options={
                'db_table': 'suppliers_fuel_agreements_pricing_manual_inclusive_taxes',
            },
        ),
        migrations.CreateModel(
            name='FuelPricingMarketIncludingTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.ForeignKey(db_column='pricing_market_id', on_delete=django.db.models.deletion.RESTRICT, related_name='included_taxes', to='pricing.fuelpricingmarket', verbose_name='Market Fuel Pricing')),
                ('tax_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pricing.taxcategory', verbose_name='Tax Category')),
                ('applies_to_fees', models.BooleanField(default=False, verbose_name='Cascade to Fees?')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market_inclusive_taxes',
            },
        ),
        migrations.DeleteModel(
            name='SupplierFuelFeeInclusiveTaxes',
        ),
    ]
