# Generated by Django 4.0.3 on 2023-07-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0052_merge_20230711_1543'),
        ('pricing', '0053_merge_20230711_1103'),
    ]

    operations = [
    ]
