# Generated by Django 4.0.3 on 2023-07-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0053_taxruleexception_source_agreement'),
        ('pricing', '0054_merge_20230711_1659'),
    ]

    operations = [
    ]
