# Generated by Django 4.0.3 on 2023-07-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0052_alter_supplierfuelfeerate_specific_fuel'),
        ('pricing', '0054_fuelagreementpricingformulaincludingtaxes_and_more'),
    ]

    operations = [
    ]
