# Generated by Django 4.0.3 on 2023-07-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20230630_0925'),
        ('pricing', '0055_merge_20230727_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='specific_fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fueltype', verbose_name='Specific Fuel'),
        ),
    ]
