# Generated by Django 4.0.3 on 2023-07-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0054_fuelagreementpricingformulaincludingtaxes_and_more'),
        ('pricing', '0055_merge_20230714_1040'),
    ]

    operations = [
    ]
