# Generated by Django 4.0.3 on 2023-07-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0056_merge_20230726_1214'),
    ]

    operations = [
    ]
