# Generated by Django 4.0.3 on 2023-08-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_merge_20230804_1013'),
        ('pricing', '0056_alter_supplierfuelfeerate_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='specific_fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fueltype', verbose_name='Specific Fuel'),
        ),
    ]
