# Generated by Django 4.0.3 on 2023-07-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0056_alter_supplierfuelfeerate_delivery_method_and_more'),
        ('pricing', '0057_merge_20230727_1056'),
    ]

    operations = [
    ]
