# Generated by Django 4.0.3 on 2023-08-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0057_alter_supplierfuelfeerate_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_client_formulae', to='organisation.organisation', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_pricing_for_client_manual', to='organisation.organisation', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_pricing_markets_where_is_client', to='organisation.organisation', verbose_name='Client'),
        ),
    ]
