# Generated by Django 4.0.3 on 2023-08-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0058_alter_fuelagreementpricingformula_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelagreementpricingformula',
            name='index_period_is_daily',
        ),
        migrations.RemoveField(
            model_name='fuelagreementpricingformula',
            name='index_period_is_monthly',
        ),
        migrations.RemoveField(
            model_name='fuelagreementpricingformula',
            name='index_period_is_weekly',
        ),
        migrations.RemoveField(
            model_name='fuelagreementpricingformula',
            name='index_price_is_high',
        ),
        migrations.RemoveField(
            model_name='fuelagreementpricingformula',
            name='index_price_is_low',
        ),
        migrations.RemoveField(
            model_name='fuelagreementpricingformula',
            name='index_price_is_mean',
        ),
        migrations.AddField(
            model_name='fuelindexpricing',
            name='source_organisation',
            field=models.ForeignKey(db_column='source_organisation', default=100000000, on_delete=django.db.models.deletion.RESTRICT, related_name='sourced_fuel_indices', to='organisation.organisation', verbose_name='Source Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelindexpricing',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='index_period_is_daily',
            field=models.BooleanField(default=False, verbose_name='Period Is Daily?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='index_period_is_weekly',
            field=models.BooleanField(default=False, verbose_name='Period Is Weekly?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='index_period_is_fortnightly',
            field=models.BooleanField(default=False, verbose_name='Period Is Fortnightly?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='index_period_is_monthly',
            field=models.BooleanField(default=False, verbose_name='Period Is Monthly?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='index_price_is_low',
            field=models.BooleanField(default=False, verbose_name='Price Is Low?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='index_price_is_mean',
            field=models.BooleanField(default=False, verbose_name='Price Is Mean?'),
        ),
        migrations.AddField(
            model_name='fuelindex',
            name='index_price_is_high',
            field=models.BooleanField(default=False, verbose_name='Price Is High?'),
        ),
    ]
