# Generated by Django 4.0.3 on 2023-07-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0057_merge_20230731_0823'),
        ('pricing', '0058_merge_20230727_1555'),
    ]

    operations = [
    ]
