# Generated by Django 4.0.3 on 2023-08-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0059_remove_fuelagreementpricingformula_index_period_is_daily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelindexpricing',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisationdocument', verbose_name='Source Document'),
        ),
    ]
