# Generated by Django 4.0.3 on 2023-08-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0057_alter_supplierfuelfeerate_delivery_method_and_more'),
        ('pricing', '0059_merge_20230731_0831'),
    ]

    operations = [
    ]
