# Generated by Django 4.0.3 on 2023-08-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0058_alter_fuelagreementpricingformula_client_and_more'),
        ('pricing', '0060_merge_20230807_1415'),
    ]

    operations = [
    ]
