# Generated by Django 4.0.3 on 2023-08-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0060_alter_fuelindexpricing_source_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelindexpricing',
            name='source_organisation',
            field=models.ForeignKey(db_column='source_organisation', limit_choices_to={'details__is_trading': True, 'details__type__in': [2, 5, 13, 17], 'tags__pk': 2}, on_delete=django.db.models.deletion.RESTRICT, related_name='sourced_fuel_indices', to='organisation.organisation', verbose_name='Source Organisation'),
        ),
    ]
