# Generated by Django 4.0.3 on 2023-08-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20230807_1403'),
        ('pricing', '0061_alter_fuelindexpricing_source_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
            ],
            options={
                'permissions': [('p_view', 'Suppliers: view'), ('p_create', 'Suppliers: create'), ('p_update', 'Suppliers: update')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.globalconfiguration',),
        ),
    ]
