# Generated by Django 4.0.3 on 2023-08-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0061_alter_fuelindexpricing_source_organisation'),
        ('pricing', '0061_merge_20230808_1537'),
    ]

    operations = [
    ]
