# Generated by Django 4.0.3 on 2023-08-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0062_merge_20230809_1502'),
        ('pricing', '0062_permissions'),
    ]

    operations = [
    ]
