# Generated by Django 4.0.3 on 2023-08-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0063_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='pricing_discount_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='Pricing Discount Amount'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='pricing_discount_percentage',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='Pricing Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='fuelindexpricing',
            name='source_organisation',
            field=models.ForeignKey(db_column='source_organisation', limit_choices_to=models.Q(('details__is_trading', True), models.Q(('tags__pk', 2), ('details__type__in', [2, 5, 13, 17]), _connector='OR')), on_delete=django.db.models.deletion.RESTRICT, related_name='sourced_fuel_indices', to='organisation.organisation', verbose_name='Source Organisation'),
        ),
        migrations.AlterField(
            model_name='taxratepercentage',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Tax Percentage'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='tax_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Tax Unit Rate'),
        ),
        migrations.AlterField(
            model_name='taxruleexception',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Tax Percentage'),
        ),
        migrations.AlterField(
            model_name='taxruleexception',
            name='tax_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Tax Unit Rate'),
        ),
    ]
