# Generated by Django 4.0.3 on 2023-08-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0063_alter_permissions_options'),
        ('pricing', '0063_merge_0062_merge_20230809_1502_0062_permissions'),
    ]

    operations = [
    ]
