# Generated by Django 4.0.3 on 2023-08-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20230807_1403'),
        ('pricing', '0064_alter_fuelagreementpricingmanual_pricing_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelindex',
            name='index_period_is_daily',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='index_period_is_fortnightly',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='index_period_is_monthly',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='index_period_is_weekly',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='index_price_is_high',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='index_price_is_low',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='index_price_is_mean',
        ),
        migrations.RemoveField(
            model_name='fuelindex',
            name='pricing_unit',
        ),
        migrations.RemoveField(
            model_name='fuelindexpricing',
            name='fuel_index',
        ),
        migrations.CreateModel(
            name='FuelIndexDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_index', to='pricing.fuelindex', verbose_name='Fuel Index Details')),
                ('pricing_unit', models.ForeignKey(db_column='pricing_unit', on_delete=django.db.models.deletion.RESTRICT, to='core.pricingunit', verbose_name='Pricing Unit')),
                ('index_period_is_daily', models.BooleanField(default=False, verbose_name='Period Is Daily?')),
                ('index_period_is_weekly', models.BooleanField(default=False, verbose_name='Period Is Weekly?')),
                ('index_period_is_fortnightly', models.BooleanField(default=False, verbose_name='Period Is Fortnightly?')),
                ('index_period_is_monthly', models.BooleanField(default=False, verbose_name='Period Is Monthly?')),
                ('index_price_is_low', models.BooleanField(default=False, verbose_name='Price Is Low?')),
                ('index_price_is_mean', models.BooleanField(default=False, verbose_name='Price Is Mean?')),
                ('index_price_is_high', models.BooleanField(default=False, verbose_name='Price Is High?')),
            ],
            options={
                'db_table': 'fuel_indices_details',
            },
        ),
        migrations.AddField(
            model_name='fuelindexpricing',
            name='fuel_index_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.fuelindexdetails', verbose_name='Fuel Index Details'),
        ),
    ]
