# Generated by Django 4.0.3 on 2023-08-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0064_alter_fuelagreementpricingmanual_pricing_discount_amount_and_more'),
        ('pricing', '0064_merge_20230810_1806'),
    ]

    operations = [
    ]
