# Generated by Django 4.0.3 on 2023-08-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0066_alter_fuelagreementpricingformula_pricing_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelindexdetails',
            name='fuel_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pricing.fuelindex', verbose_name='Fuel Index Details'),
        ),
    ]
