# Generated by Django 4.0.3 on 2023-08-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0065_merge_20230811_1930'),
        ('pricing', '0067_alter_fuelindexdetails_fuel_index'),
    ]

    operations = [
    ]
