# Generated by Django 4.0.3 on 2023-08-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20230807_1403'),
        ('pricing', '0067_alter_fuelindexdetails_fuel_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelindexdetails',
            name='pricing_unit',
        ),
        migrations.AddField(
            model_name='fuelindexpricing',
            name='pricing_unit',
            field=models.ForeignKey(db_column='pricing_unit', default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.pricingunit', verbose_name='Pricing Unit'),
            preserve_default=False,
        ),
    ]
