# Generated by Django 4.0.3 on 2023-08-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0068_merge_20230818_1520'),
        ('pricing', '0068_remove_fuelindexdetails_pricing_unit_and_more'),
    ]

    operations = [
    ]
