# Generated by Django 4.0.3 on 2023-08-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0068_remove_fuelindexdetails_pricing_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelindexpricing',
            name='source_organisation',
            field=models.ForeignKey(db_column='source_organisation', limit_choices_to=models.Q(('details__is_trading', True), models.Q(('tags__pk', 2), ('details__type__in', [2, 5, 13, 17]), ('agreements_where_supplier__isnull', False), _connector='OR')), on_delete=django.db.models.deletion.RESTRICT, related_name='sourced_fuel_indices', to='organisation.organisation', verbose_name='Source Organisation'),
        ),
    ]
