# Generated by Django 4.0.3 on 2023-08-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0069_alter_fuelindexpricing_source_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelagreementpricingformula',
            name='specific_handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'details__type_id': 3, 'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_formula_pricing', to='organisation.organisation', verbose_name='Specific Handler'),
        ),
        migrations.AddField(
            model_name='fuelagreementpricingmanual',
            name='specific_handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'details__type_id': 3, 'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_discount_pricing', to='organisation.organisation', verbose_name='Specific Handler'),
        ),
        migrations.AddField(
            model_name='fuelpricingmarket',
            name='specific_handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'details__type_id': 3, 'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_market_pricing', to='organisation.organisation', verbose_name='Specific Handler'),
        ),
    ]
