# Generated by Django 4.0.3 on 2023-08-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0069_alter_fuelindexpricing_source_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpricingmarketpld',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'details__type_id__in': [2, 3, 4, 5, 7, 8, 13, 14]}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market_plds_where_is_supplier', to='organisation.organisation', verbose_name='Supplier'),
        ),
    ]
