# Generated by Django 4.0.3 on 2023-08-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0069_alter_fuelindexpricing_source_organisation'),
        ('pricing', '0069_merge_20230821_1357'),
    ]

    operations = [
    ]
