# Generated by Django 4.0.3 on 2023-08-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0070_alter_fuelpricingmarketpld_supplier'),
        ('pricing', '0070_merge_20230823_1553'),
    ]

    operations = [
    ]
