# Generated by Django 4.0.3 on 2023-08-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0070_fuelagreementpricingformula_specific_handler_and_more'),
        ('pricing', '0071_merge_20230825_0913'),
    ]

    operations = [
    ]
