# Generated by Django 4.0.3 on 2023-08-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_aprontype'),
        ('organisation', '0108_merge_20230608_1617'),
        ('pricing', '0071_merge_20230825_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='specific_apron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_fuel_fees', to='core.aprontype', verbose_name='Specific Apron'),
        ),
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='specific_handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'details__type_id': 3, 'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_fuel_fees', to='organisation.organisation', verbose_name='Specific Handler'),
        ),
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='specific_handler_is_excluded',
            field=models.BooleanField(default=False, verbose_name='Spec. Handler Is Excluded?'),
        ),
    ]
