# Generated by Django 4.0.3 on 2023-09-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0072_supplierfuelfeerate_specific_apron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelfeecategory',
            name='applies_to_overwing_only',
            field=models.BooleanField(default=False, verbose_name='Applies To Over-Wing Only?'),
        ),
    ]
