# Generated by Django 4.0.3 on 2023-08-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0072_merge_20230825_1323'),
        ('pricing', '0072_supplierfuelfeerate_specific_apron_and_more'),
    ]

    operations = [
    ]
