# Generated by Django 4.0.3 on 2023-09-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0073_fuelfeecategory_applies_to_overwing_only'),
        ('pricing', '0073_merge_20230831_1358'),
    ]

    operations = [
    ]
