# Generated by Django 4.0.3 on 2023-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0073_fuelfeecategory_applies_to_overwing_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelfeecategory',
            name='applies_for_no_fuel_uplift',
            field=models.BooleanField(default=False, verbose_name='Applies For No Fuel Uplift?'),
        ),
        migrations.AddField(
            model_name='fuelfeecategory',
            name='applies_for_defueling',
            field=models.BooleanField(default=False, verbose_name='Applies For Defueling?'),
        ),
        migrations.AddField(
            model_name='fuelfeecategory',
            name='applies_for_multi_vehicle_uplift',
            field=models.BooleanField(default=False, verbose_name='Applies For Multi-Vehicle Uplift?'),
        ),
    ]
