# Generated by Django 4.0.3 on 2023-09-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0074_fuelfeecategory_applies_for_defueling_and_more'),
        ('pricing', '0074_merge_20230901_1441'),
    ]

    operations = [
    ]
