# Generated by Django 4.0.3 on 2023-09-07 12:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0074_fuelfeecategory_applies_for_defueling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFuelFeeRateValidityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_fee_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_periods', to='pricing.supplierfuelfeerate', verbose_name='Fuel Fee Validity Period')),
                ('valid_from_dow', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Valid From DOW')),
                ('valid_to_dow', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Valid To DOW')),
                ('valid_from_time', models.TimeField(verbose_name='Valid From Time')),
                ('valid_to_time', models.TimeField(verbose_name='Valid To Time')),
                ('is_local', models.BooleanField(default=False, verbose_name='Local Time?')),
            ],
            options={
                'db_table': 'suppliers_fuel_fees_rates_validity_periods',
            },
        ),
    ]
