# Generated by Django 4.0.3 on 2023-09-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0075_merge_20230905_1501'),
        ('pricing', '0075_supplierfuelfeeratevalidityperiod'),
    ]

    operations = [
    ]
