# Generated by Django 4.0.3 on 2023-09-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0109_alter_operatorpreferredgroundhandler_ground_handler_and_more'),
        ('pricing', '0075_supplierfuelfeeratevalidityperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='specific_handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_formula_pricing', to='organisation.organisation', verbose_name='Specific Handler'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='specific_handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_discount_pricing', to='organisation.organisation', verbose_name='Specific Handler'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='specific_handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_market_pricing', to='organisation.organisation', verbose_name='Specific Handler'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarketpld',
            name='supplier',
            field=models.ForeignKey(limit_choices_to=models.Q(('details__type_id__in', [2, 3, 4, 5, 7, 8, 13, 14]), ('airport_details__isnull', False), ('handler_details__isnull', False), ('ipa_details__isnull', False), ('oilco_details__isnull', False), ('service_provider_locations__isnull', False), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market_plds_where_is_supplier', to='organisation.organisation', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='supplierfuelfeerate',
            name='specific_handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_fuel_fees', to='organisation.organisation', verbose_name='Specific Handler'),
        ),
    ]
