# Generated by Django 4.0.3 on 2023-10-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0076_alter_fuelagreementpricingformula_specific_handler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelindexpricing',
            name='superseded_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_pricing', to='pricing.fuelindexpricing', verbose_name='Superseded By'),
        ),
    ]
