# Generated by Django 4.0.3 on 2023-09-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0076_alter_fuelagreementpricingformula_specific_handler_and_more'),
        ('pricing', '0076_merge_20230914_1704'),
    ]

    operations = [
    ]
