# Generated by Django 4.0.3 on 2023-10-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
        ('pricing', '0077_fuelindexpricing_superseded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierfuelfeerate',
            name='specific_hookup_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.hookupmethod', verbose_name='Specific Hookup Method'),
        ),
    ]
