# Generated by Django 4.0.3 on 2023-10-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0079_alter_taxrule_applies_to_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments'),
        ),
    ]
