# Generated by Django 4.0.3 on 2023-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0080_taxrule_comments_taxruleexception_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='exemption_available_with_cert',
            field=models.BooleanField(default=False, verbose_name='Exemption Available with Certificate?'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='exemption_available_with_cert',
            field=models.BooleanField(default=False, verbose_name='Exemption Available with Certificate?'),
        ),
    ]
