# Generated by Django 4.0.3 on 2023-10-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
        ('pricing', '0081_taxrule_exemption_available_with_cert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelagreementpricingformula',
            name='specific_apron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_formula_pricing', to='core.aprontype', verbose_name='Specific Apron'),
        ),
        migrations.AddField(
            model_name='fuelagreementpricingmanual',
            name='specific_apron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_discount_pricing', to='core.aprontype', verbose_name='Specific Apron'),
        ),
        migrations.AddField(
            model_name='fuelpricingmarket',
            name='specific_apron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specific_market_pricing', to='core.aprontype', verbose_name='Specific Apron'),
        ),
    ]
