# Generated by Django 4.0.3 on 2023-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0077_merge_20230929_1355'),
        ('pricing', '0081_taxrule_exemption_available_with_cert_and_more'),
    ]

    operations = [
    ]
