# Generated by Django 4.0.3 on 2023-10-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
        ('pricing', '0082_fuelagreementpricingformula_specific_apron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelagreementpricingformula',
            name='specific_hookup_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.hookupmethod', verbose_name='Specific Hookup Method'),
        ),
        migrations.AddField(
            model_name='fuelagreementpricingmanual',
            name='specific_hookup_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.hookupmethod', verbose_name='Specific Hookup Method'),
        ),
        migrations.AddField(
            model_name='fuelpricingmarket',
            name='specific_hookup_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.hookupmethod', verbose_name='Specific Hookup Method'),
        ),
    ]
