# Generated by Django 4.0.3 on 2023-10-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0082_fuelagreementpricingformula_specific_apron_and_more'),
        ('pricing', '0082_merge_20231006_1042'),
    ]

    operations = [
    ]
