# Generated by Django 4.0.3 on 2023-10-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
        ('pricing', '0083_fuelagreementpricingformula_specific_hookup_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='specific_fuel_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.fuelcategory', verbose_name='Specific Fuel Category'),
        ),
        migrations.AddField(
            model_name='taxruleexception',
            name='specific_fuel_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.fuelcategory', verbose_name='Specific Fuel Category'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='specific_fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.fueltype', verbose_name='Specific Fuel'),
        ),
        migrations.AlterField(
            model_name='taxruleexception',
            name='specific_fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.fueltype', verbose_name='Specific Fuel'),
        ),
    ]
