# Generated by Django 4.0.3 on 2023-10-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0083_fuelagreementpricingformula_specific_hookup_method_and_more'),
        ('pricing', '0083_merge_20231010_1707'),
    ]

    operations = [
    ]
