# Generated by Django 4.0.3 on 2023-10-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0084_merge_20231012_1116'),
        ('pricing', '0084_taxrule_specific_fuel_cat_and_more'),
    ]

    operations = [
    ]
