# Generated by Django 4.0.3 on 2023-10-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0085_alter_supplierfuelfee_ipa'),
        ('pricing', '0085_merge_20231013_1216'),
    ]

    operations = [
    ]
