# Generated by Django 4.0.3 on 2023-10-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
        ('pricing', '0085_alter_supplierfuelfee_ipa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPricingMarketDeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.fuelpricingmarket', verbose_name='Market Pricing')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.fuelequipmenttype', verbose_name='Delivery Method')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market_delivery_methods',
            },
        ),
        migrations.CreateModel(
            name='FuelAgreementPricingManualDeliveryMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.fuelagreementpricingmanual', verbose_name='Formula Discount Pricing')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.fuelequipmenttype', verbose_name='Delivery Method')),
            ],
            options={
                'db_table': 'suppliers_fuel_agreements_pricing_manual_delivery_methods',
            },
        ),
        migrations.CreateModel(
            name='FuelAgreementPricingFormulaDeliveryMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.fuelagreementpricingformula', verbose_name='Formula Agreement Pricing')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.fuelequipmenttype', verbose_name='Delivery Method')),
            ],
            options={
                'db_table': 'suppliers_fuel_agreements_pricing_formulae_delivery_methods',
            },
        ),
    ]
