# Generated by Django 4.0.3 on 2023-10-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
        ('pricing', '0087_fuelagreementpricingformula_delivery_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuelequipmenttype', verbose_name='Delivery Method'),
        ),
    ]
