# Generated by Django 4.0.3 on 2023-10-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hookupmethod'),
        ('pricing', '0088_alter_fuelagreementpricingformula_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreementpricingformula',
            name='delivery_methods',
            field=models.ManyToManyField(blank=True, related_name='fuel_agreement_pricing_formula', through='pricing.FuelAgreementPricingFormulaDeliveryMethods', to='core.fuelequipmenttype', verbose_name='Delivery Method(s)'),
        ),
        migrations.AlterField(
            model_name='fuelagreementpricingmanual',
            name='delivery_methods',
            field=models.ManyToManyField(blank=True, related_name='fuel_agreement_pricing_discount', through='pricing.FuelAgreementPricingManualDeliveryMethods', to='core.fuelequipmenttype', verbose_name='Delivery Method(s)'),
        ),
        migrations.AlterField(
            model_name='fuelpricingmarket',
            name='delivery_methods',
            field=models.ManyToManyField(blank=True, related_name='fuel_market_pricing', through='pricing.FuelPricingMarketDeliveryMethod', to='core.fuelequipmenttype', verbose_name='Delivery Method(s)'),
        ),
    ]
