# Generated by Django 4.0.3 on 2023-10-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0089_alter_fuelagreementpricingformula_delivery_methods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelagreementpricingformula',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='fuelagreementpricingmanual',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='fuelpricingmarket',
            name='delivery_method',
        ),
    ]
