# Generated by Django 4.0.3 on 2023-10-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0086_merge_20231016_1451'),
        ('pricing', '0090_remove_fuelagreementpricingformula_delivery_method_and_more'),
    ]

    operations = [
    ]
