# Generated by Django 4.0.3 on 2023-10-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0091_fuelindex_priority_fuelpricingmarketpld_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('p_view', 'Data Management: View Fuel Indices, Fuel Agreements, Agreement and Market Pricing'), ('p_create', 'Data Management: Create Fuel Indices, Fuel Agreements, Agreement and Market Pricing'), ('p_update', 'Data Management: Update Fuel Indices, Fuel Agreements, Agreement and Market Pricing'), ('p_moderate', 'Data Management: Review Created Supplier Fuel Agreements and Pricing - Acceptance Review'), ('p_publish', 'Data Management: (Un-)Publish Fuel Indices, Fuel Agreements, Agreement and Market Pricing'), ('p_send_pricing_update_request', 'Data Management: Send Auto-generated Pricing Update Request Emails')]},
        ),
    ]
