# Generated by Django 4.2.6 on 2023-11-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0091_merge_20231018_1114'),
        ('pricing', '0092_alter_permissions_options'),
    ]

    operations = [
    ]
