# Generated by Django 4.2.6 on 2023-11-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0093_fuelpricingmarketpldlocation_billable_organisation'),
        ('pricing', '0093_merge_20231103_1408'),
    ]

    operations = [
    ]
