# Generated by Django 4.2.6 on 2023-11-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0114_alter_organisationcontactdetails_email_address'),
        ('pricing', '0093_fuelpricingmarketpldlocation_billable_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpricingmarketpldlocation',
            name='billable_organisation',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('details__type_id__in', [2, 3, 4, 5, 7, 8, 9, 13, 14]), ('airport_details__isnull', False), ('handler_details__isnull', False), ('ipa_details__isnull', False), ('oilco_details__isnull', False), ('service_provider_locations__isnull', False), _connector='OR'), null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='billed_fuel_pricing_market_pld_locations', to='organisation.organisation', verbose_name='Billable Organisation'),
        ),
    ]
