# Generated by Django 4.2.6 on 2023-12-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_usersettings'),
        ('organisation', '0122_dlacontractlocation_enforce_fuel_order'),
        ('pricing', '0094_alter_fuelpricingmarketpldlocation_billable_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPricingMarketIpaNameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market_name_aliases_at_location', to='organisation.organisation', verbose_name='Location')),
                ('name', models.CharField(max_length=500, verbose_name='IPA Name')),
                ('ipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pricing_market_name_aliases', to='organisation.organisation', verbose_name='IPA')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.person', verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market_ipa_name_aliases',
            },
        ),
    ]
