# Generated by Django 4.2.6 on 2023-11-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0094_alter_fuelpricingmarketpldlocation_billable_organisation'),
        ('pricing', '0094_merge_20231109_1344'),
    ]

    operations = [
    ]
