# Generated by Django 4.2.6 on 2023-12-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0095_fuelpricingmarketipanamealias'),
        ('pricing', '0095_merge_20231109_1511'),
    ]

    operations = [
    ]
