# Generated by Django 4.2.6 on 2023-12-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0095_fuelpricingmarketipanamealias'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPricingMarketCsvImporterNoteField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_str', models.CharField(max_length=500, verbose_name='Relevant Phrase from CSV Note')),
                ('field_name', models.CharField(max_length=100, verbose_name='DB Field Name')),
                ('field_value', models.BigIntegerField(verbose_name='DB Field Value')),
            ],
            options={
                'db_table': 'suppliers_fuel_pricing_market_csv_importer_note_fields',
            },
        ),
    ]
