# Generated by Django 4.2.6 on 2023-12-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0096_fuelpricingmarketcsvimporternotefield'),
        ('pricing', '0096_merge_20231208_1755'),
    ]

    operations = [
    ]
