# Generated by Django 4.2.6 on 2023-11-28 13:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0033_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('requires_full_workday', models.BooleanField(default=False)),
                ('requires_comment', models.BooleanField(default=False)),
                ('is_specific', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'staff_attendance_types',
            },
        ),
        migrations.CreateModel(
            name='BlanketAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='Start Time')),
                ('end_hour', models.TimeField(verbose_name='End Time')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('applied_on_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=[1, 2, 3, 4, 5, 6, 7]), size=None)),
                ('applied_to_weeks', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=[1, 2, 3, 4, 5, 6]), size=None)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.attendancetype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
            ],
            options={
                'db_table': 'staff_blanket_attendance',
            },
        ),
        migrations.CreateModel(
            name='SpecificAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='Start Time')),
                ('end_hour', models.TimeField(verbose_name='End Time')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('applied_on_dates', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=0), size=None)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.attendancetype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
            ],
            options={
                'db_table': 'staff_specific_attendance',
            },
        ),
        migrations.CreateModel(
            name='BlanketAttendanceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='Start Time')),
                ('end_hour', models.TimeField(verbose_name='End Time')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('applied_on_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=[1, 2, 3, 4, 5, 6, 7]), size=None)),
                ('applied_to_weeks', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=[1, 2, 3, 4, 5, 6]), size=None)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.attendancetype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
                ('switched_with_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overriden_by', to='staff.blanketattendance')),
            ],
            options={
                'db_table': 'staff_blanket_attendance_override',
            },
        ),
    ]
