# Generated by Django 4.2.6 on 2023-11-29 14:35

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_usersettings'),
        ('organisation', '0124_organisationpersonteam_schedule_managed_by_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlanketEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='Start Time')),
                ('end_hour', models.TimeField(verbose_name='End Time')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Comment')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved?')),
                ('is_disapproved', models.BooleanField(default=False, verbose_name='Disapproved?')),
                ('flagged_for_delete', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('flagged_for_edit', models.BooleanField(default=False, verbose_name='Edited?')),
                ('applied_on_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=[1, 2, 3, 4, 5], verbose_name='Days'), size=None)),
                ('applied_on_weeks', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Applied on Weeks'), size=None)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actioned_blanket_entries', to='user.person')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_blanket_entries', to='user.person')),
            ],
            options={
                'db_table': 'staff_blanket_entry',
            },
        ),
        migrations.CreateModel(
            name='BlanketEntryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='Start Time')),
                ('end_hour', models.TimeField(verbose_name='End Time')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Comment')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved?')),
                ('is_disapproved', models.BooleanField(default=False, verbose_name='Disapproved?')),
                ('flagged_for_delete', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('flagged_for_edit', models.BooleanField(default=False, verbose_name='Edited?')),
                ('applied_on_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=[1, 2, 3, 4, 5], verbose_name='Days'), size=None)),
                ('applied_on_weeks', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Applied on Weeks'), size=None)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actioned_blanket_entry_overrides', to='user.person', verbose_name='Action By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_blanket_entry_overrides', to='user.person', verbose_name='Created By')),
            ],
            options={
                'db_table': 'staff_blanket_entry_override',
            },
        ),
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('requires_full_workday', models.BooleanField(default=False, verbose_name='Requires Full Workday?')),
                ('requires_comment', models.BooleanField(default=False, verbose_name='Requires Comment?')),
                ('is_specific', models.BooleanField(default=False, verbose_name='Specific Entry Only?')),
            ],
            options={
                'db_table': 'staff_entry_types',
            },
        ),
        migrations.CreateModel(
            name='FinalizedMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(2000)], verbose_name='Year')),
                ('month', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Month')),
                ('closed_on', models.DateTimeField(auto_now_add=True, verbose_name='Closed On')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_months', to='user.person', verbose_name='Closed By')),
            ],
            options={
                'db_table': 'staff_finalized_month',
            },
        ),
        migrations.CreateModel(
            name='SpecificEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='Start Time')),
                ('end_hour', models.TimeField(verbose_name='End Time')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Comment')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved?')),
                ('is_disapproved', models.BooleanField(default=False, verbose_name='Disapproved?')),
                ('flagged_for_delete', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('flagged_for_edit', models.BooleanField(default=False, verbose_name='Edited?')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('applied_on_dates', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Dates'), size=None)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actioned_specific_entries', to='user.person', verbose_name='Actioned By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_specific_entries', to='user.person', verbose_name='Created By')),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.entrytype', verbose_name='Entry Type')),
                ('original_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.specificentry', verbose_name='Edited Entry')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_entries', to='user.person', verbose_name='Person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationpersonteam', verbose_name='Team')),
            ],
            options={
                'db_table': 'staff_specific_entry',
            },
        ),
        migrations.RemoveField(
            model_name='blanketattendance',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='blanketattendance',
            name='person',
        ),
        migrations.RemoveField(
            model_name='blanketattendanceoverride',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='blanketattendanceoverride',
            name='person',
        ),
        migrations.RemoveField(
            model_name='blanketattendanceoverride',
            name='switched_with_entry',
        ),
        migrations.RemoveField(
            model_name='specificattendance',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='specificattendance',
            name='person',
        ),
        migrations.DeleteModel(
            name='AttendanceType',
        ),
        migrations.DeleteModel(
            name='BlanketAttendance',
        ),
        migrations.DeleteModel(
            name='BlanketAttendanceOverride',
        ),
        migrations.DeleteModel(
            name='SpecificAttendance',
        ),
        migrations.AddField(
            model_name='blanketentryoverride',
            name='entry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.entrytype', verbose_name='Entry Type'),
        ),
        migrations.AddField(
            model_name='blanketentryoverride',
            name='original_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.blanketentryoverride', verbose_name='Edited Entry'),
        ),
        migrations.AddField(
            model_name='blanketentryoverride',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanket_entry_overrides', to='user.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='blanketentryoverride',
            name='switched_with_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overriden_by', to='staff.blanketentry', verbose_name='Switched Entry'),
        ),
        migrations.AddField(
            model_name='blanketentryoverride',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationpersonteam', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='blanketentry',
            name='entry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.entrytype', verbose_name='Entry Type'),
        ),
        migrations.AddField(
            model_name='blanketentry',
            name='original_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.blanketentry', verbose_name='Edited Entry'),
        ),
        migrations.AddField(
            model_name='blanketentry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanket_entries', to='user.person'),
        ),
        migrations.AddField(
            model_name='blanketentry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationpersonteam', verbose_name='Team'),
        ),
    ]
