# Generated by Django 4.2.6 on 2023-11-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0125_alter_organisationpersonteam_person'),
        ('staff', '0002_blanketentry_blanketentryoverride_entrytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanketentry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_blanket_entries', to='organisation.organisationpersonteam', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_blanket_entry_overrides', to='organisation.organisationpersonteam', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_specific_entries', to='organisation.organisationpersonteam', verbose_name='Team'),
        ),
    ]
