# Generated by Django 4.2.7 on 2023-11-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_blanketentry_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrytype',
            old_name='is_specific',
            new_name='is_specific_only',
        ),
    ]
