# Generated by Django 4.2.7 on 2023-12-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_is_specific_entrytype_is_specific_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanketentry',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated On'),
        ),
    ]
