# Generated by Django 4.2.7 on 2023-12-04 12:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_usersettings'),
        ('staff', '0006_alter_blanketentry_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanketentry',
            name='action_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_blanket_entries', to='user.person', verbose_name='Action By'),
        ),
        migrations.AlterField(
            model_name='blanketentry',
            name='applied_on_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=[1, 2, 3, 4, 5], verbose_name='Days'), size=None),
        ),
        migrations.AlterField(
            model_name='blanketentry',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_blanket_entries', to='user.person', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='blanketentry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanket_entries', to='user.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='action_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_blanket_entry_overrides', to='user.person', verbose_name='Action By'),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='applied_on_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=[1, 2, 3, 4, 5], verbose_name='Days'), size=None),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_blanket_entry_overrides', to='user.person', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='action_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_specific_entries', to='user.person', verbose_name='Actioned By'),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='applied_on_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(verbose_name='Dates'), size=None),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_specific_entries', to='user.person', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
    ]
