# Generated by Django 4.2.7 on 2023-12-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_blanketentry_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanketentry',
            name='action_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Action On'),
        ),
        migrations.AddField(
            model_name='blanketentryoverride',
            name='action_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Action On'),
        ),
        migrations.AddField(
            model_name='specificentry',
            name='action_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Action On'),
        ),
    ]
