# Generated by Django 4.2.7 on 2023-12-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_usersettings'),
        ('staff', '0009_blanketentry_action_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanketentry',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_blanket_entries', to='user.person', verbose_name='Action By'),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_blanket_entry_overrides', to='user.person', verbose_name='Action By'),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_specific_entries', to='user.person', verbose_name='Actioned By'),
        ),
    ]
