# Generated by Django 4.2.7 on 2023-12-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_blanketentry_action_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanketentry',
            name='created_on',
            field=models.DateTimeField(verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='created_on',
            field=models.DateTimeField(verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='created_on',
            field=models.DateTimeField(verbose_name='Created On'),
        ),
    ]
