# Generated by Django 4.2.7 on 2023-12-11 08:42

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_blanketentry_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanketentry',
            name='applied_on_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=[1, 2, 3, 4, 5], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Days'), size=None),
        ),
        migrations.AlterField(
            model_name='blanketentry',
            name='applied_on_weeks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)], verbose_name='Applied on Weeks'), size=None),
        ),
        migrations.AlterField(
            model_name='blanketentry',
            name='created_on',
            field=models.DateTimeField(blank=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='applied_on_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=[1, 2, 3, 4, 5], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Days'), size=None),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='applied_on_weeks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)], verbose_name='Applied on Weeks'), size=None),
        ),
        migrations.AlterField(
            model_name='blanketentryoverride',
            name='created_on',
            field=models.DateTimeField(blank=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='finalizedmonth',
            name='month',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='finalizedmonth',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='applied_on_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dates'), size=None),
        ),
        migrations.AlterField(
            model_name='specificentry',
            name='created_on',
            field=models.DateTimeField(blank=True, verbose_name='Created On'),
        ),
    ]
