# Generated by Django 4.2.6 on 2023-12-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_teamrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrole',
            old_name='role',
            new_name='name',
        ),
    ]
