# Generated by Django 4.2.6 on 2023-12-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_remove_specificentry_related_blanket_entry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlanketEntryOverride',
        ),
    ]
