# Generated by Django 4.2.6 on 2023-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_delete_blanketentryoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrytype',
            name='background',
            field=models.CharField(default='#515d8a', max_length=7, verbose_name='Background'),
        ),
    ]
