# Generated by Django 3.2.9 on 2022-01-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(max_length=35, null=True, verbose_name='ASN')),
                ('ads_asn', models.CharField(max_length=50, null=True, verbose_name='ADS ASN')),
                ('pax_seats', models.IntegerField(null=True, verbose_name='Pax Seats')),
                ('yom', models.IntegerField(null=True, verbose_name='YOM')),
                ('source', models.CharField(default='EMMA', max_length=6, verbose_name='Source')),
                ('is_decommissioned', models.BooleanField(default=False, verbose_name='Decommissioned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(max_length=4, verbose_name='ICAO Type')),
                ('manufacturer', models.CharField(max_length=40, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=50, verbose_name='Name')),
                ('category', models.CharField(max_length=2, verbose_name='Category')),
            ],
            options={
                'db_table': 'aircraft_types',
            },
        ),
        migrations.CreateModel(
            name='AircraftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=50, verbose_name='Registration')),
                ('change_effective_date', models.DateField(verbose_name='Change Date')),
                ('source', models.CharField(max_length=6, verbose_name='Source')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_history', to='aircraft.aircraft', verbose_name='Aircraft')),
            ],
            options={
                'db_table': 'aircraft_history',
            },
        ),
    ]
