# Generated by Django 3.2.9 on 2022-01-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafthistory',
            name='homebase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airport', verbose_name='Homebase'),
        ),
    ]
