# Generated by Django 3.2.9 on 2022-01-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0002_aircrafthistory_homebase'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafthistory',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_list', to='organisation.organisation', verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_rev', to='aircraft.aircrafthistory'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircraft.aircrafttype', verbose_name='Aircraft Type'),
        ),
    ]
