# Generated by Django 3.2.9 on 2022-02-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafttype',
            name='category',
            field=models.CharField(max_length=3, verbose_name='Category'),
        ),
    ]
