# Generated by Django 3.2.9 on 2022-03-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0024_alter_airportdetails_icao_code'),
        ('aircraft', '0004_alter_aircrafttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafthistory',
            name='homebase_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Homebase'),
        ),
    ]
