# Generated by Django 3.2.9 on 2022-03-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_aircrafthistory_homebase_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircrafthistory',
            name='homebase',
        ),
    ]
