# Generated by Django 3.2.9 on 2022-03-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0024_alter_airportdetails_icao_code'),
        ('aircraft', '0007_rename_homebase_fk_aircrafthistory_homebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafthistory',
            name='homebase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Homebase'),
        ),
    ]
