# Generated by Django 4.0.3 on 2022-04-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0049_alter_organisation_options_and_more'),
        ('aircraft', '0009_alter_aircraft_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafthistory',
            name='homebase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Homebase'),
        ),
    ]
