# Generated by Django 4.0.3 on 2022-04-19 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0064_organisationaircrafttype_organisation_aircraft_types_and_more'),
        ('aircraft', '0010_alter_aircrafthistory_homebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafthistory',
            name='homebase',
            field=models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Homebase'),
        ),
    ]
