# Generated by Django 4.0.3 on 2022-10-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0013_alter_aircrafttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='test_aircraft',
            field=models.BooleanField(default=False, verbose_name='Is Test Aircraft?'),
        ),
    ]
