# Generated by Django 4.0.3 on 2022-11-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0098_ipalocation_location_email_and_more'),
        ('core', '0025_fueltype_contains_prist'),
        ('aircraft', '0014_aircraft_test_aircraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftTypeApprovedFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types_approved', to='aircraft.aircrafttype', verbose_name='Aircraft Type')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_types_approved', to='core.fueltype', verbose_name='Fuel Type')),
                ('specific_operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_types_approved_fuel', to='organisation.organisation', verbose_name='Specific Operator')),
            ],
            options={
                'db_table': 'aircraft_types_approved_fuel',
                'ordering': ['aircraft_type__manufacturer'],
            },
        ),
    ]
