# Generated by Django 4.0.3 on 2022-11-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0015_aircrafttypeapprovedfuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftWeightUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Unit name')),
            ],
            options={
                'db_table': 'aircraft_weight_units',
            },
        ),
    ]
