# Generated by Django 4.0.3 on 2023-02-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0016_aircraftweightunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafttype',
            name='maximum_fuel_indicative_litres',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='MTOW Indicative LBS'),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='mtow_indicative_kg',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='MTOW Indicative KG'),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='mtow_indicative_lbs',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='MTOW Indicative LBS'),
        ),
    ]
