# Generated by Django 4.0.3 on 2023-04-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0017_aircrafttype_maximum_fuel_indicative_litres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftDesignator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=10, verbose_name='ICAO')),
                ('iata', models.CharField(blank=True, max_length=10, null=True, verbose_name='IATA')),
                ('wtc', models.CharField(blank=True, max_length=1, null=True, verbose_name='WTC')),
            ],
            options={
                'db_table': 'aircraft_designators',
            },
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='type_designator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_types', to='aircraft.aircraftdesignator', verbose_name='Designator'),
        ),
    ]
