# Generated by Django 4.0.3 on 2023-02-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pricingunit_description_short'),
        ('aircraft', '0019_alter_aircrafthistory_registered_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafthistory',
            name='registered_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='Country of Registration'),
        ),
    ]
