# Generated by Django 4.0.3 on 2023-04-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0018_aircraftdesignator_aircrafttype_type_designator'),
        ('aircraft', '0020_alter_aircrafthistory_registered_country'),
    ]

    operations = [
    ]
