# Generated by Django 4.0.3 on 2023-05-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0021_merge_20230424_1725'),
        ('aircraft', '0021_merge_20230505_1344'),
    ]

    operations = [
    ]
