# Generated by Django 4.0.3 on 2023-09-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('aircraft', '0021_merge_20230505_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='asn',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='ASN'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='pax_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pax Seats'),
        ),
        migrations.AlterField(
            model_name='aircrafthistory',
            name='homebase',
            field=models.ForeignKey(blank=True, limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Homebase'),
        ),
    ]
