# Generated by Django 4.0.3 on 2023-09-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0022_alter_aircraft_asn_alter_aircraft_pax_seats_and_more'),
        ('aircraft', '0022_merge_20230505_1538'),
    ]

    operations = [
    ]
