# Generated by Django 4.0.3 on 2023-04-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_traveldocument_number_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSeenBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'chat_messages_seen',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='chat_seen_messages', through='chat.MessageSeenBy', to='user.person', verbose_name='Seen By'),
        ),
        migrations.AddField(
            model_name='messageseenby',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AddField(
            model_name='messageseenby',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
    ]
