# Generated by Django 4.0.3 on 2023-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messageseenby_message_seen_by_messageseenby_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleonline',
            name='channel_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Channel Name'),
        ),
    ]
