# Generated by Django 4.0.3 on 2023-04-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0077_handlingrequestdocumentfile_is_signed_and_more'),
        ('chat', '0003_peopleonline_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='handling_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='handling.handlingrequest', verbose_name='Handling Request'),
        ),
    ]
