# Generated by Django 4.0.3 on 2023-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_handling_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
