# Generated by Django 4.0.3 on 2023-05-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_missionlegservicing_handling_request'),
        ('chat', '0005_alter_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='mission.mission', verbose_name='Mission'),
        ),
    ]
