# Generated by Django 4.0.3 on 2023-09-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
