from django.urls import path
from pricing.views import *
from supplier.views import *

urlpatterns = [
    # Pricing Backlog

    path('data_management/fuel_pricing_backlog/', FuelPricingBacklogView.as_view(), name='fuel_pricing_backlog'),
    path('data_management/fuel_pricing_backlog_ajax/', FuelPricingBacklogAjaxView.as_view(),
         name='fuel_pricing_backlog_ajax'),

    path('data_management/fuel_pricing_backlog/pricing_update_email/<int:organisation_id>/<str:doc_type>/<int:pk>',
         SendFuelPricingUpdateRequestEmailView.as_view(), name='send_fuel_pricing_update_request_email'),

    # Agreements
    path('data_management/fuel_agreements/', FuelAgreementsListView.as_view(), name='fuel_agreements'),
    path('data_management/fuel_agreements_ajax/', FuelAgreementsListAjaxView.as_view(), name='fuel_agreements_ajax'),
    path('data_management/fuel_agreements/<int:pk>/', FuelAgreementDetailsView.as_view(), name='fuel_agreement'),
    path('data_management/fuel_agreements/create/', FuelAgreementCreateView.as_view(), name='fuel_agreement_create'),
    path('data_management/fuel_agreements/<int:pk>/edit/', FuelAgreementEditView.as_view(), name='fuel_agreement_edit'),
    path('data_management/fuel_agreements/<int:pk>/delete_document/', FuelAgreementDeleteDocumentView.as_view(),
         name='fuel_agreement_delete_document'),
    path('data_management/fuel_agreements/<int:pk>/supersede/',
         FuelAgreementSupersedeView.as_view(), name='fuel_agreement_supersede'),
    path('data_management/fuel_agreements/<int:pk>/extend/',
         FuelAgreementExtendView.as_view(), name='fuel_agreement_extend'),
    path('data_management/fuel_agreements/<int:pk>/void/', FuelAgreementVoidView.as_view(), name='fuel_agreement_void'),
    path('data_management/fuel_agreements/<int:pk>/publish/',
         FuelAgreementPublishView.as_view(), name='fuel_agreement_publish'),
    path('data_management/fuel_agreements/<int:pk>/unpublish/',
         FuelAgreementPublishView.as_view(), name='fuel_agreement_unpublish'),

    path('data_management/fuel_agreements/<int:pk>/formula_pricing/',
         AgreementFormulaPricingAjaxView.as_view(), name='agreement_formula_pricing'),
    path('data_management/fuel_agreements/<int:agreement_pk>/formula_pricing/<int:pk>/pricing_sublist/',
         AgreementFormulaPricingSubListAjaxView.as_view(), name='agreement_formula_pricing_sublist_ajax'),
    path('data_management/fuel_agreements/<int:pk>/discount_pricing/',
         AgreementDiscountPricingAjaxView.as_view(), name='agreement_discount_pricing'),
    path('data_management/fuel_agreements/<int:agreement_pk>/discount_pricing/<int:pk>/pricing_sublist/',
         AgreementDiscountPricingSubListAjaxView.as_view(), name='agreement_discount_pricing_sublist_ajax'),
    path('data_management/fuel_agreements/<int:pk>/associated_fees/',
         SupplierFeesListAjaxView.as_view(), name='agreement_associated_fees'),
    path('data_management/fuel_agreements/<int:agreement_pk>/associated_fees/<int:pk>/fee_sublist/',
         SupplierFeesSubListAjaxView.as_view(), name='associated_fees_sublist_ajax'),
    path('data_management/fuel_agreements/<int:pk>/associated_taxes/',
         SupplierTaxesListAjaxView.as_view(), name='agreement_associated_taxes'),
    path('data_management/fuel_agreements/<int:agreement_pk>/associated_taxes/<int:pk>/tax_sublist/',
         SupplierTaxesSubListAjaxView.as_view(), name='associated_taxes_sublist_ajax'),

    path('data_management/fuel_agreements/formula_pricing/<int:pk>/',
         AgreementFormulaPricingDetailsView.as_view(), name='agreement_formula_pricing_details'),
    path('data_management/fuel_agreements/<int:agreement_pk>/formula_pricing/create/',
         AgreementFormulaPricingCreateView.as_view(), name='agreement_formula_pricing_create'),
    path('data_management/fuel_agreements/<int:agreement_pk>/formula_pricing/<int:pk>/edit/',
         AgreementFormulaPricingEditView.as_view(), name='agreement_formula_pricing_edit'),
    path('data_management/fuel_agreements/formula_pricing/<int:pk>/delete/',
         AgreementFormulaPricingDeleteView.as_view(), name='agreement_formula_pricing_delete'),

    path('data_management/fuel_agreements/formula_pricing/volume_ratio/',
         DefaultVolumeConversionRateAjaxView.as_view(), name='default_volume_conversion_ratio'),

    path('data_management/fuel_agreements/discount_pricing/<int:pk>/',
         AgreementDiscountPricingDetailsView.as_view(), name='agreement_discount_pricing_details'),
    path('data_management/fuel_agreements/<int:agreement_pk>/discount_pricing/create/',
         AgreementDiscountPricingCreateView.as_view(), name='agreement_discount_pricing_create'),
    path('data_management/fuel_agreements/<int:agreement_pk>/discount_pricing/<int:pk>/edit/',
         AgreementDiscountPricingEditView.as_view(), name='agreement_discount_pricing_edit'),
    path('data_management/fuel_agreements/discount_pricing/<int:pk>/delete/',
         AgreementDiscountPricingDeleteView.as_view(), name='agreement_discount_pricing_delete'),

    # Agreement pricing supersede view (shared for formula and discount pricing)
    path('data_management/fuel_agreement/<int:pk>/pricing/supersede/',
        AgreementPricingSupersedeView.as_view(), name='agreement_pricing_supersede'),

    path('data_management/fuel_agreements/<int:agreement_pk>/supplier_fee/<int:pk>/details/',
         SupplierFeeDetailsView.as_view(), name='agreement_supplier_fee_details'),
    path('data_management/fuel_agreements/<int:agreement_pk>/supplier_fee/create/',
         SupplierFeesCreateView.as_view(), name='agreement_supplier_fee_create'),
    path('data_management/fuel_agreements/<int:agreement_pk>/supplier_fee/<int:pk>/edit/',
         SupplierFeeEditView.as_view(), name='agreement_supplier_fee_edit'),
    path('data_management/fuel_agreements/supplier_fee/<int:pk>/archive/',
         SupplierFeeArchiveView.as_view(), name='agreement_supplier_fee_archive'),
    path('data_management/fuel_agreements/<int:agreement_pk>/supplier_fee/<int:pk>/supersede/',
         SupplierFeeSupersedeView.as_view(), name='agreement_supplier_fee_supersede'),

    path('data_management/fuel_agreements/<int:pk>/supplier_fee/supersede/',
         SupplierFeesSupersedeView.as_view(), name='agreement_supplier_fees_supersede'),

    path('data_management/fuel_agreements/<int:agreement_pk>/supplier_tax/<int:pk>/details/',
         SupplierTaxDetailsView.as_view(), name='agreement_supplier_tax_details'),
    path('data_management/fuel_agreements/<int:agreement_pk>/supplier_tax/create/',
         SupplierTaxesCreateView.as_view(), name='agreement_supplier_tax_create'),
    path('data_management/fuel_agreements/<int:agreement_pk>/supplier_tax/<int:pk>/edit/',
         SupplierTaxEditView.as_view(), name='agreement_supplier_tax_edit'),
    path('data_management/fuel_agreements/supplier_tax/<int:pk>/archive/',
         SupplierTaxArchiveView.as_view(), name='agreement_supplier_tax_archive'),

    path('data_management/fuel_agreements/<int:pk>/supplier_tax/supersede/',
         SupplierTaxesSupersedeView.as_view(), name='agreement_supplier_tax_supersede'),

    # Fuel Pricing Indices

    path('data_management/fuel_pricing_indices/', FuelPricingIndicesListView.as_view(), name='fuel_pricing_indices'),
    path('data_management/fuel_indices_ajax/',
         FuelIndicesListAjaxView.as_view(), name='fuel_indices_ajax'),
    path('data_management/fuel_pricing_indices/create/',
         FuelIndexCreateView.as_view(), name='fuel_index_create'),
    path('data_management/fuel_pricing_indices/<int:pk>/',
         FuelIndexDetailsView.as_view(), name='fuel_index_details'),
    path('data_management/fuel_pricing_indices/<int:pk>/edit/',
         FuelIndexEditView.as_view(), name='fuel_index_edit'),
    path('data_management/fuel_pricing_indices/<int:pk>/delete/',
         FuelIndexDeleteView.as_view(), name='fuel_index_delete'),
    path('data_management/fuel_pricing_indices/<int:pk>/pricing/',
         FuelIndexPricingListAjaxView.as_view(), name='fuel_index_pricing_ajax'),
    path('data_management/fuel_pricing_indices/<int:index_pk>/pricing/sublist/<int:pk>',
         FuelIndexPricingSubListAjaxView.as_view(), name='fuel_index_pricing_sublist_ajax'),
    path('data_management/fuel_pricing_indices/<int:index_pk>/pricing/create/',
         FuelIndexPricingCreateView.as_view(), name='fuel_index_pricing_create'),
    path('data_management/fuel_pricing_indices/pricing/<int:pk>/edit/',
         FuelIndexPricingEditView.as_view(), name='fuel_index_pricing_edit'),
    path('data_management/fuel_pricing_indices/pricing/<int:pk>/supersede/',
         FuelIndexPricingSupersedeView.as_view(), name='fuel_index_pricing_supersede'),
    path('data_management/fuel_pricing_indices/pricing/<int:pk>/delete/',
         FuelIndexPricingDeleteView.as_view(), name='fuel_index_pricing_delete'),
    path('data_management/fuel_pricing_indices/pricing/<int:pk>/publish/',
         FuelIndexPricingPublishView.as_view(), name='fuel_index_pricing_publish'),
    path('data_management/fuel_pricing_indices/pricing/<int:pk>/unpublish/',
         FuelIndexPricingPublishView.as_view(), name='fuel_index_pricing_unpublish'),
    path('data_management/fuel_pricing_indices/<int:pk>/associated_agreement_pricing/',
         FuelIndexAgreementPricingListAjaxView.as_view(), name='index_pricing_associated_agreement_pricing_ajax'),
    path('data_management/fuel_pricing_indices/<int:index_pk>/associated_agreement_pricing/<int:pk>/',
         FuelIndexAgreementPricingListSubListAjaxView.as_view(),
         name='index_pricing_associated_agreement_pricing_sublist_ajax'),

    # Market Fuel Pricing

    path('data_management/fuel_pricing_market_documents_ajax/',
         FuelPricingMarketPldListAjaxView.as_view(), name='fuel_pricing_market_documents_ajax'),
    path('data_management/fuel_pricing_market_documents/',
         FuelPricingMarketPldListView.as_view(), name='fuel_pricing_market_documents'),
    path('data_management/fuel_pricing_market_document/<int:pk>/supersede/pricing/',
         FuelPricingMarketPldSupersedeFuelPricingView.as_view(),
         name='fuel_pricing_market_documents_supersede_pricing'),
    path('data_management/fuel_pricing_market_document/<int:pk>/supersede/supplier_defined_taxes/',
         SupplierTaxesSupersedeView.as_view(),
         name='fuel_pricing_market_documents_supersede_supplier_taxes'),
    path('data_management/fuel_pricing_market_document/<int:pk>/publication_status/<str:action>/',
         FuelPricingMarketAlterPublicationStatus.as_view(),
         name='fuel_pricing_market_documents_alter_publication_status'),
    path('data_management/fuel_pricing_market_document/create/',
         FuelPricingMarketPldCreateView.as_view(), name='fuel_pricing_market_documents_create'),
    path('data_management/fuel_pricing_market_document/<int:pk>/',
         FuelPricingMarketPldDetailsView.as_view(), name='fuel_pricing_market_document_details'),
    path('data_management/fuel_pricing_market_document/<int:pk>/edit/',
         FuelPricingMarketPldEditView.as_view(), name='fuel_pricing_market_documents_edit'),
    path('data_management/fuel_pricing_market_document/<int:pk>/add_document/',
         FuelPricingMarketPldDocumentCreateView.as_view(), name='fuel_pricing_market_documents_document_create'),
    path('data_management/fuel_pricing_market_document/<int:pk>/delete_document/',
         FuelPricingMarketPldDocumentDeleteView.as_view(), name='fuel_pricing_market_documents_document_delete'),
    path('data_management/fuel_pricing_market_document/<int:pk>/documents/',
         FuelPricingMarketPldDocumentListAjaxView.as_view(), name='fuel_pricing_market_documents_document_ajax'),
    path('data_management/fuel_pricing_market_document/<int:pk>/pricing_list/',
         FuelPricingMarketFuelPricingListAjaxView.as_view(),
         name='fuel_pricing_market_documents_fuel_pricing_list_ajax'),
    path('data_management/fuel_pricing_market_document/<int:pk>/pricing_sublist/',
         FuelPricingMarketFuelPricingSubListAjaxView.as_view(),
         name='fuel_pricing_market_documents_fuel_pricing_sublist_ajax'),
    path('data_management/fuel_pricing_market_document/<int:pk>/fuel_pricing/create/',
         FuelPricingMarketFuelPricingCreateView.as_view(), name='fuel_pricing_market_documents_pricing_create_page'),
    path('data_management/fuel_pricing_market_document/fuel_pricing/<int:pk>/details/',
         FuelPricingMarketFuelPricingDetailsView.as_view(), name='fuel_pricing_market_documents_pricing_details'),
    path('data_management/fuel_pricing_market_document/<int:pld>/fuel_pricing/<int:pk>/edit/',
         FuelPricingMarketFuelPricingEditView.as_view(), name='fuel_pricing_market_documents_pricing_edit'),
    path('data_management/fuel_pricing_market_document/fuel_pricing/<int:pk>/delete/',
         FuelPricingMarketFuelPricingArchiveView.as_view(), name='fuel_pricing_market_documents_fuel_pricing_archive'),

    path('data_management/fuel_pricing_market_document/<int:pk>/associated_fees_list/',
         FuelPricingMarketAssociatedFeesListAjaxView.as_view(),
         name='fuel_pricing_market_documents_associated_fee_list_ajax'),
    path('data_management/fuel_pricing_market_document/<int:pk>/associated_fee_sublist/',
         FuelPricingMarketAssociatedFeesSubListAjaxView.as_view(),
         name='fuel_pricing_market_documents_associated_fee_sublist_ajax'),

    path('data_management/fuel_pricing_market_document/<int:pk>/associated_fee/create/',
         SupplierFeesCreateView.as_view(),
         name='fuel_pricing_market_documents_associated_fees_create_page'),
    path('data_management/fuel_pricing_market_document/<int:pld>/fuel_fee/<int:pk>/details/',
         SupplierFeeDetailsView.as_view(),
         name='fuel_pricing_market_documents_associated_fee_details'),
    path('data_management/fuel_pricing_market_document/<int:pld>/fuel_fee/<int:pk>/edit/',
         SupplierFeeEditView.as_view(), name='fuel_pricing_market_documents_associated_fee_edit'),
    path('data_management/fuel_pricing_market_document/<int:pld>/fuel_fee/<int:pk>/supersede/',
         SupplierFeeSupersedeView.as_view(),
         name='fuel_pricing_market_documents_supersede_associated_fee'),
    path('data_management/fuel_pricing_market_document/fuel_fee/<int:pk>/archive/',
         SupplierFeeArchiveView.as_view(),
         name='fuel_pricing_market_documents_associated_fee_archive'),

    path('data_management/fuel_pricing_market_document/<int:pk>/supersede/associated_fees/',
         SupplierFeesSupersedeView.as_view(),
         name='fuel_pricing_market_documents_supersede_associated_fees'),

    path('data_management/fuel_pricing_market_document/<int:pk>/supplier_defined_taxes_list/',
         FuelPricingMarketSupplierDefinedTaxesListAjaxView.as_view(),
         name='fuel_pricing_market_documents_supplier_defined_tax_list_ajax'),
    path('data_management/fuel_pricing_market_document/<int:pk>/supplier_defined_taxes_sublist/',
         FuelPricingMarketSupplierDefinedTaxesSubListAjaxView.as_view(),
         name='fuel_pricing_market_documents_supplier_defined_tax_sublist_ajax'),

    # Some supplier tax logic shared between market and agreement pricing to reduce duplication
    path('data_management/fuel_pricing_market_document/<int:pk>/supplier_defined_tax/create/',
         SupplierTaxesCreateView.as_view(),
         name='fuel_pricing_market_documents_supplier_defined_tax_create_page'),
    path('data_management/fuel_pricing_market_document/<int:pld>/supplier_defined_tax/<int:pk>/details/',
         SupplierTaxDetailsView.as_view(),
         name='fuel_pricing_market_documents_supplier_defined_tax_details'),
    path('data_management/fuel_pricing_market_document/<int:pld>/supplier_defined_tax/<int:pk>/edit/',
         SupplierTaxEditView.as_view(),
         name='fuel_pricing_market_documents_supplier_defined_tax_edit'),
    path('data_management/fuel_pricing_market_document/supplier_defined_tax/<int:pk>/archive/',
         SupplierTaxArchiveView.as_view(),
         name='fuel_pricing_market_documents_supplier_defined_tax_archive'),

    # Billable Organisations
    path('data_management/fuel_pricing_market_document/<int:pk>/billable_organisations/',
         FuelPricingMarketPldBillableOrganisationsListAjaxView.as_view(),
         name='fuel_pricing_market_pld_billable_organisations_list_ajax'),
    path('data_management/fuel_pricing_market_document/<int:pk>/billable_organisations/edit/',
         FuelPricingMarketPldBillableOrganisationsEditView.as_view(),
         name='fuel_pricing_market_pld_billable_organisations_edit'),

    # Official Taxes

    # Country Tax List
    path('data_management/official_taxes_ajax/',
         OfficialTaxesListAjaxView.as_view(), name='official_taxes_ajax'),
    path('data_management/official_taxes/',
         OfficialTaxesListView.as_view(), name='official_taxes'),
    path('data_management/official_taxes/<int:pk>/children/',
         OfficialTaxesChildrenListAjaxView.as_view(), name='official_taxes_children_ajax'),
    path('data_management/official_taxes/country/<int:pk>/choose_tax_creation_form/',
         OfficialTaxesTaxCreationChoiceView.as_view(), name='tax_creation_choice'),
    # Specific Country Tax List
    path('data_management/official_taxes/country/<int:pk>/',
         SpecificCountryTaxListView.as_view(), name='specific_country_tax_list'),
    path('data_management/official_taxes/country/<int:pk>/country_tax_list_ajax/',
         CountryTaxListAjaxView.as_view(), name='country_tax_list_ajax'),
    path('data_management/official_taxes/country/<int:pk>/country_tax_sublist_ajax/',
         CountryTaxSubListAjaxView.as_view(), name='country_tax_sublist_ajax'),
    path('data_management/official_taxes/country/<int:pk>/regional_tax_list_ajax/',
         RegionalTaxListAjaxView.as_view(), name='regional_tax_list_ajax'),
    path('data_management/official_taxes/country/<int:pk>/airport_tax_list_ajax/',
         AirportTaxListAjaxView.as_view(), name='airport_tax_list_ajax'),
    path('data_management/official_taxes/country/<int:country>/<str:type>_tax/<int:pk>/details/',
         TaxDetailsView.as_view(), name='tax_rule_details'),
    path('data_management/official_taxes/country/<int:pk>/create_<str:type>_tax/',
         TaxCreateView.as_view(), name='tax_rule_create'),
    path('data_management/official_taxes/country/<int:country>/edit_<str:type>_tax/<int:pk>/',
         TaxEditView.as_view(), name='tax_rule_edit'),
    path('data_management/official_taxes/country/<int:country>/tax/<int:pk>/delete/',
         TaxRuleDeleteView.as_view(), name='tax_rule_delete'),

    # Supplier Fuel Cost Calculation

    path('suppliers/fuel_cost_estimate/', FuelPricingCalculationView.as_view(),
         name='supplier_fuel_cost_estimate'),
    path('data_management/fuel_pricing/<str:key>/', FuelPricingCalculationDetailsView.as_view(),
         name='fuel_pricing_calculation_details'),

    # Unit conversion
    path('data_management/fuel_pricing/utils/apply_supplier_exchange_rate/',
         ApplySupplierExchangeRateAjaxView.as_view(), name='apply_supplier_exchange_rate'),

    # CSV Importer
    path('data_management/fuel_market_pricing_import/',
         FuelPricingMarketCsvImporterView.as_view(), name='fuel_market_pricing_csv_importer')
]
