# Generated by Django 4.0.3 on 2022-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DLAContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_reference', models.CharField(max_length=50, verbose_name='Contract Reference')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('early_termination_date', models.DateField(null=True, verbose_name='Early Termination Date')),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
            ],
            options={
                'db_table': 'organisations_dla_contracts',
                'managed': False,
            },
        ),
    ]
