# Generated by Django 4.0.3 on 2022-09-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlacontract',
            options={'managed': False, 'permissions': [('view_dla_scraper', 'Can view DLA scraper logs')]},
        ),
    ]
