# Generated by Django 4.0.3 on 2022-09-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0003_dlasuppliername'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlacontract',
            options={'managed': False, 'permissions': [('view_dla_scraper', 'Can view DLA scraper logs'), ('run_dla_scraper', 'Can run DLA scraper')]},
        ),
    ]
