# Generated by Django 4.0.3 on 2022-09-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0091_dlacontractlocation_and_more'),
        ('dla_scraper', '0004_alter_dlacontract_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlasuppliername',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dla_supplier_names', to='organisation.organisation', verbose_name='Supplier'),
        ),
    ]
