# Generated by Django 4.0.3 on 2022-09-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0005_alter_dlasuppliername_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLAScraperRunStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Status Code')),
            ],
            options={
                'db_table': 'dla_scraper_run_status_types',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='dlasuppliername',
            options={'managed': True, 'ordering': ['id'], 'permissions': [('reconcile_dla_name', 'Can reconcile DLA names')]},
        ),
        migrations.CreateModel(
            name='DLAScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True, verbose_name='Run at')),
                ('log', models.TextField(blank=True, null=True, verbose_name='Run Log')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='runs_with_status', to='dla_scraper.dlascraperrunstatus', verbose_name='Run Status')),
            ],
            options={
                'db_table': 'dla_scraper_run_log',
                'ordering': ['run_at'],
                'managed': True,
            },
        ),
    ]
