# Generated by Django 4.0.3 on 2022-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0006_dlascraperrunstatus_alter_dlasuppliername_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlascraperrun',
            name='log',
            field=models.JSONField(blank=True, null=True, verbose_name='Run Log'),
        ),
    ]
