# Generated by Django 4.0.3 on 2022-09-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0007_alter_dlascraperrun_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlascraperrun',
            options={'managed': True, 'ordering': ['-run_at']},
        ),
    ]
