# Generated by Django 4.0.3 on 2022-09-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0009_dlalocationalternativeicaocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlascraperrun',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='Was a scheduled run?'),
        ),
    ]
