# Generated by Django 4.0.3 on 2022-09-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0010_dlascraperrun_is_scheduled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlacontract',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='dlacontract',
            table=None,
        ),
    ]
