# Generated by Django 4.0.3 on 2022-10-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0097_dlacontractlocation_expiring_email_sent'),
        ('dla_scraper', '0011_alter_dlacontract_options_alter_dlacontract_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLAScraperPendingOrganisationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ipa', models.BooleanField(default=False, verbose_name='Is an IPA?')),
                ('ignored', models.BooleanField(default=False, verbose_name='Ignored?')),
                ('applied', models.BooleanField(default=False, verbose_name='Applied?')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates_for_contract', to='organisation.dlacontractlocation', verbose_name='Contract')),
                ('current_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates_where_current', to='organisation.organisation', verbose_name='Current organisation')),
                ('proposed_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates_where_proposed', to='organisation.organisation', verbose_name='Proposed organisation')),
            ],
            options={
                'db_table': 'organisations_dla_pending_organisation_updates',
                'managed': True,
            },
        ),
    ]
