# Generated by Django 4.0.3 on 2022-10-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dla_scraper', '0012_dlascraperpendingorganisationupdates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlascraperpendingorganisationupdate',
            options={'managed': True, 'ordering': ['id']},
        ),
    ]
