# Generated by Django 4.0.3 on 2022-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('icon', models.CharField(max_length=10, verbose_name='Icon')),
            ],
            options={
                'db_table': 'crm_activities',
            },
        ),
    ]
