# Generated by Django 4.0.3 on 2022-04-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0080_alter_organisation_options_and_more'),
        ('user', '0019_alter_persondetails_contact_phone'),
        ('crm', '0002_organisationpeopleactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpeopleactivity',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='organisationpeopleactivity',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.person', verbose_name='Person'),
        ),
    ]
