# Generated by Django 4.0.3 on 2022-11-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0098_ipalocation_location_email_and_more'),
        ('user', '0024_user_last_token_sent_at'),
        ('pricing', '0015_supplierfuelfeerate_source_agreement'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierFuelAgreement',
            new_name='FuelAgreement',
        ),
    ]
