# Generated by Django 4.0.3 on 2022-11-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_rename_supplierfuelagreement_fuelagreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelagreement',
            name='comment',
        ),
    ]
