# Generated by Django 4.0.3 on 2023-01-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_last_token_sent_at'),
        ('supplier', '0003_remove_fuelagreement_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelagreement',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='fuelagreement',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published?'),
        ),
        migrations.AddField(
            model_name='fuelagreement',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Is Reviewed?'),
        ),
        migrations.CreateModel(
            name='FuelAgreementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(verbose_name='Assigned At')),
                ('reviewed_at', models.DateTimeField(null=True, verbose_name='Reviewed At')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_fuel_agreement_reviews', to='user.person', verbose_name='Assigned To')),
                ('fuel_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='supplier.fuelagreement', verbose_name='Fuel Agreement')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviewed_fuel_agreement_reviews', to='user.person', verbose_name='Reviewed By')),
            ],
            options={
                'db_table': 'suppliers_fuel_agreements_reviews',
            },
        ),
        migrations.AddField(
            model_name='fuelagreement',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='supplier.fuelagreementreview', verbose_name='Review'),
        ),
    ]
