# Generated by Django 4.0.3 on 2023-01-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_rename_active_fuelagreement_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreement',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supplier.fuelagreementreview', verbose_name='Review'),
        ),
    ]
