# Generated by Django 4.0.3 on 2023-01-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_fuelagreement_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreement',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='supplier.fuelagreementreview', verbose_name='Review'),
        ),
    ]
