# Generated by Django 4.0.3 on 2023-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_alter_fuelagreement_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelagreementreview',
            old_name='fuel_agreement',
            new_name='suppliers_fuel_agreement',
        ),
        migrations.AddField(
            model_name='fuelagreement',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment'),
        ),
    ]
