# Generated by Django 4.0.3 on 2023-06-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('supplier', '0007_rename_fuel_agreement_fuelagreementreview_suppliers_fuel_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreement',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisationdocument', verbose_name='Document'),
        ),
    ]
