# Generated by Django 4.0.3 on 2023-07-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_alter_fuelagreement_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreement',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End Date'),
        ),
    ]
