# Generated by Django 4.0.3 on 2023-07-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0012_fuelagreement_superseded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelagreement',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Voided At'),
        ),
    ]
