# Generated by Django 4.0.3 on 2023-08-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0108_merge_20230608_1617'),
        ('supplier', '0014_alter_fuelagreement_superseded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelagreement',
            name='is_prepayment',
            field=models.BooleanField(default=False, verbose_name='Is Prepayment?'),
        ),
        migrations.AlterField(
            model_name='fuelagreement',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'details__type_id__in': [2, 3, 4, 5, 7, 8, 13, 14]}, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_where_supplier', to='organisation.organisation', verbose_name='Supplier'),
        ),
    ]
