# Generated by Django 4.0.3 on 2023-08-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20230807_1403'),
        ('supplier', '0015_fuelagreement_is_prepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
            ],
            options={
                'permissions': [('p_view', 'Data Management: View Fuel Indices, Fuel Agreements, Agreement and Market Pricing'), ('p_create', 'Data Management: Create Fuel Indices, Fuel Agreements, Agreement and Market Pricing'), ('p_update', 'Data Management: Update Fuel Indices, Fuel Agreements, Agreement and Market Pricing'), ('p_moderate', 'Data Management: Review Created Supplier Fuel Agreements and Pricing - Acceptance Review'), ('p_publish', 'Data Management: (Un-)Publish Fuel Indices, Fuel Agreements, Agreement and Market Pricing')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.globalconfiguration',),
        ),
    ]
