# Generated by Django 4.0.3 on 2023-08-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0016_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('p_view', 'Suppliers: view'), ('p_create', 'Suppliers: create'), ('p_update', 'Suppliers: update')]},
        ),
    ]
