# Generated by Django 4.0.3 on 2023-09-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0109_alter_operatorpreferredgroundhandler_ground_handler_and_more'),
        ('supplier', '0017_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreement',
            name='supplier',
            field=models.ForeignKey(limit_choices_to=models.Q(('details__type_id__in', [2, 3, 4, 5, 7, 8, 13, 14]), ('airport_details__isnull', False), ('handler_details__isnull', False), ('ipa_details__isnull', False), ('oilco_details__isnull', False), ('service_provider_locations__isnull', False), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='agreements_where_supplier', to='organisation.organisation', verbose_name='Supplier'),
        ),
    ]
