# Generated by Django 4.2.6 on 2023-12-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_commentreadstatus'),
        ('supplier', '0019_fuelagreement_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelagreement',
            name='deposit_required',
            field=models.BooleanField(default=False, verbose_name='Deposit Required?'),
        ),
        migrations.AddField(
            model_name='fuelagreement',
            name='deposit_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.currency', verbose_name='Deposit Currency'),
        ),
        migrations.AddField(
            model_name='fuelagreement',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Deposit Amount'),
        ),
    ]
