# Generated by Django 4.2.6 on 2023-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0020_fuelagreement_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelagreement',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deposit Amount'),
        ),
    ]
