# Generated by Django 3.2.9 on 2022-01-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADS_Aircraft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(max_length=35, null=True, verbose_name='ASN')),
                ('ads_asn', models.CharField(max_length=50, null=True, verbose_name='ADS ASN')),
                ('pax_seats', models.IntegerField(null=True, verbose_name='Pax Seats')),
                ('yom', models.IntegerField(null=True, verbose_name='YOM')),
                ('source', models.CharField(default='AML', max_length=6, verbose_name='Source')),
                ('is_decommissioned', models.BooleanField(default=False, verbose_name='Decommissioned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('details_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'aircraft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADS_AircraftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=50, verbose_name='Registration')),
                ('operator_id', models.BigIntegerField(null=True)),
                ('change_effective_date', models.DateField(verbose_name='Change Date')),
                ('source', models.CharField(max_length=6, verbose_name='Source')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('created_by', models.IntegerField(verbose_name='Created by')),
            ],
            options={
                'db_table': 'aircraft_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADS_AircraftType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(db_column='type_designator', max_length=4, verbose_name='ICAO Type')),
                ('manufacturer', models.CharField(db_column='type_manufacturer', max_length=40, verbose_name='Manufacturer')),
                ('model', models.CharField(db_column='type_model', max_length=50, verbose_name='Model')),
                ('category', models.CharField(max_length=40, verbose_name='Category')),
            ],
            options={
                'db_table': 'aircraft_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADS_Airport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('icao_code', models.CharField(max_length=4, unique=True, verbose_name='ICAO Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='IATA Code')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('maximum_weight', models.IntegerField(verbose_name='Maximum Weight')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('has_structures', models.BooleanField(default=False, verbose_name='Has Pricing')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.IntegerField(verbose_name='Updated by')),
            ],
            options={
                'db_table': 'airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADS_AirportMaxWeightUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'airports_max_weight_units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADS_Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('continent', models.CharField(max_length=2, verbose_name='Continent')),
                ('currency_code', models.CharField(max_length=50, verbose_name='Code')),
                ('in_eu', models.BooleanField(default=False, verbose_name='In EU?')),
                ('in_schengen', models.BooleanField(default=False, verbose_name='In Schengen?')),
                ('in_eea', models.BooleanField(default=False, verbose_name='In EAA?')),
                ('in_cemac', models.BooleanField(default=False, verbose_name='In CEMAC?')),
                ('in_ecowas', models.BooleanField(default=False, verbose_name='In ECOWAS?')),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADS_Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=3, verbose_name='Code')),
                ('currency_name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'currencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ADS_Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
    ]
