# Generated by Django 4.0.3 on 2023-05-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='apacs_url',
            field=models.URLField(blank=True, null=True, verbose_name='APACS Number'),
        ),
    ]
