# Generated by Django 4.0.3 on 2023-05-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0081_alter_handlingrequestmovement_airport'),
        ('core', '0035_alter_activitylog_data'),
        ('mission', '0002_mission_apacs_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionLegServicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_quantity', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Fuel Quantity')),
                ('fuel_prist_required', models.BooleanField(default=False, verbose_name='Prist Required')),
                ('fuel_required', models.ForeignKey(blank=True, db_column='fuel_required_on', null=True, on_delete=django.db.models.deletion.RESTRICT, to='handling.movementdirection', verbose_name='Fuel Required')),
                ('fuel_unit', models.ForeignKey(blank=True, limit_choices_to={'is_fluid_uom': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Fuel Unit')),
            ],
            options={
                'db_table': 'missions_legs_servicing',
            },
        ),
        migrations.AlterModelOptions(
            name='missionleg',
            options={'ordering': ['mission', 'sequence_id']},
        ),
        migrations.AddField(
            model_name='missionleg',
            name='previous_leg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_leg', to='mission.missionleg', verbose_name='Previous Leg'),
        ),
        migrations.CreateModel(
            name='MissionLegServicingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_arrival', models.BooleanField(default=False, verbose_name='On Arrival')),
                ('on_departure', models.BooleanField(default=False, verbose_name='On Departure')),
                ('mission_leg_servicing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_services', to='mission.missionlegservicing', verbose_name='MissionLegServicing')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_leg_servicing', to='handling.handlingservice', verbose_name='Service')),
            ],
            options={
                'db_table': 'missions_legs_servicing_services',
            },
        ),
        migrations.AddField(
            model_name='missionlegservicing',
            name='mission_leg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicing', to='mission.missionleg', verbose_name='Mission Leg'),
        ),
    ]
