# Generated by Django 4.0.3 on 2023-05-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0081_alter_handlingrequestmovement_airport'),
        ('mission', '0003_missionlegservicing_alter_missionleg_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionlegservicing',
            name='handling_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_leg_servicing', to='handling.handlingrequest', verbose_name='Handling Request'),
        ),
    ]
