# Generated by Django 4.0.3 on 2023-06-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_activitylog_mission'),
        ('mission', '0004_missionlegservicing_handling_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='air_card_prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aircardprefix', verbose_name='AIR Card Prefix'),
        ),
        migrations.AddField(
            model_name='missionleg',
            name='air_card_prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aircardprefix', verbose_name='AIR Card Prefix'),
        ),
    ]
