# Generated by Django 4.0.3 on 2023-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_alter_mission_air_card_expiration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionLegCancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'db_table': 'missions_legs_cancellation_reasons',
            },
        ),
    ]
