# Generated by Django 4.0.3 on 2023-06-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_missionlegcancellationreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionleg',
            name='cancellation_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='mission.missionlegcancellationreason', verbose_name='Cancellation Reason'),
        ),
    ]
