# Generated by Django 4.0.3 on 2023-06-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0008_missionleg_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_amended_callsign',
            field=models.BooleanField(default=False, verbose_name='Is Callsign Amended?'),
        ),
    ]
