# Generated by Django 4.0.3 on 2023-07-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0084_merge_20230601_1759'),
        ('mission', '0010_alter_mission_aircraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionleg',
            name='crew',
        ),
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='handling.handlingrequesttype', verbose_name='Mission Type'),
        ),
        migrations.DeleteModel(
            name='MissionLegCrew',
        ),
    ]
