# Generated by Django 4.0.3 on 2023-07-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0084_merge_20230601_1759'),
        ('user', '0028_alter_traveldocument_number_and_more'),
        ('mission', '0011_remove_missionleg_crew_alter_mission_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionCrewPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='Primary Mission Contact')),
                ('can_update_mission', models.BooleanField(default=False, verbose_name='Can Update Mission?')),
            ],
            options={
                'db_table': 'missions_crew_people',
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='crew',
            field=models.ManyToManyField(related_name='crew_missions', through='mission.MissionCrewPosition', to='user.person', verbose_name='Mission Crew'),
        ),
        migrations.CreateModel(
            name='MissionLegCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_legs_crew', to='mission.missioncrewposition', verbose_name='Crew Member')),
                ('mission_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='mission.missionleg', verbose_name='Mission Leg')),
            ],
            options={
                'db_table': 'missions_crew_legs',
            },
        ),
        migrations.AddField(
            model_name='missioncrewposition',
            name='legs',
            field=models.ManyToManyField(related_name='crew_positions', through='mission.MissionLegCrew', to='mission.missionleg', verbose_name='Mission Leg'),
        ),
        migrations.AddField(
            model_name='missioncrewposition',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_crew_positions', to='mission.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='missioncrewposition',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_crew_positions', to='user.person', verbose_name='Crew Member'),
        ),
        migrations.AddField(
            model_name='missioncrewposition',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='handling.handlingrequestcrewmemberposition', verbose_name='Position'),
        ),
    ]
