# Generated by Django 4.0.3 on 2023-07-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0012_missioncrewposition_mission_crew_missionlegcrew_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionLegCrew',
            new_name='MissionCrewPositionLeg',
        ),
    ]
