# Generated by Django 4.0.3 on 2023-07-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0013_rename_missionlegcrew_missioncrewpositionleg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missioncrewposition',
            name='legs',
            field=models.ManyToManyField(blank=True, null=True, related_name='crew_positions', through='mission.MissionCrewPositionLeg', to='mission.missionleg', verbose_name='Mission Leg'),
        ),
    ]
