# Generated by Django 4.0.3 on 2023-07-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0016_missionlegservicingservice_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionlegcargopayload',
            old_name='flight_leg',
            new_name='mission_leg',
        ),
        migrations.RenameField(
            model_name='missionlegpassengerspayload',
            old_name='flight_leg',
            new_name='mission_leg',
        ),
    ]
