# Generated by Django 4.0.3 on 2023-07-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0106_organisationpeople_is_authorising_person_and_more'),
        ('mission', '0017_rename_flight_leg_missionlegcargopayload_mission_leg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionleg',
            name='arrival_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_mission_legs', to='organisation.organisation', verbose_name='Arrival Location'),
        ),
        migrations.AlterField(
            model_name='missionleg',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_mission_legs', to='organisation.organisation', verbose_name='Departure Location'),
        ),
    ]
