# Generated by Django 4.0.3 on 2023-07-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0084_merge_20230601_1759'),
        ('core', '0038_activitylog_mission_leg'),
        ('mission', '0018_alter_missionleg_arrival_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionLegServicing',
            new_name='MissionTurnaround',
        ),
    ]
