# Generated by Django 4.0.3 on 2023-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0019_rename_missionlegservicing_missionturnaround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionleg',
            name='cob_lbs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cargo Payload'),
        ),
        migrations.AlterField(
            model_name='missionleg',
            name='pob_pax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Passengers on Board'),
        ),
    ]
