# Generated by Django 4.0.3 on 2023-08-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0088_migrate_amendments_to_activity_log'),
        ('aircraft', '0018_aircraftdesignator_aircrafttype_type_designator'),
        ('core', '0045_alter_activitylog_record_slug_and_more'),
        ('mission', '0020_alter_missionleg_cob_lbs_alter_missionleg_pob_pax'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionleg',
            name='aircraft_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_flight_legs', to='aircraft.aircrafthistory', verbose_name='Tail Number'),
        ),
        migrations.AlterField(
            model_name='missioncrewposition',
            name='legs',
            field=models.ManyToManyField(related_name='crew_positions', through='mission.MissionCrewPositionLeg', to='mission.missionleg', verbose_name='Mission Leg'),
        ),
        migrations.AlterField(
            model_name='missionleg',
            name='air_card_prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aircardprefix', verbose_name='AIR Card Prefix'),
        ),
        migrations.AlterField(
            model_name='missionleg',
            name='arrival_sf_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_mission_legs', to='handling.handlingrequest', verbose_name='Arrival SFR'),
        ),
        migrations.AlterField(
            model_name='missionleg',
            name='cancellation_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='mission.missionlegcancellationreason', verbose_name='Cancellation Reason'),
        ),
        migrations.AlterField(
            model_name='missionleg',
            name='departure_sf_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_mission_legs', to='handling.handlingrequest', verbose_name='Departure SFR'),
        ),
    ]
