# Generated by Django 4.0.3 on 2023-08-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0018_aircraftdesignator_aircrafttype_type_designator'),
        ('mission', '0021_missionleg_aircraft_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionleg',
            name='aircraft_type_override',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_flight_legs', to='aircraft.aircrafttype', verbose_name='Aircraft Type'),
        ),
    ]
