# Generated by Django 4.0.3 on 2023-08-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0088_migrate_amendments_to_activity_log'),
        ('mission', '0022_missionleg_aircraft_type_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionturnaround',
            name='handling_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_turnaround', to='handling.handlingrequest', verbose_name='Handling Request'),
        ),
    ]
