# Generated by Django 4.0.3 on 2023-08-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0088_migrate_amendments_to_activity_log'),
        ('core', '0045_alter_activitylog_record_slug_and_more'),
        ('mission', '0023_alter_missionturnaround_handling_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionLegServicingService',
            new_name='MissionTurnaroundService',
        ),
        migrations.AlterField(
            model_name='missionturnaround',
            name='mission_leg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turnaround', to='mission.missionleg', verbose_name='Mission Leg'),
        ),
    ]
