# Generated by Django 4.0.3 on 2023-08-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0024_rename_missionlegservicingservice_missionturnaroundservice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionturnaroundservice',
            old_name='mission_leg_servicing',
            new_name='turnaround',
        ),
    ]
