# Generated by Django 4.0.3 on 2023-08-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0088_migrate_amendments_to_activity_log'),
        ('mission', '0025_rename_mission_leg_servicing_missionturnaroundservice_turnaround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionturnaroundservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_turnarounds_services', to='handling.handlingservice', verbose_name='Service'),
        ),
    ]
