# Generated by Django 4.0.3 on 2023-08-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0018_aircraftdesignator_aircrafttype_type_designator'),
        ('mission', '0026_alter_missionturnaroundservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='aircraft.aircrafthistory', verbose_name='Tail Number'),
        ),
    ]
