# Generated by Django 4.0.3 on 2023-09-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_user_is_superuser'),
        ('mission', '0028_missionturnaroundservice_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionturnaroundservice',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.person', verbose_name='Updated By'),
        ),
    ]
