# Generated by Django 4.2.6 on 2023-10-28 16:38

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0030_missionlegcargopayload_sync_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missionlegcargopayload",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="missionlegpassengerspayload",
            options={"ordering": ["id", "identifier"]},
        ),
        migrations.AlterField(
            model_name="missionlegcargopayload",
            name="sync_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="missionlegpassengerspayload",
            name="sync_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.CreateModel(
            name="MissionStatusFlags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_sfr",
                    models.BooleanField(
                        default=False, verbose_name="Has Any S&F Request"
                    ),
                ),
                (
                    "has_sfr_new",
                    models.BooleanField(
                        default=False, verbose_name="Has New S&F Request"
                    ),
                ),
                (
                    "has_sfr_amended",
                    models.BooleanField(
                        default=False, verbose_name="Has Amended S&F Request"
                    ),
                ),
                (
                    "has_sfr_in_progress",
                    models.BooleanField(
                        default=False, verbose_name="Has In Progress S&F Request"
                    ),
                ),
                (
                    "has_sfr_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Has Confirmed S&F Request"
                    ),
                ),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_flags",
                        to="mission.missionstatusflags",
                        verbose_name="Mission",
                    ),
                ),
            ],
            options={
                "db_table": "missions_status_details",
            },
        ),
    ]
