# Generated by Django 4.2.6 on 2023-10-28 16:45

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0031_alter_missionlegcargopayload_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionlegcargopayload",
            name="sync_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="missionlegpassengerspayload",
            name="sync_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="missionstatusflags",
            name="mission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_flags",
                to="mission.mission",
                verbose_name="Mission",
            ),
        ),
    ]
