# Generated by Django 4.2.6 on 2023-10-28 16:55

from django.db import migrations

from mission.models import Mission


def create_mission_status_flags(apps, schema):
    from mission.utils.mission_utils import calculate_mission_status_flags
    missions_to_process = Mission.objects.all()

    for mission in missions_to_process:
        calculate_mission_status_flags(mission)


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0032_alter_missionlegcargopayload_sync_id_and_more"),
    ]

    operations = [
        migrations.RunPython(create_mission_status_flags)
    ]
