# Generated by Django 4.2.6 on 2023-11-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0034_alter_missionlegcargopayload_sync_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionPassengerMissionLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers_intermediate",
                        to="mission.missionleg",
                        verbose_name="Mission Leg",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_legs_intermediate",
                        to="mission.missionlegpassengerspayload",
                        verbose_name="Crew Member",
                    ),
                ),
            ],
            options={
                "db_table": "missions_passengers_flight_legs",
            },
        ),
        migrations.AddField(
            model_name="missionlegpassengerspayload",
            name="mission_legs",
            field=models.ManyToManyField(
                related_name="passengers",
                through="mission.MissionPassengerMissionLeg",
                to="mission.missionleg",
                verbose_name="Mission Leg",
            ),
        ),
    ]
