# Generated by Django 4.2.6 on 2023-11-22 22:25

from django.db import migrations


def migrate_data(apps, schema):
    passengers_payloads_cls = apps.get_model('mission', 'MissionLegPassengersPayload')
    passengers_payloads = passengers_payloads_cls.objects.all()

    for passengers_payload in passengers_payloads:
        passengers_payload.mission_legs.add(passengers_payload.mission_leg)


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0035_missionpassengermissionleg_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
