# Generated by Django 4.2.6 on 2023-11-22 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0036_migrate_passengers_payload_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missionlegpassengerspayload",
            name="mission_leg",
        ),
    ]
