# Generated by Django 4.2.6 on 2023-11-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0037_remove_missionlegpassengerspayload_mission_leg"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionCargoMissionLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo_payload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_legs_intermediate",
                        to="mission.missionlegcargopayload",
                        verbose_name="Cargo Payload",
                    ),
                ),
                (
                    "mission_leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_intermediate",
                        to="mission.missionleg",
                        verbose_name="Mission Leg",
                    ),
                ),
            ],
            options={
                "db_table": "missions_cargo_flight_legs",
            },
        ),
        migrations.AddField(
            model_name="missionlegcargopayload",
            name="mission_legs",
            field=models.ManyToManyField(
                related_name="cargo",
                through="mission.MissionCargoMissionLeg",
                to="mission.missionleg",
                verbose_name="Mission Legs",
            ),
        ),
    ]
