# Generated by Django 4.2.6 on 2023-11-22 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0039_migrate_cargo_payload_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missionlegcargopayload",
            name="mission_leg",
        ),
    ]
