# Generated by Django 4.2.6 on 2023-11-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0033_usersettings"),
        ("mission", "0040_remove_missionlegcargopayload_mission_leg"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="mission_number_prefix",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Mission Number Prefix",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="mission_planner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planner_missions",
                to="user.person",
                verbose_name="Requesting Person",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="assigned_mil_team_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_missions",
                to="user.person",
                verbose_name="Assigned Mil Team Member",
            ),
        ),
    ]
