# Generated by Django 3.2.9 on 2022-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_personrole_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrole',
            name='is_aircraft_owner',
            field=models.BooleanField(default=False, verbose_name='Aircraft Owner'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='is_finance',
            field=models.BooleanField(default=False, verbose_name='Finance'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='is_flight_crew',
            field=models.BooleanField(default=False, verbose_name='Flight Crew'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='is_maintainer',
            field=models.BooleanField(default=False, verbose_name='Maintainer'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='is_management',
            field=models.BooleanField(default=False, verbose_name='Management'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='is_ops',
            field=models.BooleanField(default=False, verbose_name='OPS'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='is_refueller',
            field=models.BooleanField(default=False, verbose_name='Refueller'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='is_sales',
            field=models.BooleanField(default=False, verbose_name='Sales'),
        ),
    ]
