# Generated by Django 3.2.9 on 2022-03-25 01:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220129_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Contact Phone')),
                ('change_effective_date', models.DateField(auto_now_add=True, verbose_name='Change Effective Date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='user.person')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.persontitle', verbose_name='Title')),
            ],
            options={
                'db_table': 'people_history',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_current', to='user.persondetails'),
        ),
    ]
