# Generated by Django 3.2.9 on 2022-03-25 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_auto_20220325_0148'),
        ('user', '0007_auto_20220325_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ofac_api_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OFAC API ID'),
        ),
        migrations.AddField(
            model_name='persontitle',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_titles', to='organisation.organisation', verbose_name='Organisation'),
        ),
    ]
