# Generated by Django 3.2.9 on 2022-03-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_person_ofac_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='users_roles_users', help_text='The roles this user belongs to. A user will get all permissions granted to each of their roles.', related_name='user_set', related_query_name='user', to='user.Role', verbose_name='Roles'),
        ),
    ]
