# Generated by Django 3.2.9 on 2022-03-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0008_alter_aircrafthistory_homebase'),
        ('user', '0010_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aircraft_types',
            field=models.ManyToManyField(blank=True, through='user.PersonAircraftTypes', to='aircraft.AircraftType', verbose_name='Person Aircraft Types'),
        ),
    ]
