# Generated by Django 4.0.3 on 2022-04-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_personpronoun_persondetails_personal_pronoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetails',
            name='abbreviated_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviated Name'),
        ),
    ]
