# Generated by Django 4.0.3 on 2022-04-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_country_options'),
        ('user', '0013_persondetails_abbreviated_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'people_tags',
            },
        ),
        migrations.AlterModelOptions(
            name='personpronoun',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='people', through='user.PersonTag', to='core.tag'),
        ),
        migrations.AddField(
            model_name='persontag',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
        migrations.AddField(
            model_name='persontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
