# Generated by Django 4.0.3 on 2022-04-15 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_persontag_alter_personpronoun_options_person_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personrole',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890', regex='^(\\+)\\d{8,14}$')], verbose_name='Personal Phone'),
        ),
    ]
