# Generated by Django 4.0.3 on 2022-04-19 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Personal Phone'),
        ),
    ]
