# Generated by Django 4.0.3 on 2022-05-17 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_persondetails_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Direct Email'),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should start from "+", may contains spaces and brackets', regex='^(\\+?\\0?)(\\s?)+\\d(\\s?\\(?\\d\\)?){6,26}$')], verbose_name='Direct Phone'),
        ),
    ]
