# Generated by Django 4.0.3 on 2022-07-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invitation_sent',
            field=models.BooleanField(default=False, verbose_name='Is Invitation Sent?'),
        ),
    ]
