# Generated by Django 4.0.3 on 2022-10-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_is_invitation_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token_sent_at',
            field=models.DateTimeField(null=True, verbose_name='Last Password Reset Token Sent at'),
        ),
    ]
