# Generated by Django 4.0.3 on 2023-03-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_persongender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persongender',
            table='people_genders',
        ),
    ]
