# Generated by Django 4.0.3 on 2023-03-07 15:21

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pricingunit_description_short'),
        ('user', '0026_alter_persongender_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_td', models.BooleanField(default=False, verbose_name='Is TD?')),
            ],
            options={
                'db_table': 'people_documents_types',
            },
        ),
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='TD Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Dob')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('issue_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_documents_issue_country', to='core.country', verbose_name='Issue Country')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_documents_nationality', to='core.country', verbose_name='Nationality')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_documents', to='user.person', verbose_name='Person')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_documents', to='user.peopledocumenttype', verbose_name='Type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_travel_documents', to='user.person', verbose_name='Updated By')),
            ],
            options={
                'db_table': 'people_documents',
            },
        ),
        migrations.CreateModel(
            name='TravelDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=app.storage_backends.TravelDocumentFilesStorage(), upload_to='', verbose_name='File')),
                ('travel_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='user.traveldocument', verbose_name='Travel Document')),
            ],
            options={
                'db_table': 'people_documents_files',
            },
        ),
    ]
