# Generated by Django 4.0.3 on 2023-03-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_peopledocumenttype_traveldocument_traveldocumentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldocument',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='traveldocumentfile',
            name='travel_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.traveldocument', verbose_name='Travel Document'),
        ),
    ]
