# Generated by Django 4.0.3 on 2023-07-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0028_alter_traveldocument_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_forced_onboard',
            field=models.BooleanField(default=False, verbose_name='Force Onboarding'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='users_role_permissions', related_name='roles', to='auth.permission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='Superuser Permissions'),
        ),
    ]
