# Generated by Django 4.0.3 on 2023-08-02 14:37

from django.db import migrations


def migrate_data(apps, schema_editor):
    user_cls = apps.get_model('user', 'User')
    role_cls = apps.get_model('user', 'Role')

    users = user_cls.objects.raw("SELECT id FROM users WHERE is_superuser=TRUE")
    superuser_role, created = role_cls.objects.get_or_create(pk=1, defaults={'name': 'ERP Admin'})
    for user in users:
        user.roles.add(superuser_role)

    return True


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_is_forced_onboard_alter_role_permissions_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]

