# Generated by Django 4.0.3 on 2023-08-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_move_superuser_to_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
