# Generated by Django 3.2.9 on 2022-01-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('organisation', '0001_initial'),
        ('aircraft', '0003_initial'),
        ('handling', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestservices',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.person', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='handlingrequestmovement',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airport.airport', verbose_name='Airport'),
        ),
        migrations.AddField(
            model_name='handlingrequestmovement',
            name='direction',
            field=models.ForeignKey(db_column='direction_code', on_delete=django.db.models.deletion.RESTRICT, to='handling.movementdirection'),
        ),
        migrations.AddField(
            model_name='handlingrequestmovement',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to='handling.handlingrequest'),
        ),
        migrations.AddField(
            model_name='handlingrequestamendment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='handling.handlingrequest', verbose_name='Handling Request'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='aircraft_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircraft.aircrafttype', verbose_name='Aircraft Type'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airport.airport', verbose_name='Airport'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_handling_requests', to='user.person', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='customer_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_requests', to='organisation.organisation', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='customer_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_requests', to='user.person', verbose_name='Customer Person'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='fuel_required',
            field=models.ForeignKey(db_column='fuel_required_on', on_delete=django.db.models.deletion.RESTRICT, to='handling.movementdirection', verbose_name='Fuel Required'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='fuel_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Fuel Unit'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='handling_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisation', verbose_name='Handling Agent'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='ipa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipa_handling_requests', to='organisation.organisation', verbose_name='IPA'),
        ),
    ]
