# Generated by Django 3.2.9 on 2022-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='legacy_fuel_order_ipa_name',
            field=models.CharField(max_length=120, null=True, verbose_name='IPA'),
        ),
    ]
