# Generated by Django 3.2.9 on 2022-03-27 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0025_auto_20220327_0030'),
        ('handling', '0003_handlingrequest_legacy_fuel_order_ipa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_handling_requests', to='organisation.organisation', verbose_name='Airport'),
        ),
        migrations.AlterField(
            model_name='handlingrequest',
            name='handling_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handler_handling_requests', to='organisation.organisation', verbose_name='Handling Agent'),
        ),
        migrations.AlterField(
            model_name='handlingrequestmovement',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisation', verbose_name='Airport'),
        ),
        migrations.AlterField(
            model_name='handlingservice',
            name='availability',
            field=models.ManyToManyField(blank=True, through='handling.HandlingServiceAvailability', to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='handlingserviceavailability',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_availability', to='organisation.organisation', verbose_name='Airport'),
        ),
    ]
