# Generated by Django 4.0.3 on 2022-04-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0065_alter_handlerdetails_contact_phone_and_more'),
        ('handling', '0004_auto_20220327_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='airport',
            field=models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_handling_requests', to='organisation.organisation', verbose_name='Airport'),
        ),
        migrations.AlterField(
            model_name='handlingrequestmovement',
            name='airport',
            field=models.ForeignKey(limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisation', verbose_name='Airport'),
        ),
    ]
