# Generated by Django 4.0.3 on 2022-04-30 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0083_alter_organisation_options'),
        ('handling', '0005_alter_handlingrequest_airport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingServiceOrganisationSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_services', to='organisation.organisation', verbose_name='Airport')),
            ],
            options={
                'db_table': 'handling_services_organisations',
            },
        ),
        migrations.AddField(
            model_name='handlingservice',
            name='specific_to_organisations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'details__type_id': 1, 'details__type_id__in': [13, 14, 15, 16, 17], 'operator_details__isnull': False}, related_name='organisation_specific_handling_services', through='handling.HandlingServiceOrganisationSpecific', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='handlingserviceorganisationspecific',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_handling_services', to='handling.handlingservice', verbose_name='Service'),
        ),
    ]
