# Generated by Django 4.0.3 on 2022-04-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0083_alter_organisation_options'),
        ('handling', '0006_handlingserviceorganisationspecific_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingservice',
            name='availability',
            field=models.ManyToManyField(blank=True, through='handling.HandlingServiceAvailability', to='organisation.organisation', verbose_name='Applicable Airport(s)'),
        ),
        migrations.AlterField(
            model_name='handlingservice',
            name='specific_to_organisations',
            field=models.ManyToManyField(blank=True, help_text='Service usage will be locked only to selected organisations.', limit_choices_to={'details__type_id': 1, 'details__type_id__in': [13, 14, 15, 16, 17], 'operator_details__isnull': False}, related_name='organisation_specific_handling_services', through='handling.HandlingServiceOrganisationSpecific', to='organisation.organisation', verbose_name='Applicable Unit(s)'),
        ),
        migrations.AlterField(
            model_name='handlingserviceorganisationspecific',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_services', to='organisation.organisation', verbose_name='Unit'),
        ),
    ]
