# Generated by Django 4.0.3 on 2022-04-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comment_handling_service'),
        ('handling', '0007_alter_handlingservice_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingServiceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'handling_services_tags',
            },
        ),
        migrations.AddField(
            model_name='handlingservice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='handling_services', through='handling.HandlingServiceTag', to='core.tag'),
        ),
        migrations.AddField(
            model_name='handlingservicetag',
            name='handling_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.handlingservice'),
        ),
        migrations.AddField(
            model_name='handlingservicetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
