# Generated by Django 4.0.3 on 2022-04-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0008_handlingservicetag_handlingservice_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlingservice',
            old_name='specific_to_organisations',
            new_name='organisations',
        ),
    ]
