# Generated by Django 4.0.3 on 2022-05-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_persondetails_contact_phone'),
        ('handling', '0009_rename_specific_to_organisations_handlingservice_organisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestamendment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.person', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='handlingservice',
            name='always_included',
            field=models.BooleanField(default=False, help_text='This service will be automatically applied to each Fueling Request or SPF based on options below.', verbose_name='Always Included?'),
        ),
    ]
