# Generated by Django 4.0.3 on 2022-05-02 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0012_alter_handlingrequesttype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handling.handlingrequesttype', verbose_name='Request Type'),
        ),
    ]
