# Generated by Django 4.0.3 on 2022-05-03 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0015_handlingrequest_dla_contracted_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingRequestFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelling_feedback', models.CharField(max_length=500, null=True, verbose_name='Fueling Feedback')),
                ('servicing_feedback', models.CharField(max_length=500, null=True, verbose_name='Ground Servicing Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('handling_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='handling.handlingrequest', verbose_name='Handling Request')),
            ],
            options={
                'db_table': 'handling_requests_feedback',
            },
        ),
    ]
