# Generated by Django 4.0.3 on 2022-05-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0012_alter_aircraft_type'),
        ('handling', '0018_handlingrequest_tail_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='tail_number',
            field=models.ForeignKey(blank=True, limit_choices_to={'details_rev__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircrafthistory', verbose_name='Tail Number'),
        ),
    ]
