# Generated by Django 4.0.3 on 2022-05-07 22:48

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0083_alter_organisation_options'),
        ('handling', '0019_alter_handlingrequest_tail_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingRequestFuelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dla_contracted_fuel', models.BooleanField(default=False, verbose_name='Coordination with DLA Contracted Supplier?')),
                ('fuel_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fuel Order Number')),
                ('processed_by', models.CharField(max_length=50, verbose_name='Processed By')),
                ('fuel_release', models.FileField(blank=True, null=True, storage=app.storage_backends.FuelReleaseStorage(), upload_to='', verbose_name='Upload Fuel Release')),
                ('handling_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_booking', to='handling.handlingrequest', verbose_name='Servicing & Fueling Request')),
                ('ipa', models.ForeignKey(limit_choices_to={'details__type_id': 4, 'ipa_details__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='handling_requests_fuel_bookings', to='organisation.organisation', verbose_name='IPA')),
            ],
            options={
                'db_table': 'handling_requests_fuel_confirmations',
            },
        ),
    ]
