# Generated by Django 4.0.3 on 2022-05-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0020_handlingrequestfuelbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlingrequest',
            name='dla_contracted_fuel',
        ),
        migrations.RemoveField(
            model_name='handlingrequest',
            name='ipa',
        ),
        migrations.RemoveField(
            model_name='handlingrequest',
            name='legacy_fuel_order_id',
        ),
        migrations.RemoveField(
            model_name='handlingrequest',
            name='legacy_fuel_order_ipa_name',
        ),
        migrations.RemoveField(
            model_name='handlingrequest',
            name='legacy_fuel_order_status_code',
        ),
    ]
