# Generated by Django 4.0.3 on 2022-05-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0021_remove_handlingrequest_dla_contracted_fuel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handlingrequestamendment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='handlingrequestmovement',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='handlingrequestmovement',
            name='passengers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Passengers'),
        ),
    ]
