# Generated by Django 4.0.3 on 2022-05-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0022_alter_handlingrequestamendment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='air_card_expiration',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='AIR Card Expiration'),
        ),
        migrations.AlterField(
            model_name='handlingrequest',
            name='air_card_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='AIR Card Number'),
        ),
    ]
