# Generated by Django 4.0.3 on 2022-06-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_unitofmeasurement_description_plural'),
        ('handling', '0023_alter_handlingrequest_air_card_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingservice',
            name='is_allowed_free_text',
            field=models.BooleanField(default=False, verbose_name='Allow Free Text Entry?'),
        ),
        migrations.AddField(
            model_name='handlingservice',
            name='is_allowed_quantity_selection',
            field=models.BooleanField(default=False, verbose_name='Allow Quantity Selection?'),
        ),
        migrations.AddField(
            model_name='handlingservice',
            name='quantity_selection_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unitofmeasurement', verbose_name='Unit of Measure'),
        ),
    ]
