# Generated by Django 4.0.3 on 2022-06-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_unitofmeasurement_description_plural'),
        ('handling', '0024_handlingservice_is_allowed_free_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestservices',
            name='booking_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity Required'),
        ),
        migrations.AddField(
            model_name='handlingrequestservices',
            name='booking_quantity_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_fluid_uom': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Quantity Required UOM'),
        ),
        migrations.AddField(
            model_name='handlingrequestservices',
            name='booking_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='handlingservice',
            name='quantity_selection_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_fluid_uom': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unitofmeasurement', verbose_name='Unit of Measure'),
        ),
    ]
