# Generated by Django 4.0.3 on 2022-06-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0025_handlingrequestservices_booking_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handlingservice',
            options={'ordering': ['name']},
        ),
    ]
