# Generated by Django 4.0.3 on 2022-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0026_alter_handlingservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingservice',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted At'),
        ),
    ]
