# Generated by Django 4.0.3 on 2022-07-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aircardprefix_valid_from'),
        ('handling', '0028_handlingrequest_air_card_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='air_card_prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aircardprefix', verbose_name='AIR Card Prefix'),
        ),
    ]
