# Generated by Django 4.0.3 on 2022-07-09 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0029_alter_handlingrequest_air_card_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestamendment',
            name='created_by_text',
            field=models.CharField(max_length=50, null=True, verbose_name='Person (guest)'),
        ),
        migrations.AlterField(
            model_name='serviceprovisionform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
