# Generated by Django 4.0.3 on 2022-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0031_movementdirection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingservice',
            name='is_dla',
            field=models.BooleanField(db_index=True, default=False, help_text='Once been enabled - all airports settings will be cleared',
                                      verbose_name='Always Display in Services Lists?'),
        ),
    ]
