# Generated by Django 4.0.3 on 2022-07-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0032_alter_handlingservice_is_dla'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='New Request'),
        ),
    ]
