# Generated by Django 4.0.3 on 2022-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0033_handlingrequest_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestmovement',
            name='ppr_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prior Permission Requested Number'),
        ),
        migrations.AlterField(
            model_name='handlingrequest',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='New Request'),
        ),
    ]
