# Generated by Django 4.0.3 on 2022-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0034_handlingrequestmovement_ppr_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='mission_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mission Number'),
        ),
        migrations.AlterField(
            model_name='handlingrequest',
            name='amended',
            field=models.BooleanField(default=False, verbose_name='Amended'),
        ),
    ]
