# Generated by Django 4.0.3 on 2022-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0035_handlingrequest_mission_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='apacs_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='APACS Number'),
        ),
    ]
