# Generated by Django 4.0.3 on 2022-08-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_is_invitation_sent'),
        ('organisation', '0090_alter_organisationlogomotto_cascade_to_departments'),
        ('handling', '0039_move_contact_person_to_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlingrequest',
            name='customer_person',
        ),
        migrations.AlterField(
            model_name='handlingrequestcrew',
            name='handling_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_crew', to='handling.handlingrequest', verbose_name='Handling Request'),
        ),
        migrations.AlterField(
            model_name='handlingrequestcrew',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_crews', to='user.person', verbose_name='Crew Member'),
        ),
        migrations.AlterField(
            model_name='handlingrequestfuelbooking',
            name='ipa',
            field=models.ForeignKey(limit_choices_to={'details__type_id__in': [3, 4]}, on_delete=django.db.models.deletion.CASCADE, related_name='handling_requests_fuel_bookings', to='organisation.organisation', verbose_name='IPA'),
        ),
    ]
