# Generated by Django 4.0.3 on 2022-09-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_flighttype_geographichflighttype'),
        ('handling', '0040_remove_handlingrequest_customer_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='fuel_quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Fuel Quantity'),
        ),
        migrations.AlterField(
            model_name='handlingrequest',
            name='fuel_required',
            field=models.ForeignKey(blank=True, choices=[('NO_FUEL', 'No Fuel'), ('ARRIVAL', 'On Arrival'), ('DEPARTURE', 'On Departure')], db_column='fuel_required_on', null=True, on_delete=django.db.models.deletion.RESTRICT, to='handling.movementdirection', verbose_name='Fuel Required'),
        ),
        migrations.AlterField(
            model_name='handlingrequest',
            name='fuel_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Fuel Unit'),
        ),
    ]
