# Generated by Django 4.0.3 on 2022-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0041_alter_handlingrequest_fuel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='decline_reason',
            field=models.CharField(max_length=255, null=True, verbose_name='Decline Reason'),
        ),
        migrations.AddField(
            model_name='handlingrequest',
            name='is_unable_to_support',
            field=models.BooleanField(default=False, verbose_name='Unable To Support?'),
        ),
    ]
