# Generated by Django 4.0.3 on 2022-09-18 14:13

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0042_handlingrequest_decline_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='apacs_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Diplomatic Clearance'),
        ),
        migrations.CreateModel(
            name='AutoServiceProvisionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spf_document', models.FileField(null=True, storage=app.storage_backends.AutoSPFDocumentsStorage(), upload_to='', verbose_name='SPF Document')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('handling_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_spf', to='handling.handlingrequest')),
            ],
            options={
                'db_table': 'spf_auto_submissions',
                'managed': True,
            },
        ),
    ]
