# Generated by Django 4.0.3 on 2022-09-19 15:15

from django.db import migrations, models


def update_handling_request_handling_confirmed(apps, schema):
    handling_request_cls = apps.get_model('handling', 'HandlingRequest')
    handling_requests = handling_request_cls.objects.all()

    for handling_request in handling_requests:
        if not handling_request.is_new:
            handling_request_cls.objects.filter(
                pk=handling_request.pk
            ).update(
                is_handling_confirmed=True
            )


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0043_alter_handlingrequest_apacs_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='is_handling_confirmed',
            field=models.BooleanField(default=False, verbose_name='Handling Confirmed'),
        ),
        migrations.RunPython(update_handling_request_handling_confirmed),
    ]
