# Generated by Django 4.0.3 on 2022-09-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_is_invitation_sent'),
        ('handling', '0044_handlingrequest_is_handling_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='assigned_mil_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_handling_requests', to='user.person', verbose_name='Assigned Mil Team Member'),
        ),
    ]
