# Generated by Django 4.0.3 on 2022-10-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0045_handlingrequest_assigned_mil_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='customer_organisation',
            field=models.ForeignKey(limit_choices_to={'operator_details__isnull': False, 'operator_details__type_id__in': [13, 14, 15, 16, 17]}, on_delete=django.db.models.deletion.CASCADE, related_name='handling_requests', to='organisation.organisation', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='handlingservice',
            name='organisations',
            field=models.ManyToManyField(blank=True, help_text='Service usage will be locked only to selected organisations.', limit_choices_to={'operator_details__isnull': False, 'operator_details__type_id__in': [13, 14, 15, 16, 17]}, related_name='organisation_specific_handling_services', through='handling.HandlingServiceOrganisationSpecific', to='organisation.organisation', verbose_name='Applicable Unit(s)'),
        ),
    ]
