# Generated by Django 4.0.3 on 2022-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0047_alter_handlingrequest_customer_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='is_amended_callsign',
            field=models.BooleanField(default=False, verbose_name='Callsign Amended'),
        ),
    ]
