# Generated by Django 4.0.3 on 2022-11-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0048_handlingrequest_is_amended_callsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingRequestNotificationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_handler_parking_confirmation_email_sent', models.BooleanField(default=False, verbose_name='Handler Parking Confirmation Email Sent')),
                ('handling_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='handling.handlingrequest')),
            ],
            options={
                'db_table': 'handling_requests_notifications_log',
            },
        ),
    ]
