# Generated by Django 4.0.3 on 2022-11-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0046_alter_handlingrequest_assigned_mil_team_member'),
        ('handling', '0049_handlingrequestnotificationslog'),
    ]

    operations = [
    ]
