# Generated by Django 4.0.3 on 2022-11-18 16:47

from django.db import migrations, models
import django.db.models.deletion


def migrate_data(apps, schema_editor):
    handling_request_movement_cls = apps.get_model('handling', 'HandlingRequestMovement')
    movements = handling_request_movement_cls.objects.all()

    for movement in movements:
        if movement.passengers and movement.passengers > 0:
            movement.is_passengers_onboard = True
            movement.is_passengers_tbc = False

        movement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0100_airportdetails_updated_at_and_more'),
        ('handling', '0050_merge_20221103_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestmovement',
            name='is_passengers_onboard',
            field=models.BooleanField(default=False, verbose_name='Is Passengers Onboard?'),
        ),
        migrations.AddField(
            model_name='handlingrequestmovement',
            name='is_passengers_tbc',
            field=models.BooleanField(default=False, verbose_name='Is Passengers TBC?'),
        ),
        migrations.AlterField(
            model_name='handlingrequestfuelbooking',
            name='ipa',
            field=models.ForeignKey(limit_choices_to={'ipa_locations__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='handling_requests_fuel_bookings', to='organisation.organisation', verbose_name='IPA'),
        ),
        migrations.RunPython(migrate_data),
    ]
