# Generated by Django 4.0.3 on 2022-11-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0051_handlingrequestmovement_is_passengers_onboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingservice',
            name='is_passengers_handling',
            field=models.BooleanField(default=False, verbose_name='Is Passengers Handling?'),
        ),
    ]
