# Generated by Django 4.0.3 on 2022-11-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0052_handlingservice_is_passengers_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequestmovement',
            name='is_passengers_onboard',
            field=models.BooleanField(default=False, verbose_name='Pax Onboard?'),
        ),
    ]
