# Generated by Django 4.0.3 on 2022-11-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pricingunit_description'),
        ('handling', '0053_alter_handlingrequestmovement_is_passengers_onboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='fuel_unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_fluid_uom': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Fuel Unit'),
        ),
    ]
