# Generated by Django 4.0.3 on 2022-12-06 23:47

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_last_token_sent_at'),
        ('handling', '0054_alter_handlingrequest_fuel_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingRequestDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('is_staff_added', models.BooleanField(default=True, verbose_name='Is Staff Document?')),
                ('handling_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='handling.handlingrequest', verbose_name='Handling Request')),
            ],
            options={
                'db_table': 'handling_requests_documents',
            },
        ),
        migrations.CreateModel(
            name='HandlingRequestDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'handling_requests_documents_types',
            },
        ),
        migrations.CreateModel(
            name='HandlingRequestDocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=app.storage_backends.HandlingRequestDocumentFilesStorage(), upload_to='', verbose_name='File')),
                ('is_recent', models.BooleanField(default=True, verbose_name='Is File Recent?')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='handling.handlingrequestdocument', verbose_name='Document')),
            ],
            options={
                'db_table': 'handling_requests_documents_files',
            },
        ),
        migrations.AddField(
            model_name='handlingrequestdocument',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='handling.handlingrequestdocumenttype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='handlingrequestdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_requests_documents', to='user.person', verbose_name='Uploaded By'),
        ),
    ]
