# Generated by Django 4.0.3 on 2022-12-07 00:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_last_token_sent_at'),
        ('handling', '0055_handlingrequestdocument_handlingrequestdocumenttype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlingrequestdocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='handlingrequestdocument',
            old_name='uploaded_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='handlingrequestdocumentfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Uploaded At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handlingrequestdocumentfile',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='handling_requests_document_files', to='user.person', verbose_name='Uploaded By'),
            preserve_default=False,
        ),
    ]
