# Generated by Django 4.0.3 on 2023-01-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0101_operatorpreferredgroundhandler'),
        ('handling', '0056_rename_uploaded_at_handlingrequestdocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handlingrequestdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='handlingrequest',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_handling_requests', to='organisation.organisation', verbose_name='Location'),
        ),
    ]
