# Generated by Django 4.0.3 on 2023-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0057_alter_handlingrequestdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='parking_confirmed_on_day_of_arrival',
            field=models.BooleanField(default=False, verbose_name='Parking confirmed on day of arrival'),
        ),
    ]
