# Generated by Django 4.0.3 on 2023-01-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0016_aircraftweightunit'),
        ('organisation', '0103_organisationopsdetails'),
        ('handling', '0058_handlingrequest_parking_confirmed_on_day_of_arrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingRequestAmendmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_gh_opened', models.BooleanField(default=True, verbose_name='Is GH Amendment Opened')),
                ('callsign', models.CharField(blank=True, max_length=50, null=True, verbose_name='Callsign')),
                ('arrival_date', models.DateTimeField(null=True, verbose_name='Arrival Date')),
                ('departure_date', models.DateTimeField(null=True, verbose_name='Departure Date')),
                ('arrival_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment_sessions_arrival_from', to='organisation.organisation', verbose_name='Arrival From')),
                ('departure_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment_sessions_departure_to', to='organisation.organisation', verbose_name='Departure To')),
                ('handling_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_sessions', to='handling.handlingrequest', verbose_name='Handling Request')),
            ],
            options={
                'db_table': 'handling_requests_amendment_sessions',
            },
        ),
        migrations.CreateModel(
            name='HandlingRequestAmendmentSessionService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_added', models.BooleanField(default=False, verbose_name='Is Added?')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Is Removed')),
                ('amendment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_services', to='handling.handlingrequestamendmentsession', verbose_name='Amendment Session')),
                ('direction', models.ForeignKey(db_column='direction_code', on_delete=django.db.models.deletion.CASCADE, related_name='amendment_session_services', to='handling.movementdirection', verbose_name='Movement')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='amendment_session_services', to='handling.handlingservice', verbose_name='Service')),
            ],
            options={
                'db_table': 'handling_requests_amendment_sessions_services',
            },
        ),
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='services',
            field=models.ManyToManyField(blank=True, through='handling.HandlingRequestAmendmentSessionService', to='handling.handlingservice', verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='tail_number',
            field=models.ForeignKey(blank=True, limit_choices_to={'details_rev__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircrafthistory', verbose_name='Tail Number'),
        ),
    ]
