# Generated by Django 4.0.3 on 2023-01-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0059_handlingrequestamendmentsession_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlingrequestamendmentsession',
            old_name='arrival_from',
            new_name='arrival_airport',
        ),
        migrations.RenameField(
            model_name='handlingrequestamendmentsession',
            old_name='departure_to',
            new_name='departure_airport',
        ),
    ]
