# Generated by Django 4.0.3 on 2023-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0060_rename_arrival_from_handlingrequestamendmentsession_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='is_gh_sent',
            field=models.BooleanField(default=False, verbose_name='Is sent to GH'),
        ),
    ]
