# Generated by Django 4.0.3 on 2023-02-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0063_handlingrequestrecurrence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlingrequestrecurrencemission',
            old_name='group',
            new_name='recurrence',
        ),
        migrations.AlterModelTable(
            name='handlingrequestrecurrence',
            table='handling_requests_recurrences',
        ),
    ]
