# Generated by Django 4.0.3 on 2023-02-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0064_rename_group_handlingrequestrecurrencemission_recurrence_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='handlingrequestrecurrencemission',
            table='handling_requests_recurrences_missions',
        ),
    ]
