# Generated by Django 4.0.3 on 2023-02-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0066_handlingrequestfuelbooking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='apacs_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='APACS URL'),
        ),
    ]
