# Generated by Django 4.0.3 on 2023-03-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_persongender'),
        ('handling', '0067_handlingrequest_apacs_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingRequestPassengersPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(verbose_name='Identifier')),
                ('weight', models.IntegerField(verbose_name='Weight (lbs)')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
                ('is_arrival', models.BooleanField(default=False, verbose_name='Arriving')),
                ('is_departure', models.BooleanField(default=False, verbose_name='Departing')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_request_passenger_payloads', to='user.persongender', verbose_name='Gender')),
                ('handling_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers_payloads', to='handling.handlingrequest', verbose_name='Passengers Payload')),
            ],
            options={
                'db_table': 'handling_requests_passengers_payloads',
            },
        ),
    ]
