# Generated by Django 4.0.3 on 2023-03-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0068_handlingrequestpassengerspayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='arrival_passengers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Arrival Passengers'),
        ),
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='departure_passengers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Departure Passengers'),
        ),
    ]
