# Generated by Django 4.0.3 on 2023-03-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0069_handlingrequestamendmentsession_arrival_passengers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingRequestCargoPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('width', models.IntegerField(verbose_name='Width')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('weight', models.IntegerField(verbose_name='Weight (lbs)')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('is_dg', models.BooleanField(default=False, verbose_name='Dangerous Goods')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('is_arrival', models.BooleanField(default=False, verbose_name='Arriving')),
                ('is_departure', models.BooleanField(default=False, verbose_name='Departing')),
            ],
            options={
                'db_table': 'handling_requests_payloads_cargo',
            },
        ),
    ]
