# Generated by Django 4.0.3 on 2023-03-03 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0071_alter_handlingrequestpassengerspayload_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestcargopayload',
            name='handling_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_payloads', to='handling.handlingrequest', verbose_name='Handling Request'),
            preserve_default=False,
        ),
    ]
