# Generated by Django 4.0.3 on 2023-03-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0072_handlingrequestcargopayload_handling_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='arrival_is_passengers_onboard',
            field=models.BooleanField(null=True, verbose_name='Pax Onboard?'),
        ),
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='arrival_is_passengers_tbc',
            field=models.BooleanField(null=True, verbose_name='Is Passengers TBC?'),
        ),
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='departure_is_passengers_onboard',
            field=models.BooleanField(null=True, verbose_name='Pax Onboard?'),
        ),
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='departure_is_passengers_tbc',
            field=models.BooleanField(null=True, verbose_name='Is Passengers TBC?'),
        ),
    ]
