# Generated by Django 4.0.3 on 2023-03-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0073_handlingrequestamendmentsession_arrival_is_passengers_onboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingServiceSpfRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'handling_services_spf_representations',
            },
        ),
        migrations.AddField(
            model_name='handlingservice',
            name='codename',
            field=models.SlugField(blank=True, max_length=25, null=True, unique=True, verbose_name='Code Name'),
        ),
        migrations.AddField(
            model_name='handlingservice',
            name='represent_in_spf_as',
            field=models.ManyToManyField(blank=True, related_name='spf_represented_by', through='handling.HandlingServiceSpfRepresentation', to='handling.handlingservice'),
        ),
        migrations.AddField(
            model_name='handlingservicespfrepresentation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spf_representations', to='handling.handlingservice', verbose_name='Service'),
        ),
    ]
