# Generated by Django 4.0.3 on 2023-03-06 19:11

from django.db import migrations, models
import django.db.models.deletion


def update_handling_services_codenames(apps, schema):
    handling_service_cls = apps.get_model('handling', 'HandlingService')

    service = handling_service_cls.objects.filter(
        name='Hotel Transportation',
    ).first()
    service.name = 'Transportation, Hotel'
    service.codename = 'transportation_hotel'
    service.save()

    service = handling_service_cls.objects.filter(
        name='Crew Transportation',
    ).first()
    service.codename = 'crew_transportation'
    service.save()

    service = handling_service_cls.objects.filter(
        is_passengers_handling=True,
    ).first()
    service.codename = 'passengers_handling'
    service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0074_handlingservicespfrepresentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingservicespfrepresentation',
            name='represent_as',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='represent', to='handling.handlingservice', verbose_name='Represent As'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handlingservicespfrepresentation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='represented_by', to='handling.handlingservice', verbose_name='Service'),
        ),
        migrations.RunPython(update_handling_services_codenames),
    ]
