# Generated by Django 4.0.3 on 2023-04-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_traveldocument_number_and_more'),
        ('handling', '0076_remove_handlingservice_is_passengers_handling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestdocumentfile',
            name='is_signed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is Signed?'),
        ),
        migrations.AddField(
            model_name='handlingrequestdocumentfile',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handling_request_document_files', to='user.person', verbose_name='Person'),
        ),
    ]
