# Generated by Django 4.0.3 on 2023-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0077_handlingrequestdocumentfile_is_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='is_standalone',
            field=models.BooleanField(default=True, verbose_name='Is Standalone'),
        ),
    ]
