# Generated by Django 4.0.3 on 2023-05-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0078_handlingrequest_is_standalone'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestdocumentfile',
            name='signed_at',
            field=models.DateTimeField(null=True, verbose_name='Signed At'),
        ),
    ]
