# Generated by Django 4.0.3 on 2023-05-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0106_organisationpeople_is_authorising_person_and_more'),
        ('core', '0035_alter_activitylog_data'),
        ('handling', '0080_alter_handlingrequestmovement_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestamendmentsessionservice',
            name='booking_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity Required'),
        ),
        migrations.AddField(
            model_name='handlingrequestamendmentsessionservice',
            name='booking_quantity_uom',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_fluid_uom': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unitofmeasurement', verbose_name='Quantity Required UOM'),
        ),
        migrations.AddField(
            model_name='handlingrequestamendmentsessionservice',
            name='booking_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='handlingrequestmovement',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisation', verbose_name='Airport'),
        ),
    ]
