# Generated by Django 4.0.3 on 2023-05-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_missionlegservicing_handling_request'),
        ('handling', '0081_alter_handlingrequestmovement_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestdocument',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mission.mission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='handlingrequestdocument',
            name='handling_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='handling.handlingrequest', verbose_name='Handling Request'),
        ),
    ]
