# Generated by Django 4.0.3 on 2023-06-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0081_handlingrequestamendmentsessionservice_booking_quantity_and_more'),
        ('handling', '0083_handlingrequestdocument_mission_leg'),
    ]

    operations = [
    ]
