# Generated by Django 4.0.3 on 2023-08-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_activitylog_mission_leg'),
        ('handling', '0084_merge_20230601_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
            ],
            options={
                'permissions': [('p_view', 'DoD Servicing: View section pages'), ('p_dod_comms', 'DoD Servicing: DoD Comms chat access'), ('p_sfr_export_data', 'DoD Servicing: S&F Request Data Export'), ('p_create', 'DoD Servicing: Create anything'), ('p_update', 'DoD Servicing: Update anything')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.globalconfiguration',),
        ),
    ]
