# Generated by Django 4.0.3 on 2023-08-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0085_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('p_view', 'DoD Servicing: View section pages'), ('p_dod_comms', 'DoD Servicing: DoD Comms chat access'), ('p_sfr_export_data', 'DoD Servicing: S&F Request Data Export'), ('p_create', 'DoD Servicing: Create anything'), ('p_update', 'DoD Servicing: Update anything'), ('p_activity_log_view', 'DoD Servicing: View Activity Log')]},
        ),
    ]
