# Generated by Django 4.0.3 on 2023-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0086_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequestmovement',
            name='ppr_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PPR Number'),
        ),
    ]
