# Generated by Django 4.0.3 on 2023-08-11 19:24

from django.db import migrations


def migrate_handling_request_amendments_to_activity_log(apps, schema):
    handling_request_cls = apps.get_model('handling', 'HandlingRequest')
    sfr_to_process = handling_request_cls.objects.all()

    for sfr in sfr_to_process:
        for amendment_row in sfr.amendments.all():
            record_slug = ''
            if amendment_row.tail_number_changed:
                record_slug = 'sfr_tail_number_id_amendment'

            sfr.activity_log.create(
                record_slug=record_slug,
                author=amendment_row.created_by,
                created_at=amendment_row.created_at,
                details=amendment_row.details,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0087_alter_handlingrequestmovement_ppr_number'),
        ('core', '0043_activitylog_handling_request_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_handling_request_amendments_to_activity_log)
    ]
