# Generated by Django 4.0.3 on 2023-08-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0088_migrate_amendments_to_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequest',
            name='is_aog',
            field=models.BooleanField(default=False, verbose_name='AOG'),
        ),
    ]
