# Generated by Django 4.0.3 on 2023-09-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0109_alter_operatorpreferredgroundhandler_ground_handler_and_more'),
        ('handling', '0089_handlingrequest_is_aog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrequest',
            name='handling_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'handler_details__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handler_handling_requests', to='organisation.organisation', verbose_name='Handling Agent'),
        ),
    ]
