# Generated by Django 4.0.3 on 2023-09-25 14:29

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0089_handlingrequest_is_aog'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestcargopayload',
            name='sync_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AddField(
            model_name='handlingrequestpassengerspayload',
            name='sync_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
