# Generated by Django 4.0.3 on 2023-09-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0090_alter_handlingrequest_handling_agent'),
        ('handling', '0090_handlingrequestcargopayload_sync_id_and_more'),
    ]

    operations = [
    ]
