# Generated by Django 4.0.3 on 2023-10-02 17:20

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0090_handlingrequestcargopayload_sync_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handlingrequestcargopayload',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='handlingrequestpassengerspayload',
            options={'ordering': ['identifier']},
        ),
        migrations.AddField(
            model_name='handlingrequestdocument',
            name='is_dod_viewable',
            field=models.BooleanField(default=True, verbose_name='Is DoD Viewable?'),
        ),
        migrations.AlterField(
            model_name='handlingrequestcargopayload',
            name='sync_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='handlingrequestpassengerspayload',
            name='sync_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22),
        ),
    ]
