# Generated by Django 4.0.3 on 2023-10-02 17:19

from django.db import migrations


def handling_requests_update_is_dod_viewable(apps, schema):
    documents_cls = apps.get_model('handling', 'HandlingRequestDocument')
    documents_to_process = documents_cls.objects.all()

    for document in documents_to_process:
        if document.type_id == 4:
            document.is_dod_viewable = False
            document.save()


class Migration(migrations.Migration):
    dependencies = [
        ('handling', '0091_alter_handlingrequestcargopayload_options_and_more'),
    ]

    operations = [
        migrations.RunPython(handling_requests_update_is_dod_viewable)
    ]
