# Generated by Django 4.0.3 on 2023-10-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0091_merge_20230929_1355'),
        ('handling', '0092_auto_20231002_1721'),
    ]

    operations = [
    ]
