# Generated by Django 4.0.3 on 2023-10-06 12:20

from django.db import migrations


def handling_requests_update_is_dod_viewable_for_type_id_14(apps, schema):
    documents_cls = apps.get_model('handling', 'HandlingRequestDocument')
    documents_to_process = documents_cls.objects.all()

    for document in documents_to_process:
        if document.type_id == 14:
            document.is_dod_viewable = False
            document.save()


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0092_auto_20231002_1721'),
    ]

    operations = [
        migrations.RunPython(handling_requests_update_is_dod_viewable_for_type_id_14)
    ]
