# Generated by Django 4.0.3 on 2023-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0091_merge_20231002_1021'),
        ('handling', '0093_merge_20231002_2040'),
    ]

    operations = [
    ]
