# Generated by Django 4.0.3 on 2023-10-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0091_merge_20231002_1021'),
        ('handling', '0093_auto_20231006_1220'),
    ]

    operations = [
    ]
