# Generated by Django 4.0.3 on 2023-10-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0093_merge_20231006_1200'),
        ('handling', '0094_merge_20231006_1746'),
    ]

    operations = [
    ]
