# Generated by Django 4.0.3 on 2023-10-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0094_merge_20231006_1042'),
        ('handling', '0094_merge_20231006_1746'),
    ]

    operations = [
    ]
