# Generated by Django 4.0.3 on 2023-10-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0093_merge_20231006_1200'),
        ('handling', '0095_merge_20231006_1747'),
    ]

    operations = [
    ]
