# Generated by Django 4.2.6 on 2023-10-28 16:45

from django.db import migrations
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0096_alter_handlingrequestcargopayload_sync_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlingrequestcargopayload",
            name="sync_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="handlingrequestpassengerspayload",
            name="sync_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
    ]
