# Generated by Django 4.0.3 on 2023-10-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0095_merge_20231011_1442'),
        ('handling', '0096_merge_20231010_1707'),
    ]

    operations = [
    ]
