# Generated by Django 4.2.6 on 2023-11-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_customnotification_options_and_more'),
        ('organisation', '0114_alter_organisationcontactdetails_email_address'),
        ('handling', '0097_alter_handlingrequestcargopayload_sync_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SfrOpsChecklistCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 'aml_sfr_ops_checklist_categories',
            },
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('p_view', 'DoD Servicing: View section pages'), ('p_dod_comms', 'DoD Servicing: DoD Comms chat access'), ('p_sfr_export_data', 'DoD Servicing: S&F Request Data Export'), ('p_create', 'DoD Servicing: Create anything'), ('p_update', 'DoD Servicing: Update anything'), ('p_activity_log_view', 'DoD Servicing: View Activity Log'), ('p_manage_sfr_ops_checklist_settings', 'DoD Servicing: Manage SFR Ops Checklist Settings')]},
        ),
        migrations.CreateModel(
            name='SfrOpsChecklistParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(blank=True, limit_choices_to={'airport_details__isnull': False, 'details__type_id': 8}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_specific_sfr_ops_checklist_parameters', to='organisation.organisation', verbose_name='Location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='handling.sfropschecklistcategory', verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'db_table': 'aml_sfr_ops_checklist_parameters',
            },
        ),
        migrations.CreateModel(
            name='HandlingRequestOpsChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfr_ops_checklist_items', to='handling.handlingrequest', verbose_name='Handling Request')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_item_instances', to='handling.sfropschecklistparameter', verbose_name='Checklist Item')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed?')),
                ('completed_at', models.DateTimeField(null=True, verbose_name='Completed At')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sfr_ops_checklist_items', to='user.person', verbose_name='Completed By')),
            ],
            options={
                'db_table': 'handling_requests_ops_checklist',
            },
        ),
    ]
