# Generated by Django 4.2.6 on 2023-10-30 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0097_alter_handlingrequestcargopayload_sync_id_and_more"),
        ("handling", "0097_merge_20231012_1116"),
    ]

    operations = []
