# Generated by Django 4.2.6 on 2023-11-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0098_handlingrequestspf_handlingrequestspfservice_and_more"),
        (
            "organisation",
            "0114_dlaservice_handlerspfservice_dlaservicemapping_and_more",
        ),
        ("user", "0032_alter_customnotification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingrequestspfservice",
            name="dla_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spf_v2_services",
                to="organisation.dlaservice",
                verbose_name="DLA Service",
            ),
        ),
        migrations.AddField(
            model_name="handlingrequestspfservice",
            name="handling_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spf_v2_services",
                to="handling.handlingservice",
                verbose_name="Handling Service",
            ),
        ),
        migrations.AddField(
            model_name="handlingrequestspfservice",
            name="spf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="handling.handlingrequestspf",
                verbose_name="SPF",
            ),
        ),
        migrations.AddField(
            model_name="handlingrequestspf",
            name="handling_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spf_v2",
                to="handling.handlingrequest",
                verbose_name="S&F Request",
            ),
        ),
        migrations.AddField(
            model_name="handlingrequestspf",
            name="reconciled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reconciled_spf_v2",
                to="user.person",
                verbose_name="Reconciled By",
            ),
        ),
    ]
