# Generated by Django 4.2.6 on 2023-11-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0098_sfropschecklistcategory_alter_permissions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sfropschecklistcategory',
            options={'ordering': ['name']},
        ),
    ]
