# Generated by Django 4.2.6 on 2023-11-07 15:54

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0099_handlingrequestspfservice_dla_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlingrequestcargopayload",
            name="sync_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True, editable=False, max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="handlingrequestpassengerspayload",
            name="sync_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True, editable=False, max_length=22
            ),
        ),
        migrations.AlterModelOptions(
            name="permissions",
            options={
                "permissions": [
                    ("p_view", "DoD Servicing: View section pages"),
                    ("p_dod_comms", "DoD Servicing: DoD Comms chat access"),
                    ("p_sfr_export_data", "DoD Servicing: S&F Request Data Export"),
                    ("p_create", "DoD Servicing: Create anything"),
                    ("p_update", "DoD Servicing: Update anything"),
                    ("p_activity_log_view", "DoD Servicing: View Activity Log"),
                    (
                        "p_dla_services_update",
                        "DoD Servicing: Create or Update DLA Services",
                    ),
                    ("p_dla_services_view", "DoD Servicing: View DLA Services"),
                ]
            },
        ),
    ]
