# Generated by Django 4.2.6 on 2023-11-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0098_merge_20231030_1640'),
        ('handling', '0100_alter_handlingrequestcargopayload_sync_id_and_more'),
    ]

    operations = [
    ]
