# Generated by Django 4.2.6 on 2023-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0100_alter_handlingrequestcargopayload_sync_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingrequest",
            name="is_legacy_spf_v1",
            field=models.BooleanField(default=True, verbose_name="Use Legacy SPF V1"),
            preserve_default=False,
        ),
    ]
