# Generated by Django 4.2.6 on 2023-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0101_handlingrequest_is_legacy_spf_v1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlingrequest",
            name="is_legacy_spf_v1",
            field=models.BooleanField(default=False, verbose_name="Use Legacy SPF V1"),
        ),
    ]
