# Generated by Django 4.2.6 on 2023-11-07 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0101_merge_20231107_1722"),
        ("handling", "0102_alter_handlingrequest_is_legacy_spf_v1"),
    ]

    operations = []
