# Generated by Django 4.2.6 on 2023-11-08 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0102_alter_handlingrequest_is_legacy_spf_v1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissions",
            options={
                "permissions": [
                    ("p_view", "DoD Servicing: View section pages"),
                    ("p_dod_comms", "DoD Servicing: DoD Comms chat access"),
                    ("p_sfr_export_data", "DoD Servicing: S&F Request Data Export"),
                    ("p_create", "DoD Servicing: Create anything"),
                    ("p_update", "DoD Servicing: Update anything"),
                    ("p_activity_log_view", "DoD Servicing: View Activity Log"),
                    (
                        "p_dla_services_update",
                        "DoD Servicing: Create or Update DLA Services",
                    ),
                    ("p_dla_services_view", "DoD Servicing: View DLA Services"),
                    ("p_spf_v2_reconcile", "DoD Servicing: Reconcile SPF"),
                ]
            },
        ),
    ]
