# Generated by Django 4.2.6 on 2023-11-09 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0103_alter_permissions_options"),
        ("handling", "0103_merge_20231107_1804"),
    ]

    operations = []
