# Generated by Django 4.2.6 on 2023-11-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0116_alter_handlerspfservice_applies_after_minutes"),
        ("handling", "0103_alter_permissions_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingservice",
            name="dla_service",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handling_service",
                to="organisation.dlaservice",
                verbose_name="DLA Service",
            ),
        ),
    ]
