# Generated by Django 4.2.6 on 2023-11-10 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0104_handlingservice_dla_service"),
        ("handling", "0104_merge_20231109_1236"),
    ]

    operations = []
