# Generated by Django 4.2.6 on 2023-11-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0104_handlingservice_dla_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingservice",
            name="is_dla_v2",
            field=models.BooleanField(default=False, verbose_name="Is DLAv2 Service?"),
        ),
    ]
