# Generated by Django 4.2.6 on 2023-11-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0105_handlingservice_is_dla_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingservice",
            name="is_dla_v2_visible_arrival",
            field=models.BooleanField(
                default=False, verbose_name="SPFv2: Visible for Arrival"
            ),
        ),
        migrations.AddField(
            model_name="handlingservice",
            name="is_dla_v2_visible_departure",
            field=models.BooleanField(
                default=False, verbose_name="SPFv2: Visible for Departure"
            ),
        ),
        migrations.AddField(
            model_name="handlingservice",
            name="is_spf_v2_non_dla",
            field=models.BooleanField(
                default=False, verbose_name="SPFv2: Optional Service"
            ),
        ),
        migrations.AddField(
            model_name="handlingservice",
            name="is_spf_v2_visible",
            field=models.BooleanField(default=False, verbose_name="SPFv2: Visible"),
        ),
    ]
