# Generated by Django 4.2.6 on 2023-11-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0099_alter_sfropschecklistcategory_options_and_more'),
        ('handling', '0106_handlingservice_is_dla_v2_visible_arrival_and_more'),
    ]

    operations = [
    ]
