# Generated by Django 4.2.6 on 2023-11-17 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0105_merge_20231110_1412"),
        ("handling", "0106_handlingservice_is_dla_v2_visible_arrival_and_more"),
    ]

    operations = []
