# Generated by Django 4.2.6 on 2023-11-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0107_merge_20231117_1735'),
        ('handling', '0108_alter_handlingrequestopschecklistitem_options_and_more'),
    ]

    operations = [
    ]
