# Generated by Django 4.2.6 on 2023-11-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0022_alter_aircraft_asn_alter_aircraft_pax_seats_and_more'),
        ('handling', '0108_alter_handlingrequestopschecklistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingrequestamendmentsession',
            name='aircraft_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircrafttype', verbose_name='Aircraft Type'),
        ),
    ]
