# Generated by Django 4.2.6 on 2023-11-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0109_alter_handlingservice_is_spf_v2_non_dla'),
        ('handling', '0109_handlingrequestamendmentsession_aircraft_type'),
        ('handling', '0109_merge_20231121_1309'),
    ]

    operations = [
    ]
