# Generated by Django 4.2.6 on 2023-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0109_alter_handlingservice_is_spf_v2_non_dla"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="handlingrequestspfservice",
            constraint=models.UniqueConstraint(
                fields=("spf", "dla_service"), name="unique_spf_service"
            ),
        ),
    ]
