# Generated by Django 4.2.6 on 2023-11-30 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0111_alter_permissions_options"),
        ("handling", "0111_handlingrequest_is_awaiting_departure_update_confirmation"),
    ]

    operations = []
