# Generated by Django 4.2.6 on 2023-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0110_merge_20231122_1543'),
        ('handling', '0111_handlingrequest_is_awaiting_departure_update_confirmation'),
    ]

    operations = [
    ]
