# Generated by Django 4.2.6 on 2023-11-29 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0110_handlingrequestspfservice_unique_spf_service"),
        ("handling", "0112_merge_20231127_1630"),
    ]

    operations = []
