# Generated by Django 4.2.7 on 2023-12-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0111_alter_permissions_options'),
        ('handling', '0113_merge_20231129_1937'),
    ]

    operations = [
    ]
