# Generated by Django 4.2.6 on 2023-12-09 16:41

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0113_merge_20231206_2141"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingrequest",
            name="uuid",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True, editable=False, max_length=22
            ),
        ),
        migrations.AddField(
            model_name="handlingrequestnotificationslog",
            name="is_spf_gh_request_email_sent",
            field=models.BooleanField(
                default=False, verbose_name="GH SPF Request Sent"
            ),
        ),
    ]
