# Generated by Django 4.2.6 on 2023-12-09 16:41
import shortuuid
from django.db import migrations


def migrate_data(apps, schema):
    handling_request_cls = apps.get_model('handling', 'HandlingRequest')
    sfr_to_process = handling_request_cls.objects.all()

    for sfr in sfr_to_process:
        handling_request_cls.objects.filter(pk=sfr.pk).update(uuid=shortuuid.uuid())


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0114_handlingrequest_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
