# Generated by Django 4.2.7 on 2023-12-01 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0112_merge_20231130_1803"),
        ("handling", "0114_merge_20231201_1152"),
    ]

    operations = []
