# Generated by Django 4.2.6 on 2023-12-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0033_usersettings"),
        ("handling", "0115_sfr_generate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlingrequestdocument",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handling_requests_documents",
                to="user.person",
                verbose_name="Uploaded By",
            ),
        ),
        migrations.AlterField(
            model_name="handlingrequestdocumentfile",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handling_requests_document_files",
                to="user.person",
                verbose_name="Uploaded By",
            ),
        ),
    ]
