# Generated by Django 4.2.6 on 2023-12-08 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0113_merge_20231206_2141"),
        ("handling", "0115_merge_20231201_1539"),
    ]

    operations = []
