# Generated by Django 4.2.6 on 2023-12-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0033_usersettings"),
        ("handling", "0117_alter_permissions_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlingrequestcrew",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sfr_crews",
                to="user.person",
                verbose_name="Crew Member",
            ),
        ),
    ]
