# Generated by Django 4.2.6 on 2023-12-09 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0116_merge_20231208_1610"),
        ("handling", "0117_alter_permissions_options"),
    ]

    operations = []
