# Generated by Django 4.2.6 on 2023-12-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0118_alter_handlingrequestcrew_person'),
        ('handling', '0118_merge_20231209_1940'),
    ]

    operations = [
    ]
