# Generated by Django 4.2.6 on 2023-12-13 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handling", "0119_alter_permissions_options"),
        ("handling", "0119_merge_20231213_1154"),
    ]

    operations = []
